import * as M from '../core/math.js';
import {cloneMesh,mesh as makeMesh,face as makeFace} from './mesh.js';
import {triangulate,polygonArea} from './triangulate.js';
import {pointInPolygon} from '../core/selection.js';
const cache=new WeakMap();
export const edgeKey=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;
export function adjacency(mesh){if(cache.has(mesh))return cache.get(mesh);const edges=new Map(),faces=new Map(),vertexFaces=new Map();const add=(a,b,face=null,flags={})=>{const key=edgeKey(a,b);let edge=edges.get(key);if(!edge){edge={key,a:Math.min(a,b),b:Math.max(a,b),faces:new Set()};edges.set(key,edge);}Object.assign(edge,flags);if(face)edge.faces.add(face);};for(const f of mesh.faces){faces.set(f.id,f);for(const loop of f.loops)for(let i=0;i<loop.length;i++){const a=loop[i],b=loop[(i+1)%loop.length];add(a,b,f.id);if(!vertexFaces.has(a))vertexFaces.set(a,new Set());vertexFaces.get(a).add(f.id);}}for(const {a,b,...flags} of mesh.edges||[])add(a,b,null,flags);const result={edges,faces,vertexFaces};cache.set(mesh,result);return result;}
export function selectionForHit(mesh,hit,clicks=1){const graph=adjacency(mesh),faces=new Set(),edges=new Set();if(hit.edgeKey){const e=graph.edges.get(hit.edgeKey);if(!e)return {faces,edges};edges.add(e.key);if(clicks>=2)for(const id of e.faces)faces.add(id);}else if(hit.faceId){const f=graph.faces.get(hit.faceId);if(!f)return {faces,edges};faces.add(f.id);if(clicks>=2)for(const l of f.loops)for(let i=0;i<l.length;i++)edges.add(edgeKey(l[i],l[(i+1)%l.length]));}
 if(clicks===1&&faces.size){const queue=[...faces];for(let i=0;i<queue.length;i++){const f=graph.faces.get(queue[i]);for(const l of f.loops)for(let j=0;j<l.length;j++){const e=graph.edges.get(edgeKey(l[j],l[(j+1)%l.length]));if(e?.soft||mesh.smooth)for(const id of e.faces)if(!faces.has(id)){faces.add(id);queue.push(id);}}}}
 if(clicks>=3){const vertices=selectedVertices(mesh,{faces,edges}),queue=[...vertices],byVertex=new Map();for(const e of graph.edges.values())for(const v of [e.a,e.b]){if(!byVertex.has(v))byVertex.set(v,[]);byVertex.get(v).push(e);}for(let i=0;i<queue.length;i++)for(const e of byVertex.get(queue[i])||[]){edges.add(e.key);for(const id of e.faces)faces.add(id);for(const v of [e.a,e.b])if(!vertices.has(v)){vertices.add(v);queue.push(v);}}}return {faces,edges};}
export function selectedVertices(mesh,part){const graph=adjacency(mesh),ids=new Set();for(const id of part.faces||[])for(const i of graph.faces.get(id)?.loops.flat()||[])ids.add(i);for(const key of part.edges||[]){const e=graph.edges.get(key);if(e){ids.add(e.a);ids.add(e.b);}}return ids;}
export function transformedSelection(mesh,part,matrix,{autoFold=false}={}){const result=cloneMesh(mesh),ids=selectedVertices(mesh,part),faces=[];for(const i of ids)result.vertices[i]=M.transform(matrix,result.vertices[i]);for(const f of result.faces){if(f.loops.flat().some(i=>ids.has(i))){delete f.normal;delete f.uv;delete f.cornerNormals;const pts=f.loops[0].map(i=>result.vertices[i]),n=M.faceNormal(pts);if(pts.some(v=>Math.abs(M.dot(M.sub(v,pts[0]),n))>1e-5)){if(!autoFold)throw Error('This move makes a face nonplanar. Hold Alt to auto-fold.');const source=mesh.faces.find(x=>x.id===f.id),tri=triangulate(mesh.vertices,source.loops,source.normal);for(let i=0;i<tri.length;i+=3)faces.push(makeFace([tri.slice(i,i+3)],f.material));continue;}}faces.push(f);}result.faces=faces;return result;}
function edgeRecord(e){return {a:e.a,b:e.b,hidden:e.hidden,soft:e.soft,smooth:e.smooth};}
export function eraseSelection(mesh,part){const result=cloneMesh(mesh),graph=adjacency(mesh),remove=new Set(part.faces);for(const key of part.edges)for(const id of graph.edges.get(key)?.faces||[])remove.add(id);result.faces=result.faces.filter(f=>!remove.has(f.id));result.edges=[...graph.edges.values()].filter(e=>!part.edges.has(e.key)).map(edgeRecord);return result;}
export function extractSelection(mesh,part){const graph=adjacency(mesh),ids=selectedVertices(mesh,part),remap=new Map([...ids].map((id,i)=>[id,i]));const extracted=makeMesh([...ids].map(i=>mesh.vertices[i].slice()),mesh.faces.filter(f=>part.faces.has(f.id)).map(f=>({...f,loops:f.loops.map(l=>l.map(i=>remap.get(i)))})),mesh.name);extracted.edges=[...graph.edges.values()].filter(e=>part.edges.has(e.key)||[...e.faces].some(id=>part.faces.has(id))).filter(e=>remap.has(e.a)&&remap.has(e.b)).map(e=>({...edgeRecord(e),a:remap.get(e.a),b:remap.get(e.b)}));const rest=cloneMesh(mesh);rest.faces=rest.faces.filter(f=>!part.faces.has(f.id));rest.edges=[...graph.edges.values()].filter(e=>!part.edges.has(e.key)&&(!e.faces.size||[...e.faces].some(id=>!part.faces.has(id)))).map(edgeRecord);return {extracted,rest};}
function strictInside(p,loop,tol){for(let i=0;i<loop.length;i++){const a=loop[i],b=loop[(i+1)%loop.length],dx=b[0]-a[0],dy=b[1]-a[1],t=M.clamp(((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1),0,1);if(Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy)<=tol)return false;}return pointInPolygon(p,loop);}
/** Weld raw geometry in one editing context, with bounded planar face creation/splitting. */
export function mergeRaw(a,b,tolerance=1e-7){const result=cloneMesh(a),map=new Map(),remap=[],key=v=>v.map(x=>Math.round(x/tolerance)).join(',');result.vertices.forEach((v,i)=>map.set(key(v),i));for(const v of b.vertices){const k=key(v);if(!map.has(k)){map.set(k,result.vertices.length);result.vertices.push(v.slice());}remap.push(map.get(k));}const newIds=new Set();for(const f of b.faces){const id=M.uid('f');newIds.add(id);result.faces.push({...f,id,loops:f.loops.map(l=>l.map(i=>remap[i]))});}for(const e of b.edges||[])result.edges.push({...e,a:remap[e.a],b:remap[e.b]});result.curves=[...(a.curves||[]),...(b.curves||[]).map(c=>({...c,vertices:c.vertices?.map(i=>remap[i])}))];
 for(const f of result.faces)f.loops=f.loops.map(loop=>loop.flatMap((id,i)=>{const next=loop[(i+1)%loop.length],start=result.vertices[id],d=M.sub(result.vertices[next],start),d2=M.dot(d,d),inside=[];if(d2<tolerance*tolerance)return [id];for(const v of new Set(remap)){if(v===id||v===next)continue;const delta=M.sub(result.vertices[v],start),t=M.dot(delta,d)/d2;if(t>tolerance&&t<1-tolerance&&M.len(M.cross(delta,d))/Math.sqrt(d2)<tolerance)inside.push([t,v]);}return [id,...inside.sort((a,b)=>a[0]-b[0]).map(p=>p[1])];}));
 const remove=new Set();for(const fresh of result.faces.filter(f=>newIds.has(f.id))){if(fresh.loops.length!==1)continue;for(const host of result.faces){if(host===fresh||newIds.has(host.id))continue;const pts=host.loops[0].map(i=>result.vertices[i]),normal=M.faceNormal(pts),origin=pts[0];if(fresh.loops[0].some(i=>Math.abs(M.dot(M.sub(result.vertices[i],origin),normal))>tolerance))continue;const {u,v}=M.planeBasis(normal),flat=i=>{const p=M.sub(result.vertices[i],origin);return [M.dot(p,u),M.dot(p,v)];},outer=host.loops[0].map(flat),inner=fresh.loops[0].map(flat);if(fresh.loops[0].length===host.loops[0].length&&fresh.loops[0].every(i=>host.loops[0].includes(i))){remove.add(fresh.id);break;}if(inner.every(p=>strictInside(p,outer,tolerance))&&!host.loops.slice(1).some(h=>{const hole=h.map(flat);return inner.some(p=>pointInPolygon(p,hole))||hole.some(p=>pointInPolygon(p,inner));})){const hole=fresh.loops[0].slice();if(M.dot(M.faceNormal(hole.map(i=>result.vertices[i])),normal)>0)hole.reverse();const loops=[...host.loops,hole];try{triangulate(result.vertices,loops,normal);host.loops=loops;host.normal=normal;delete host.uv;delete host.cornerNormals;}catch{}break;}}}result.faces=result.faces.filter(f=>!remove.has(f.id));
 for(const e of b.edges||[]){const start=remap[e.a],end=remap[e.b];if(start===end)continue;for(let i=0;i<result.faces.length;i++){const f=result.faces[i];if(f.loops.length!==1)continue;const l=f.loops[0],a=l.indexOf(start),b=l.indexOf(end);if(a<0||b<0||Math.abs(a-b)===1||Math.abs(a-b)===l.length-1)continue;const [lo,hi]=[Math.min(a,b),Math.max(a,b)],one=l.slice(lo,hi+1),two=[...l.slice(hi),...l.slice(0,lo+1)],normal=M.faceNormal(l.map(i=>result.vertices[i]));try{triangulate(result.vertices,[one],normal);triangulate(result.vertices,[two],normal);const old=polygonArea(result.vertices,[l]),area=polygonArea(result.vertices,[one])+polygonArea(result.vertices,[two]);if(Math.abs(old-area)>Math.max(tolerance,old*1e-7))continue;result.faces.splice(i,1,{...f,loops:[one],normal,uv:undefined,cornerNormals:undefined},makeFace([two],f.material,{normal,tag:f.tag}));break;}catch{}}}return result;
}
export function eraseEdge(mesh,key){const result=cloneMesh(mesh),graph=adjacency(mesh),edge=graph.edges.get(key);if(!edge)return result;const faces=[...edge.faces].map(id=>graph.faces.get(id));let merged=null;if(faces.length===2){const [a,b]=faces,na=a.normal||M.faceNormal(a.loops[0].map(i=>mesh.vertices[i])),nb=b.normal||M.faceNormal(b.loops[0].map(i=>mesh.vertices[i]));if(M.dot(na,nb)>.99999){const segments=[];for(const f of faces)for(const l of f.loops)for(let i=0;i<l.length;i++)if(edgeKey(l[i],l[(i+1)%l.length])!==key)segments.push([l[i],l[(i+1)%l.length]]);const loops=[];while(segments.length){const first=segments.shift(),l=[first[0]];let end=first[1],valid=true;while(end!==first[0]){l.push(end);const index=segments.findIndex(e=>e[0]===end);if(index<0||l.length>mesh.vertices.length+1){valid=false;break;}end=segments.splice(index,1)[0][1];}if(!valid){loops.length=0;break;}loops.push(l);}if(loops.length){loops.sort((a,b)=>b.length-a.length);try{triangulate(mesh.vertices,loops,na);merged={...a,loops,normal:na,uv:undefined,cornerNormals:undefined};}catch{}}}}result.faces=result.faces.filter(f=>!edge.faces.has(f.id));if(merged)result.faces.push(merged);result.edges=[...graph.edges.values()].filter(e=>e.key!==key).map(edgeRecord);return result;}
