import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {importSkp} from '../src/importers/skp.js';import {importFiles} from '../src/importers/formats.js';import {bakeMesh,cloneMesh} from '../src/geometry/mesh.js';import {exportGLB} from '../src/exporters/formats.js';import {projectBounds,validateProject,Document} from '../src/core/document.js';
const fixture=process.env.SINGLETAKE_MODEL_FIXTURE;
const testFixture=(name,fn)=>test(name,{skip:!fixture},fn);
let project;
async function getProject(){if(!project){const bytes=await readFile(fixture);project=await importSkp(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'private model fixture');}return project;}
testFixture('Original private model fixture V26.2 loads with resolved geometry and component references',async()=>{const p=await getProject(),r=p.source.report;assert.equal(r.version,'26.2.0');assert.equal(r.definitions,154);assert.equal(r.instances,438);assert.equal(r.sourceFaces,19469);assert.equal(r.sourceVertices,24808);assert.equal(r.invalidFaces,0);assert.equal(r.unresolvedInstances,0);assert.equal(r.materials,52);assert.equal(r.textures,14);validateProject(p);});
testFixture('Every imported private model fixture mesh triangulates with its original face loops',async()=>{const p=await getProject(),start=performance.now();let triangles=0,errors=[];for(const m of Object.values(p.meshes)){const b=bakeMesh(m);triangles+=b.triangles.length;errors.push(...b.errors.map(e=>({mesh:m.name,...e})));}assert.equal(errors.length,0);assert.equal(triangles,46600);const data=await readFile(fixture);const report={...p.source.report,sha256:createHash('sha256').update(data).digest('hex'),bounds:projectBounds(p),uniqueMeshTriangles:triangles,triangulationErrors:errors.length,bakeMs:Math.round(performance.now()-start),validation:'Parser and CPU triangulation tested; native VFF model visual comparison and WebGPU rendering not tested.'};if(process.env.SINGLETAKE_IMPORT_REPORT)await writeFile(process.env.SINGLETAKE_IMPORT_REPORT,JSON.stringify(report,null,2));});
testFixture('Home imported meshes remain editable with undo and source geometry retained',async()=>{const d=new Document(),p=await getProject();d.replace(p);const id=Object.keys(p.meshes).find(id=>p.meshes[id].faces.length),before=p.meshes[id];d.transaction('Paint imported face',q=>{const m=cloneMesh(q.meshes[id]);m.faces[0].material=0;q.meshes[id]=m;});assert.notEqual(d.project.meshes[id],before);d.undo();assert.equal(d.project.meshes[id],before);});
testFixture('private model fixture exports as GLB and reloads with matching world bounds',async()=>{const p=await getProject(),blob=await exportGLB(p),q=await importFiles([{name:'fixture.glb',buffer:await blob.arrayBuffer()}]);validateProject(q);const a=projectBounds(p),b=projectBounds(q);for(const key of ['min','max'])for(let i=0;i<3;i++)assert.ok(Math.abs(a[key][i]-b[key][i])<1e-4,`Bounds ${key}[${i}] match`);assert.ok(q.nodes.length>=p.nodes.filter(n=>n.visible).length-5);});
