import test from 'node:test';import assert from 'node:assert/strict';import * as M from '../src/core/math.js';import * as G from '../src/geometry/mesh.js';
import {newProject,makeNode,projectBounds,sceneEntries} from '../src/core/document.js';
import {exportGLB,exportOBJ,exportSTL,exportPLY,exportDXF} from '../src/exporters/formats.js';
import {importFiles,importOBJ,importGLTF} from '../src/importers/formats.js';import {unzip} from '../src/io/zip.js';
const near=(a,b,e=1e-5)=>assert.ok(Math.abs(a-b)<e,`${a} ≈ ${b}`);
function sample(){const p=newProject('Test exchange'),m=G.box(2,3,4);p.meshes[m.id]=m;p.nodes.push(makeNode('First box',m.id),makeNode('Shared box',m.id,{matrix:M.translation([5,0,0])}));return p;}
const numTriangles=p=>sceneEntries(p).filter(e=>e.visible&&e.node.mesh).reduce((s,e)=>s+G.bakeMesh(p.meshes[e.node.mesh]).triangles.length,0);
test('GLB round-trip preserves placements, shared mesh resources, colors and geometry',async()=>{const p=sample();p.materials[0].color=[.3,.5,.7,1];const blob=await exportGLB(p),q=await importFiles([{name:'model.glb',buffer:await blob.arrayBuffer()}]);assert.equal(Object.keys(q.meshes).length,1);assert.equal(q.nodes.length,2);assert.equal(numTriangles(q),24);p.materials[0].color.forEach((v,i)=>near(q.materials[0].color[i],v));const b=projectBounds(q);near(b.max[0],7);near(b.max[1],3);near(b.max[2],4);});
test('GLB nested transform hierarchy survives a round-trip',async()=>{const p=sample(),parent=makeNode('Group',null,{matrix:M.translation([10,1,2])});p.nodes.push(parent);p.nodes[0].parent=parent.id;const q=await importFiles([{name:'nested.glb',buffer:await (await exportGLB(p)).arrayBuffer()}]);assert.equal(q.nodes.length,3);const first=sceneEntries(q).find(e=>e.node.name==='First box');near(first.matrix[12],10);near(first.matrix[13],1);});
test('GLB stores and recovers embedded image bytes',async()=>{const p=sample();p.materials[0].texture={bytes:new Uint8Array([137,80,78,71,1,2,3,4]),mime:'image/png',flipY:true};const q=await importFiles([{name:'image.glb',buffer:await (await exportGLB(p)).arrayBuffer()}]);assert.deepEqual(q.materials[0].texture.bytes,p.materials[0].texture.bytes);});
test('OBJ + MTL ZIP round-trip exports complete material companions',async()=>{const p=sample(),z=await unzip(await (await exportOBJ(p)).arrayBuffer()),files=[...z].map(([name,b])=>({name,buffer:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}));assert(z.has('materials.mtl'));const q=importOBJ(files,'model.obj');assert.equal(numTriangles(q),24);near(projectBounds(q).max[0],7);});
for(const [format,exporter] of [['stl',exportSTL],['ply',exportPLY],['dxf',exportDXF]])test(`${format.toUpperCase()} geometry round-trip`,async()=>{const p=sample(),blob=exporter(p),q=await importFiles([{name:'model.'+format,buffer:await blob.arrayBuffer()}]);assert.equal(numTriangles(q),24);const b=projectBounds(q);near(b.max[0],7);near(b.max[1],3);near(b.max[2],4);});
test('Exchange export omits hidden branches but native scene remains unchanged',async()=>{const p=sample();p.nodes[1].visible=false;const q=await importFiles([{name:'visible.glb',buffer:await (await exportGLB(p)).arrayBuffer()}]);assert.equal(numTriangles(q),12);assert.equal(p.nodes.length,2);});
test('Selected GLB export includes parents and excludes unrelated objects',async()=>{const p=sample(),q=await importFiles([{name:'selected.glb',buffer:await (await exportGLB(p,new Set([p.nodes[1].id]))).arrayBuffer()}]);assert.equal(numTriangles(q),12);near(projectBounds(q).min[0],5);});
test('OBJ negative indices and concave polygons import without a fan triangulation',()=>{const s='v 0 0 0\nv 3 0 0\nv 3 2 0\nv 1 2 0\nv 1 1 0\nv 0 1 0\nf -6 -5 -4 -3 -2 -1';const p=importOBJ([{name:'concave.obj',buffer:new TextEncoder().encode(s).buffer}],'concave.obj');assert.equal(numTriangles(p),4);});
test('Unknown file formats and malformed GLB fail explicitly',async()=>{await assert.rejects(()=>importFiles([{name:'bad.dwg',buffer:new ArrayBuffer(4)}]));await assert.rejects(()=>importGLTF([{name:'bad.glb',buffer:new ArrayBuffer(4)}],'bad.glb'));});
