import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {inflateRawSync,deflateRawSync} from 'node:zlib';
import vm from 'node:vm';
import * as G from '../src/geometry/mesh.js';
import * as M from '../src/core/math.js';
import {Document,newProject,makeNode,projectBounds} from '../src/core/document.js';
import {SceneProxy,visibleBox} from '../desktop/shared/scene-proxy.js';
import {toBase64,fromBase64,utf8Encode,utf8Decode,DataBlob,DataTextDecoder} from '../desktop/shared/encoding.js';
import {bundleDesktop} from '../tools/desktop-bundle.mjs';
import {unzip,setNativeInflater,crc32} from '../src/io/zip.js';
import {App} from '../src/app.js';
import {Tools} from '../src/ui/tools.js';

const scene=()=>{const p=newProject(),m=G.box();p.meshes[m.id]=m;p.nodes.push(makeNode('Box',m.id,{kind:'raw'}));const r=new SceneProxy();r.resize(1000,800);r.setProject(p);r.camera.fit(projectBounds(p));return {p,m,r};};
test('Native base64 preserves every byte and subarray boundaries',()=>{for(const n of [0,1,2,3,31,65539]){const bytes=Uint8Array.from({length:n},(_,i)=>i%256);const b64=toBase64(bytes);assert.equal(b64,Buffer.from(bytes).toString('base64'));assert.deepEqual(fromBase64(b64),bytes);}const a=new Uint8Array([1,2,3,4]);assert.equal(toBase64(a.subarray(1,3)),'AgM=');});
test('Native binary decoding bounds input and rejects malformed padding',()=>{for(const value of ['a','abc','====','AA=A','A===','AA\n=','@@=='])assert.throws(()=>fromBase64(value));assert.throws(()=>fromBase64('AAAA',2));const a=new Uint8Array(3*1024*1024);assert.equal(fromBase64(toBase64(a)).length,a.length);});
test('Native UTF-8, UTF-16 and Blob primitives retain model metadata',async()=>{const text='SingleTake · café 日本 🏠';assert.deepEqual(utf8Encode(text),new TextEncoder().encode(text));assert.equal(utf8Decode(utf8Encode(text)),text);assert.equal(new DataTextDecoder('utf-16le').decode(Buffer.from('{26.2.0}','utf16le')),'{26.2.0}');const blob=new DataBlob([text,new Uint8Array([33])]);assert.equal(await blob.text(),text+'!');assert.equal((await blob.arrayBuffer()).byteLength,blob.size);});
test('Native packets reuse shared meshes and send no geometry on camera-only changes',()=>{const {p,m,r}=scene();p.nodes.push(makeNode('Second',m.id,{matrix:M.translation([3,0,0]),component:'shared'}));r.setProject(p);r.camera.fit(projectBounds(p));const first=r.packet();assert.equal(first.resources.length,1);assert.equal(first.nodes.length,2);r.acknowledge(first);r.camera.orbit(2,2);const next=r.packet();assert.equal(next.resources.length,0);assert.equal(next.resourceIds.length,1);assert.equal(next.nodes[0].mesh,next.nodes[1].mesh);assert.notDeepEqual(next.viewProjection,first.viewProjection);});
test('Undo reuses immutable resource identities rather than revision-number collisions',()=>{const {p,m,r}=scene();const doc=new Document();doc.replace(p);const first=r.packet();r.acknowledge(first);doc.transaction('Edit',q=>{q.meshes[m.id]=G.cloneMesh(q.meshes[m.id]);q.meshes[m.id].vertices[0][0]+=.1;});r.setProject(doc.project);const edited=r.packet();assert.notEqual(edited.resourceIds[0],first.resourceIds[0]);r.acknowledge(edited);doc.undo();r.setProject(doc.project);const undone=r.packet();assert.equal(undone.resourceIds[0],first.resourceIds[0]);assert.equal(undone.resources.length,1);});
test('A native context reset requests all resident assets again',()=>{const {r}=scene();let p=r.packet();r.acknowledge(p);assert.equal(r.packet().resources.length,0);r.resetResources();assert.equal(r.packet().resources.length,1);});
test('Native scene proxy uses the same BVH face picking as the web modeler',()=>{const {r}=scene();const point=[1,2,1],screen=r.camera.project(point),hit=r.raycast(screen[0],screen[1]);assert(hit);assert.equal(hit.mesh.faces.length,6);assert(M.dist(hit.point,point)<1e-4);});
test('Frustum culling rejects separated bounds and preserves intersecting bounds',()=>{assert(visibleBox({min:[-.1,-.1,.1],max:[.1,.1,.9]},M.identity()));assert(!visibleBox({min:[5,-.1,.1],max:[6,.1,.9]},M.identity()));assert(visibleBox({min:[-5,-5,-5],max:[5,5,5]},M.identity()));});
test('Native camera-relative placement preserves logical axes and section distances',()=>{const {p,r}=scene();p.nodes[0].matrix=M.translation([10000,0,10000]);p.section={enabled:true,axis:'y',value:1.1,flip:false};r.setProject(p);r.camera.fit(projectBounds(p));const frame=r.packet();assert(frame.axes&&frame.grid);assert.equal(frame.section[1],1);assert.equal(frame.section[3],frame.origin[1]-1.1);assert(Math.abs(frame.nodes[0].matrix[12])<1000);});
test('Native texture deltas retain object identity and do not re-transfer images while orbiting',()=>{const {p,r}=scene();p.materials[0].texture={bytes:new Uint8Array([1,2,3]),flipY:true};r.setProject(p);const a=r.packet();assert.equal(a.images.length,1);assert.equal(a.materials[0].flipY,true);r.acknowledge(a);assert.equal(r.packet().images.length,0);});
test('Desktop static bundle is deterministic and excludes the browser renderer',async()=>{const a=await bundleDesktop(),b=await bundleDesktop();assert.equal(a.text,b.text);assert(a.report.modules.includes('src/ui/tools.js'));assert(a.report.modules.includes('src/importers/skp.js'));assert(!a.report.modules.includes('src/render/renderer.js'));assert(a.report.modules.includes('src/app.js'));const sandbox={EventTarget,Event,CustomEvent,console,TextEncoder,TextDecoder};vm.runInNewContext(a.text,sandbox,{timeout:1000});assert.equal(typeof sandbox.mount,'function');assert.equal(typeof sandbox.unmount,'function');});
function compressedZip(bytes){const compressed=deflateRawSync(bytes),filename=Buffer.from('data.bin');const local=Buffer.alloc(30),central=Buffer.alloc(46),end=Buffer.alloc(22),crc=crc32(bytes);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(8,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(bytes.length,22);local.writeUInt16LE(filename.length,26);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(8,10);central.writeUInt32LE(crc,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(bytes.length,24);central.writeUInt16LE(filename.length,28);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(1,8);end.writeUInt16LE(1,10);end.writeUInt32LE(central.length+filename.length,12);end.writeUInt32LE(local.length+filename.length+compressed.length,16);return new Uint8Array(Buffer.concat([local,filename,compressed,central,filename,end]));}
test('Native raw DEFLATE supplies ZIP entries with unchanged size and CRC validation',async()=>{const bytes=Buffer.from('native geometry '.repeat(1024));let calls=0;setNativeInflater(async(data,expected)=>{calls++;const out=new Uint8Array(inflateRawSync(data));assert.equal(out.length,expected);return out;});try{const files=await unzip(compressedZip(bytes));assert.deepEqual(Buffer.from(files.get('data.bin')),bytes);assert.equal(calls,1);}finally{setNativeInflater(null);}});
test('Native decompressor failures do not bypass ZIP validation',async()=>{const zip=compressedZip(Buffer.from('model'));try{setNativeInflater(async()=>new Uint8Array(1));await assert.rejects(unzip(zip),/size/);setNativeInflater(async()=>new Uint8Array(5));await assert.rejects(unzip(zip),/checksum/);}finally{setNativeInflater(null);}});
function appHarness(){const app=Object.create(App.prototype);Object.assign(app,{doc:new Document(),selection:new Set(),subSelection:new Map(),editContext:null,expanded:new Set(),face:null,vertex:null,activeMaterial:0,ready:true,measurement:{value:'',placeholder:''},canvas:{style:{},addEventListener(){},focus(){},getBoundingClientRect:()=>({left:0,top:0})},invoke:async()=>({}),guard:fn=>fn(),toast(){},renderOutliner(){},renderEntity(){},renderMaterials(){},renderTags(){},renderAll(){},renderContext(){},refreshTools(){}});app.renderer=new SceneProxy();app.renderer.resize(1000,800);app.renderer.setProject(app.doc.project);app.tools=new Tools(app);app.tools.overlay=()=>{};app.doc.addEventListener('change',()=>app.renderer.setProject(app.doc.project));app.selectionChanged=()=>{app.renderer.selected=app.highlightedSelection();};return app;}
test('Shared application controller creates, groups, duplicates and undoes using shared editing logic',async()=>{const a=appHarness();a.addGeometry(G.box());const n=a.doc.project.nodes[0];a.select(n.id);await a.action('group');assert.equal(a.doc.project.nodes.filter(n=>n.kind==='group').length,1);await a.action('duplicate');assert.equal(a.doc.project.nodes.filter(n=>n.kind==='group').length,2);await a.action('undo');assert.equal(a.doc.project.nodes.filter(n=>n.kind==='group').length,1);});
test('Desktop numeric tools retain rectangle and face extrusion semantics',()=>{const a=appHarness();a.tools.id='rectangle';a.tools.pending={kind:'rectangle',a:[0,0,0],plane:{point:[0,0,0],...M.planeBasis([0,1,0])}};a.tools.enter('4m, 3m');const m=Object.values(a.doc.project.meshes)[0];assert.equal(m.faces.length,1);assert(Math.abs(G.topology(m).area-12)<1e-6);const next=G.extrudeFace(m,m.faces[0].id,2.7);assert(Math.abs(G.topology(next).volume-32.4)<1e-6);});
test('Native project references NuGet dependencies, never an upstream source checkout or browser control',async()=>{const project=await readFile(new URL('../desktop/SingleTake.Desktop/SingleTake.Desktop.csproj',import.meta.url),'utf8');assert(project.includes('PackageReference Include="WebScene.Sdk.Avalonia"'));assert(project.includes('Silk.NET.OpenGL'));assert(!project.includes('WebView')&&!project.includes('CefSharp')&&!project.includes('Electron'));assert.equal((project.match(/WebScene.NativeEngine.Runtime./g)||[]).length,3);assert(!project.includes('ProjectReference Include="../WebScene'));});
test('Private fixture traverses the native inflater and indexed scene-packet path',{skip:!process.env.SINGLETAKE_MODEL_FIXTURE},async()=>{const {importSkp}=await import('../src/importers/skp.js');const bytes=await readFile(process.env.SINGLETAKE_MODEL_FIXTURE);let inflated=0;setNativeInflater(async(data)=>{inflated++;return new Uint8Array(inflateRawSync(data));});try{const p=await importSkp(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length),'private fixture');assert.equal(p.source.report.invalidFaces,0);assert.equal(p.source.report.unresolvedInstances,0);const r=new SceneProxy();r.resize(1280,800);r.setProject(p);r.camera.fit(projectBounds(p));const frame=r.packet();assert(frame.nodes.length>100);assert(frame.resources.length>50);assert(frame.images.length>0);assert(inflated>0);for(const n of frame.nodes)assert(n.matrix.every(Number.isFinite));r.acknowledge(frame);assert.equal(r.packet().resources.length,0);}finally{setNativeInflater(null);}});
