import * as M from '../core/math.js';
import * as G from '../geometry/mesh.js';
import {projectBounds,sceneEntries,descendants} from '../core/document.js';
import {TOOLS} from './icons.js';
const drawTools=new Set(['line','rectangle','circle','arc']);
const axisVector={x:[1,0,0],y:[0,1,0],z:[0,0,1]};
const NS='http://www.w3.org/2000/svg';
const svg=(tag,attrs)=>{const el=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);return el;};
export class Tools {
 constructor(app){this.app=app;this.id='select';this.pending=null;this.axis=null;this.snapEnabled=true;this.snapStep=.1;this.cursor={x:0,y:0};this.hover=null;this.gesture=null;this.snapInfo=null;this.lastPreview=null;const c=app.canvas;
  c.addEventListener('pointerdown',e=>this.down(e));c.addEventListener('pointermove',e=>this.move(e));c.addEventListener('pointerup',e=>this.up(e));c.addEventListener('pointercancel',()=>{this.gesture=null;});c.addEventListener('wheel',e=>{e.preventDefault();app.renderer.camera.zoom(e.deltaY);this.changedCamera();},{passive:false});c.addEventListener('contextmenu',e=>e.preventDefault());
  c.addEventListener('dblclick',e=>{if(this.id==='select'){const p=this.position(e),h=app.renderer.raycast(p.x,p.y);if(h)app.select(h.node.id,false,h);}else if(this.id==='line')this.finishLine(false);});
 }
 set(id){if(id==='section'){this.app.action('section');return;}this.app.renderer.previewTransform=null;this.app.renderer.requestRender();this.id=id;this.pending=null;this.axis=null;this.snapInfo=null;this.lastPreview=null;this.app.canvas.style.cursor=['select','move','scale','rotate','vertex','edge'].includes(id)?'default':['orbit','pan'].includes(id)?'grab':'crosshair';this.app.refreshTools();this.overlay();}
 cancel(){this.app.renderer.previewTransform=null;this.app.renderer.requestRender();this.pending=null;this.axis=null;this.lastPreview=null;this.app.measurement.value='';this.overlay();}
 position(e){const r=this.app.canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 changedCamera(){this.app.renderer.requestRender();this.overlay();}
 down(e){if(!this.app.ready)return;this.app.canvas.focus();this.app.hideContext();this.cursor=this.position(e);const camera=e.button===1||e.button===2||this.id==='orbit'||this.id==='pan'||(e.altKey&&!drawTools.has(this.id)&&this.id!=='paint');this.gesture={start:{...this.cursor},last:{...this.cursor},button:e.button,camera,pan:e.shiftKey||e.button===2||this.id==='pan',shift:e.shiftKey,alt:e.altKey,moved:false};this.app.canvas.setPointerCapture(e.pointerId);}
 move(e){if(!this.app.ready)return;this.cursor=this.position(e);const g=this.gesture;if(g){const dx=this.cursor.x-g.last.x,dy=this.cursor.y-g.last.y;g.moved||=Math.hypot(this.cursor.x-g.start.x,this.cursor.y-g.start.y)>4;if(g.camera&&g.moved){g.pan?this.app.renderer.camera.pan(dx,dy):this.app.renderer.camera.orbit(dx,dy);g.last={...this.cursor};this.changedCamera();return;}if(this.id==='select'&&g.moved){this.overlay();return;}}
  this.hover=this.app.renderer.raycast(this.cursor.x,this.cursor.y);this.snapInfo=this.resolvePoint(this.cursor,e);this.updatePending();this.overlay();
 }
 async up(e){if(!this.gesture)return;const g=this.gesture;this.gesture=null;try{this.app.canvas.releasePointerCapture(e.pointerId);}catch{}this.cursor=this.position(e);if(g.camera){if(g.button===2&&!g.moved)this.app.context(e.clientX,e.clientY);return;}if(this.id==='select'&&g.moved){this.marquee(g.start,this.cursor,e.shiftKey);this.overlay();return;}if(g.moved&&this.id==='select')return;
  try{await this.click(e);}catch(err){this.app.toast(err.message,'error');}this.overlay();
 }
 plane(e={}){if(this.pending?.plane)return this.pending.plane;if(e.altKey&&drawTools.has(this.id)){const hit=this.app.renderer.raycast(this.cursor.x,this.cursor.y);if(hit)return {point:hit.point,...M.planeBasis(hit.normal)};}return {point:[0,0,0],u:[1,0,0],v:[0,0,-1],normal:[0,1,0]};}
 resolvePoint(pos,e={}){
  const ray=this.app.renderer.camera.ray(pos.x,pos.y),plane=this.plane(e);let point=M.rayPlane(ray,plane.point,plane.normal),label='On plane';const hit=this.app.renderer.raycast(pos.x,pos.y);
  if(['measure','move','vertex','edge'].includes(this.id)&&!this.pending?.plane&&hit){point=hit.point;label='On face';}
  const start=this.pending?.anchor||this.pending?.points?.at(-1)||this.pending?.a;
  if(this.axis&&start){const v=axisVector[this.axis],w=M.sub(ray.origin,start),d=ray.direction,a=M.dot(d,d),b=M.dot(d,v),den=a-b*b;if(Math.abs(den)>1e-8)point=M.add(start,M.mul(v,(a*M.dot(v,w)-b*M.dot(d,w))/den));label=this.axis.toUpperCase()+' axis';}
  if(!point)return null;if(!this.snapEnabled)return {point,label};
  let best=null;const candidates=[];const near=hit? [hit.entry]:this.app.renderer.entries.filter(x=>this.app.selection.has(x.node.id)&&x.node.mesh).slice(0,5);
  for(const entry of near){const mesh=this.app.doc.project.meshes[entry.node.mesh];if(!mesh)continue;const face=hit?.node.id===entry.node.id?mesh.faces[hit.face]:null,ids=face?new Set(face.loops.flat()):new Set(mesh.vertices.map((_,i)=>i).slice(0,3000));for(const id of ids)candidates.push({point:M.transform(entry.matrix,mesh.vertices[id]),label:'Endpoint'});if(face)for(const l of face.loops)for(let i=0;i<l.length;i++)candidates.push({point:M.transform(entry.matrix,M.mul(M.add(mesh.vertices[l[i]],mesh.vertices[l[(i+1)%l.length]]),.5)),label:'Midpoint'});}
  if(this.pending?.points?.length)candidates.push({point:this.pending.points[0],label:'Close loop'});
  for(const c of candidates){if(drawTools.has(this.id)&&Math.abs(M.dot(M.sub(c.point,plane.point),plane.normal))>1e-4)continue;if(this.axis&&start&&M.len(M.cross(M.sub(c.point,start),axisVector[this.axis]))>1e-4)continue;const screen=this.app.renderer.camera.project(c.point);if(!screen)continue;const distance=Math.hypot(screen[0]-pos.x,screen[1]-pos.y);if(distance<11&&(!best||distance<best.distance))best={...c,distance};}
  if(best)return best;
  if(!this.axis&&start){for(const [name,axis] of Object.entries(axisVector)){const candidate=M.add(start,M.mul(axis,M.dot(M.sub(point,start),axis))),screen=this.app.renderer.camera.project(candidate);if(screen&&Math.hypot(screen[0]-pos.x,screen[1]-pos.y)<7){point=candidate;label=name.toUpperCase()+' inference';break;}}}
  if(label==='On plane'&&this.snapStep>0){const delta=M.sub(point,plane.point),u=Math.round(M.dot(delta,plane.u)/this.snapStep)*this.snapStep,v=Math.round(M.dot(delta,plane.v)/this.snapStep)*this.snapStep;point=M.add(plane.point,M.add(M.mul(plane.u,u),M.mul(plane.v,v)));label='Grid · '+M.formatLength(this.snapStep,this.app.doc.project.units);}
  return {point,label};
 }
 updatePending(){const p=this.pending;if(!p)return;const scale=this.app.renderer.camera.distance/Math.max(1,this.app.renderer.camera.height);if(p.kind==='pushpull')p.value=(p.mouse.y-this.cursor.y)*scale;if(p.kind==='rotate')p.value=(this.cursor.x-p.mouse.x)*.5;if(p.kind==='scale')p.value=Math.max(.01,1+(this.cursor.x-p.mouse.x)*.008);this.lastPreview=this.previewPoints();if(['move','rotate','scale'].includes(p.kind)){let matrix=null;const center=p.center||=M.center(projectBounds(this.app.doc.project,descendants(this.app.doc.project,this.app.selection)));if(p.kind==='move'&&this.snapInfo)matrix=M.translation(M.sub(this.snapInfo.point,p.anchor));if(p.kind==='rotate')matrix=M.mmul(M.translation(center),M.mmul(M.rotation(axisVector[this.axis||'y'],p.value*Math.PI/180),M.translation(M.mul(center,-1))));if(p.kind==='scale')matrix=M.mmul(M.translation(center),M.mmul(M.scaling([p.value,p.value,p.value]),M.translation(M.mul(center,-1))));if(matrix){this.app.renderer.previewTransform={ids:descendants(this.app.doc.project,this.app.selection),matrix};this.app.renderer.requestRender();}}if(document.activeElement!==this.app.measurement){let value='';if(p.kind==='pushpull')value=M.formatLength(p.value||0,this.app.doc.project.units);if(p.kind==='rotate')value=(p.value||0).toFixed(1)+'°';if(p.kind==='scale')value=(p.value||1).toFixed(3);if(['circle','measure','line','move'].includes(p.kind)&&this.snapInfo){const a=p.a||p.anchor||p.points?.at(-1);if(a)value=M.formatLength(M.dist(a,this.snapInfo.point),this.app.doc.project.units);}this.app.measurement.placeholder=value||'Type a precise value';}}
 async click(e){const app=this.app,r=app.renderer,p=this.pending,pos=this.cursor,hit=r.raycast(pos.x,pos.y),info=this.resolvePoint(pos,e),point=info?.point;
  if(this.id==='select'){let id;try{id=await r.pick(pos.x,pos.y);}catch{}id=id||hit?.node.id||r.pickLine(pos.x,pos.y)?.node.id;if(id)app.select(id,e.shiftKey,null);else if(!e.shiftKey)app.select(null);return;}
  if(this.id==='vertex'||this.id==='edge'){if(hit){app.select(hit.node.id,false,hit);const source=hit.mesh,ids=source.faces[hit.face].loops.flat(),candidates=ids.map(i=>({i,p:r.camera.project(M.transform(hit.entry.matrix,source.vertices[i]))})).filter(v=>v.p).sort((a,b)=>Math.hypot(a.p[0]-pos.x,a.p[1]-pos.y)-Math.hypot(b.p[0]-pos.x,b.p[1]-pos.y));if(candidates.length){app.vertex=candidates[0].i;app.renderEntity();}}return;}
  if(this.id==='eraser'){if(hit&&!hit.entry.locked){app.select(hit.node.id,false,e.shiftKey?hit:null);e.shiftKey?app.deleteFace():app.deleteSelection();}return;}
  if(this.id==='paint'){if(!hit)return;if(e.altKey){app.activeMaterial=hit.mesh.faces[hit.face].material??hit.entry.material;app.renderMaterials();return;}app.select(hit.node.id,false,e.shiftKey?null:hit);app.paintSelection();return;}
  if(this.id==='pushpull'||this.id==='offset'){if(p){if(this.id==='pushpull')this.commitValue(p.value);else app.measurement.focus();return;}if(!hit)throw Error('Click a face first.');if(hit.entry.locked)throw Error('This object is locked.');app.select(hit.node.id,false,hit);this.pending={kind:this.id,hit,mouse:{...pos},value:0};if(this.id==='offset'){app.measurement.focus();app.measurement.placeholder='Inset distance, e.g. 100 mm';}return;}
  if(['move','rotate','scale'].includes(this.id)){if(p){if(this.id==='move'&&point)this.commitValue(M.sub(point,p.anchor));else this.commitValue(p.value);return;}if(!app.selection.size&&hit)app.select(hit.node.id);if(!app.selection.size)throw Error('Select an object first.');this.pending={kind:this.id,anchor:point||M.center(projectBounds(app.doc.project,descendants(app.doc.project,app.selection))),mouse:{...pos},value:this.id==='scale'?1:0};return;}
  if(!point)return;
  if(this.id==='measure'){if(p){app.addMeasurement(p.a,point);this.pending=null;}else this.pending={kind:'measure',a:point};return;}
  if(this.id==='rectangle'||this.id==='circle'){if(p){const m=this.id==='rectangle'?G.rectangle(p.a,point,p.plane):G.circle(p.a,M.dist(p.a,point),48,p.plane.normal);if(!m.faces.length||M.len(M.extent(M.bounds(m.vertices)))<1e-6)return;app.addGeometry(m);this.pending=null;}else this.pending={kind:this.id,a:point,plane:this.plane(e)};return;}
  if(this.id==='line'){if(!p){this.pending={kind:'line',points:[point],plane:this.plane(e)};return;}if(p.points.length>=3&&M.dist(point,p.points[0])<Math.max(1e-5,this.snapStep*.1)){this.finishLine(true);return;}if(M.dist(point,p.points.at(-1))>1e-6)p.points.push(point);return;}
  if(this.id==='arc'){if(!p)this.pending={kind:'arc',points:[point],plane:this.plane(e)};else{p.points.push(point);if(p.points.length===3){const points=this.arcPoints(p.points,p.plane),m=G.mesh(points,[],'Arc');m.edges=points.slice(1).map((_,i)=>({a:i,b:i+1}));app.addGeometry(m);this.pending=null;}}}
 }
 arcPoints(points,plane){const [a,b,c]=points.map(p=>[M.dot(M.sub(p,plane.point),plane.u),M.dot(M.sub(p,plane.point),plane.v)]),d=2*(a[0]*(b[1]-c[1])+b[0]*(c[1]-a[1])+c[0]*(a[1]-b[1]));if(Math.abs(d)<1e-8)throw Error('Arc points are collinear.');const sq=p=>p[0]*p[0]+p[1]*p[1],cx=(sq(a)*(b[1]-c[1])+sq(b)*(c[1]-a[1])+sq(c)*(a[1]-b[1]))/d,cy=(sq(a)*(c[0]-b[0])+sq(b)*(a[0]-c[0])+sq(c)*(b[0]-a[0]))/d,r=Math.hypot(a[0]-cx,a[1]-cy),start=Math.atan2(a[1]-cy,a[0]-cx),end=Math.atan2(b[1]-cy,b[0]-cx),through=Math.atan2(c[1]-cy,c[0]-cx),tau=2*Math.PI,positive=x=>(x%tau+tau)%tau;let sweep=positive(end-start);if(positive(through-start)>sweep)sweep-=tau;return Array.from({length:49},(_,i)=>{const angle=start+sweep*i/48;return M.add(plane.point,M.add(M.mul(plane.u,cx+Math.cos(angle)*r),M.mul(plane.v,cy+Math.sin(angle)*r)));});}
 finishLine(close=false){const p=this.pending;if(!p||p.kind!=='line')return;if(p.points.length<2){this.cancel();return;}let m;if(close){m=G.polygon(p.points,p.plane.normal);}else{m=G.mesh(p.points,[],'Polyline');m.edges=p.points.slice(1).map((_,i)=>({a:i,b:i+1}));}this.app.addGeometry(m);this.pending=null;this.overlay();}
 enter(text){const p=this.pending;if(!text.trim()){if(this.id==='line')this.finishLine(false);else if(p&&['pushpull','rotate','scale'].includes(p.kind))this.commitValue(p.value);return;}const unit=this.app.doc.project.units,parse=x=>M.parseLength(x,unit);let value;
  if(['rotate','scale'].includes(p?.kind)){const xs=text.split(',').map(x=>Number(x.replace(/°|deg/g,'')));if(xs.some(x=>!Number.isFinite(x)))throw Error('Enter numeric values.');value=xs.length===1?xs[0]:xs;}
  else value=text.split(',').map(parse);if(Array.isArray(value)&&value.some(x=>!Number.isFinite(x)))throw Error('Enter valid measurements.');
  if(!p){if(this.id==='pushpull'&&this.app.face){this.pending={kind:'pushpull',hit:this.app.face};return this.commitValue(Array.isArray(value)?value[0]:value);}throw Error('Begin a tool operation in the canvas first.');}
  if(p.kind==='rectangle'){if(value.length!==2)throw Error('Rectangle: enter width, depth.');const b=M.add(p.a,M.add(M.mul(p.plane.u,value[0]),M.mul(p.plane.v,value[1])));this.app.addGeometry(G.rectangle(p.a,b,p.plane));this.cancel();return;}
  if(p.kind==='circle'){this.app.addGeometry(G.circle(p.a,Math.abs(value[0]),48,p.plane.normal));this.cancel();return;}
  if(p.kind==='line'){const direction=this.axis?axisVector[this.axis]:this.snapInfo?M.norm(M.sub(this.snapInfo.point,p.points.at(-1))):[1,0,0];if(M.len(direction)<.5)throw Error('Point the cursor in a direction first.');p.points.push(M.add(p.points.at(-1),M.mul(direction,value[0])));this.app.measurement.value='';this.overlay();return;}
  if(p.kind==='move'){if(value.length===3)this.commitValue(value);else{const direction=this.axis?axisVector[this.axis]:M.norm(M.sub(this.snapInfo?.point||p.anchor,p.anchor));if(M.len(direction)<.5)throw Error('Lock X, Y, or Z, or indicate a movement direction.');this.commitValue(M.mul(direction,value[0]));}return;}
  this.commitValue(Array.isArray(value)&&value.length===1?value[0]:value);
 }
 commitValue(value){const p=this.pending;if(!p)return;const app=this.app;
  if(p.kind==='pushpull'){const normal=p.hit.mesh.faces[p.hit.face].normal||M.faceNormal(p.hit.mesh.faces[p.hit.face].loops[0].map(i=>p.hit.mesh.vertices[i])),worldScale=M.len(M.transform(p.hit.entry.matrix,normal,0));app.editMesh('Push / Pull',p.hit,m=>G.extrudeFace(m,p.hit.faceId,value/worldScale));}
  if(p.kind==='offset')app.editMesh('Offset face',p.hit,m=>G.offsetFace(m,p.hit.faceId,value));
  if(p.kind==='move')app.transformSelection(M.translation(value),'Move');
  if(p.kind==='rotate'){const c=M.center(projectBounds(app.doc.project,descendants(app.doc.project,app.selection))),r=M.rotation(axisVector[this.axis||'y'],value*Math.PI/180);app.transformSelection(M.mmul(M.translation(c),M.mmul(r,M.translation(M.mul(c,-1)))),'Rotate');}
  if(p.kind==='scale'){const factors=Array.isArray(value)?value:[value,value,value];if(factors.length!==3||factors.some(x=>!Number.isFinite(x)||Math.abs(x)<.00001))throw Error('All scale factors must be nonzero.');const c=M.center(projectBounds(app.doc.project,descendants(app.doc.project,app.selection)));app.transformSelection(M.mmul(M.translation(c),M.mmul(M.scaling(factors),M.translation(M.mul(c,-1)))),'Scale');}
  this.cancel();app.canvas.focus();
 }
 marquee(a,b,add){const min=[Math.min(a.x,b.x),Math.min(a.y,b.y)],max=[Math.max(a.x,b.x),Math.max(a.y,b.y)],ids=[];for(const e of this.app.renderer.entries){if(!e.visible||!e.node.mesh)continue;const m=this.app.doc.project.meshes[e.node.mesh];const center=this.app.renderer.camera.project(M.transform(e.matrix,M.center(M.bounds(m.vertices))));if(center&&center[0]>=min[0]&&center[0]<=max[0]&&center[1]>=min[1]&&center[1]<=max[1])ids.push(e.node.id);}this.app.selectMany(ids,add);}
 previewPoints(){const p=this.pending,q=this.snapInfo?.point;if(!p)return null;if(p.kind==='rectangle'&&q)return G.rectangle(p.a,q,p.plane).vertices;if(p.kind==='circle'&&q){const radius=M.dist(p.a,q);return radius>1e-6?G.circle(p.a,radius,48,p.plane.normal).vertices:null;}if(p.kind==='line')return q?[...p.points,q]:p.points;if(p.kind==='arc'){if(p.points.length===2&&q){try{return this.arcPoints([...p.points,q],p.plane);}catch{}}return q?[...p.points,q]:p.points;}if(p.kind==='measure'&&q)return [p.a,q];if(p.kind==='move'&&q)return [p.anchor,q];if(p.kind==='pushpull'){const hit=p.hit,points=hit.mesh.faces[hit.face].loops[0].map(i=>M.transform(hit.entry.matrix,hit.mesh.vertices[i]));return points.map(v=>M.add(v,M.mul(hit.normal,p.value||0)));}return null;}
 overlay(){const app=this.app;if(!app.ready)return;const camera=app.renderer.camera,project=app.doc.project,preview=document.querySelector('#preview-layer'),selection=document.querySelector('#selection-layer'),snap=document.querySelector('#snap-layer'),dims=document.querySelector('#dimension-layer');for(const el of [preview,selection,snap,dims])el.replaceChildren();
  const line=(layer,pts,close=false,attrs={})=>{const projected=pts.map(p=>camera.project(p));if(projected.some(p=>!p))return;layer.append(svg(close?'polygon':'polyline',{points:projected.map(p=>p.slice(0,2).join(',')).join(' '),fill:close?'rgba(38,148,103,.10)':'none',stroke:'#278362','stroke-width':1.5,...attrs}));};
  const measured=(a,b,label)=>{const pa=camera.project(a),pb=camera.project(b);if(!pa||!pb)return;line(dims,[a,b],false,{stroke:'#475b51','stroke-dasharray':'4 3'});for(const p of [pa,pb])dims.append(svg('circle',{cx:p[0],cy:p[1],r:3,fill:'#f7f8f4',stroke:'#475b51'}));const x=(pa[0]+pb[0])/2,y=(pa[1]+pb[1])/2-9;const txt=label||M.formatLength(M.dist(a,b),project.units);dims.append(svg('rect',{x:x-txt.length*3.4-6,y:y-12,width:txt.length*6.8+12,height:19,rx:4,fill:'#f7f8f4',stroke:'#d8ded4'}));const t=svg('text',{x,y,'text-anchor':'middle',fill:'#344638','font-size':11,'font-family':'system-ui'});t.textContent=txt;dims.append(t);};
  for(const m of project.measurements)measured(m.a,m.b,m.label);
  for(const e of app.renderer.entries){if(!app.selection.has(e.node.id)||!e.node.mesh)continue;const mesh=project.meshes[e.node.mesh];if(!mesh.vertices.length)continue;const c=M.corners(M.bounds(mesh.vertices)).map(p=>M.transform(e.matrix,p));for(const [a,b] of [[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]])line(selection,[c[a],c[b]],false,{stroke:'#2c8b66','stroke-width':1,'stroke-dasharray':'3 3',opacity:.7});}
  if(app.face){const entry=app.renderer.entries.find(e=>e.node.id===app.face.node.id),mesh=project.meshes[app.face.mesh.id],f=mesh?.faces.find(f=>f.id===app.face.faceId);if(entry&&f)for(const l of f.loops)line(selection,l.map(i=>M.transform(entry.matrix,mesh.vertices[i])),true,{fill:'rgba(62,164,116,.22)',stroke:'#188e59','stroke-width':2});if(entry&&app.vertex!=null&&mesh.vertices[app.vertex]){const p=camera.project(M.transform(entry.matrix,mesh.vertices[app.vertex]));if(p)selection.append(svg('rect',{x:p[0]-4,y:p[1]-4,width:8,height:8,fill:'#fff',stroke:'#128858','stroke-width':2}));}}
  const points=this.previewPoints();if(points?.length)line(preview,points,['rectangle','circle','pushpull'].includes(this.pending.kind),{'stroke-dasharray':'5 3'});
  if(this.pending?.kind==='measure'&&this.snapInfo)measured(this.pending.a,this.snapInfo.point);
  if(this.gesture?.moved&&!this.gesture.camera&&this.id==='select'){const a=this.gesture.start,b=this.cursor;preview.append(svg('rect',{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y),fill:'rgba(67,148,106,.08)',stroke:'#438d67','stroke-dasharray':'4 3'}));}
  if(this.snapInfo&&this.id!=='select'&&this.id!=='orbit'&&this.id!=='pan'){const p=camera.project(this.snapInfo.point);if(p){snap.append(svg('rect',{x:p[0]-3,y:p[1]-3,width:6,height:6,fill:'#ecfff3',stroke:'#20885d','stroke-width':1.5}));const t=svg('text',{x:p[0]+12,y:p[1]-9,fill:'#456250','font-size':11,'font-family':'system-ui'});t.textContent=this.snapInfo.label;snap.append(t);}}
 }
}
