import * as M from '../core/math.js';
import * as G from '../geometry/mesh.js';
import {projectBounds,descendants,sceneEntries} from '../core/document.js';
import {AXES,AXIS_COLORS,ARROW_AXES,toWorld} from '../core/coordinates.js';
import {selectionMode,applySelection,contextRoot,isRaw,rectangularRegion,polygonSelected,clockwise,pointInPolygon} from '../core/selection.js';
import {adjacency,edgeKey,transformedSelection,eraseEdge} from '../geometry/topology.js';
import {InferenceIndex,inferAxis,normalDrag,facingNormal,rayLineParameter,projectWith,nearestOnProjectedEdge} from './inference.js';
import {tagVisible} from '../core/tags.js';
const drawing=new Set(['line','rectangle','circle','arc']),planar=new Set(['rectangle','circle','arc']),constrained=new Set([...drawing,'move','rotate','measure','dimension','scale']);
const NS='http://www.w3.org/2000/svg',svg=(tag,attrs)=>{const e=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);return e;};
const around=(point,matrix)=>M.mmul(M.translation(point),M.mmul(matrix,M.translation(M.mul(point,-1))));
export class Tools {
 constructor(app){this.app=app;this.id='select';this.pending=null;this.axis=null;this.lockedDirection=null;this.lockedPlane=null;this.parallelDirection=null;this.snapEnabled=true;this.snapStep=0;this.cursor={x:0,y:0};this.hover=null;this.gesture=null;this.snapInfo=null;this.modifiers={shift:false,ctrl:false,alt:false};this.copyMode=false;this.centerMode=false;this.guideMode=true;this.circleSegments=24;this.arcSegments=12;this.lastOperation=null;this.lastExtrusion=null;this.lastOffset=null;this.inference=new InferenceIndex(app.renderer);this.cameraHistory=[];this.cameraFuture=[];
  const c=app.canvas,listen=(target,...args)=>app.listen?app.listen(target,...args):target.addEventListener(...args);listen(c,'pointerdown',e=>this.down(e));listen(c,'pointermove',e=>this.move(e));listen(c,'pointerup',e=>this.up(e));listen(c,'pointercancel',()=>this.releaseModifiers());listen(c,'contextmenu',e=>e.preventDefault());listen(c,'wheel',e=>{if(!app.ready)return;e.preventDefault();const p=this.position(e),hit=app.renderer.raycast(p.x,p.y),delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?app.renderer.camera.height:1);app.renderer.camera.zoomAt(delta,p.x,p.y,hit?.point);this.changedCamera();},{passive:false});
 }
 set(id){if(id==='section'){this.app.action('section');return;}this.cancel();this.id=id;this.lastOperation=null;this.copyMode=false;this.centerMode=false;this.app.canvas.style.cursor=['select','lasso','move','rotate','scale','vertex','edge'].includes(id)?'default':['orbit','pan'].includes(id)?'grab':id==='zoom'?'zoom-in':'crosshair';this.app.refreshTools();this.overlay();}
 cancel(){this.pending=null;this.axis=null;this.lockedDirection=null;this.lockedPlane=null;this.parallelDirection=null;this.snapInfo=null;this.gesture=null;this.app.renderer.previewTransform=null;this.app.renderer.clearGeometryPreview?.();this.app.renderer.requestRender();this.app.measurement.value='';this.overlay();}
 position(e){const r=this.app.canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 recordCamera(){const state=this.app.renderer.camera.save();if(JSON.stringify(state)!==JSON.stringify(this.cameraHistory.at(-1))){this.cameraHistory.push(state);if(this.cameraHistory.length>50)this.cameraHistory.shift();this.cameraFuture=[];}}
 previousCamera(forward=false){const source=forward?this.cameraFuture:this.cameraHistory,target=forward?this.cameraHistory:this.cameraFuture,state=source.pop();if(!state)return;target.push(this.app.renderer.camera.save());this.app.renderer.camera.restore(state);this.changedCamera();}
 changedCamera(){this.app.hidePhotoReference?.();this.inference.invalidate();this.app.renderer.requestRender();if(this.pending?.kind==='pushpull'){this.pending.mouse={...this.cursor};this.pending.baseValue=this.pending.value||0;}this.overlay();}
 releaseModifiers(){this.modifiers={shift:false,ctrl:false,alt:false};this.lockedDirection=null;this.lockedPlane=null;this.gesture=null;this.overlay();}
 modifier(e,down){const key=e.key,prop={Shift:'shift',Control:'ctrl',Meta:'ctrl',Alt:'alt'}[key];if(prop)this.modifiers[prop]=down;if(!down){if(key==='Shift'||key==='Alt'&&this.id==='line'){this.lockedDirection=null;this.lockedPlane=null;}return false;}
  const axis=ARROW_AXES[key];if((axis||key==='ArrowDown')&&constrained.has(this.id)){e.preventDefault?.();if(e.repeat)return true;if(axis){this.axis=this.axis===axis?null:axis;this.parallelDirection=null;}else{const dir=this.referenceDirection||this.inference.acquired?.direction||this.hover?.normal;this.parallelDirection=this.parallelDirection?null:dir?.slice()||null;this.axis=null;}if((planar.has(this.id)||this.id==='rotate')&&this.pending){const normal=this.axis?AXES[this.axis]:this.parallelDirection||this.pending.plane?.normal||[0,1,0];this.pending.plane={point:this.pending.a||this.pending.center||this.pending.points?.[0]||[0,0,0],...M.planeBasis(normal)};if(this.id==='rotate')this.pending.normal=normal;}this.refreshInference();return true;}
  if(key==='Shift'||key==='Alt'&&this.id==='line'){if(!e.repeat&&constrained.has(this.id)&&!this.gesture?.camera){if(planar.has(this.id)||this.id==='rotate')this.lockedPlane=this.plane();else{const a=this.anchor(),dir=this.axis?AXES[this.axis]:this.snapInfo?.direction||(a&&this.snapInfo?M.sub(this.snapInfo.point,a):null);if(dir&&M.len(dir)>1e-6)this.lockedDirection=M.norm(dir);}}if(key==='Alt')e.preventDefault?.();return false;}
  if((key==='Control'||key==='Meta')&&!e.repeat){if(['move','rotate','pushpull'].includes(this.id)){this.copyMode=!this.copyMode;this.refreshInference();return true;}if(this.id==='measure'){this.guideMode=!this.guideMode;this.app.measurement.placeholder=this.guideMode?'Guide mode':'Measure only';return true;}if(this.id==='rectangle'){this.centerMode=!this.centerMode;this.refreshInference();return true;}}
  if(key==='Alt'&&!e.repeat&&this.id==='rectangle'){e.preventDefault?.();this.centerMode=!this.centerMode;this.refreshInference();return true;}if(key==='Alt'&&['orbit','eraser','offset'].includes(this.id)){e.preventDefault?.();return true;}return false;
 }
 refreshInference(){if(!this.app.ready)return;this.snapInfo=this.resolvePoint(this.cursor);this.updatePending();this.overlay();}
 down(e){if(!this.app.ready)return;e.preventDefault();this.app.canvas.focus();this.app.hideContext();this.cursor=this.position(e);if(this.gesture?.camera){this.gesture.buttons=e.buttons;return;}const camera=e.button===1||e.button===0&&['orbit','pan','zoom'].includes(this.id);this.gesture={start:{...this.cursor},last:{...this.cursor},button:e.button,buttons:e.buttons,camera,nav:e.button===0&&this.id==='zoom'?'zoom':e.button===0&&this.id==='pan'?'pan':'orbit',moved:false,points:[[this.cursor.x,this.cursor.y]],erasures:[]};if(camera)this.recordCamera();this.app.canvas.setPointerCapture?.(e.pointerId);}
 move(e){if(!this.app.ready)return;this.cursor=this.position(e);this.modifiers={shift:e.shiftKey,ctrl:e.ctrlKey||e.metaKey,alt:e.altKey};const g=this.gesture;if(g){const dx=this.cursor.x-g.last.x,dy=this.cursor.y-g.last.y;g.moved||=Math.hypot(this.cursor.x-g.start.x,this.cursor.y-g.start.y)>4;if(g.camera&&g.moved){const c=this.app.renderer.camera;if(g.nav==='zoom'){e.shiftKey?c.changeFov(dy):c.zoomAt(dy*4,this.cursor.x,this.cursor.y);}else if(g.nav==='pan'||e.shiftKey||(e.buttons&4)&&(e.buttons&1))c.pan(dx,dy);else c.orbit(dx,dy,e.altKey||e.ctrlKey);g.last={...this.cursor};this.changedCamera();return;}if(g.button===0&&g.moved&&['select','lasso'].includes(this.id)){const last=g.points.at(-1);if(Math.hypot(this.cursor.x-last[0],this.cursor.y-last[1])>3)g.points.push([this.cursor.x,this.cursor.y]);this.overlay();return;}if(g.button===0&&this.id==='eraser'){const hit=this.pickEdge(this.cursor);if(hit&&!g.erasures.some(x=>x.node.id===hit.node.id&&x.edgeKey===hit.edgeKey))g.erasures.push(hit);}}
  this.hover=this.app.renderer.raycast(this.cursor.x,this.cursor.y);this.snapInfo=this.resolvePoint(this.cursor,e);this.updatePending();this.overlay();
 }
 async up(e){const g=this.gesture;if(!g)return;if(g.camera&&e.buttons){g.buttons=e.buttons;return;}this.gesture=null;try{this.app.canvas.releasePointerCapture?.(e.pointerId);}catch{}this.cursor=this.position(e);
  if(g.camera){if(!g.moved&&g.button===1){const now=performance.now();if(this.lastMiddle&&now-this.lastMiddle.time<400&&Math.hypot(this.cursor.x-this.lastMiddle.x,this.cursor.y-this.lastMiddle.y)<5){const r=this.app.renderer,hit=r.raycast(this.cursor.x,this.cursor.y),point=hit?.point||M.rayPlane(r.camera.ray(this.cursor.x,this.cursor.y),r.camera.target,r.camera.direction);if(point)r.camera.recenter(point);this.changedCamera();this.lastMiddle=null;}else this.lastMiddle={...this.cursor,time:now};}return;}
  if(g.button===2){if(!g.moved){const hit=this.pickHit(this.cursor);if(hit){const root=contextRoot(this.app.doc.project,hit.node.id,this.app.editContext);if(root&&!this.app.selection.has(root.id))this.app.selectHit(hit,{});}this.app.context(e.clientX,e.clientY);}return;}if(g.button!==0)return;
  try{if(['select','lasso'].includes(this.id)&&g.moved){this.marquee(g.start,this.cursor,e,this.id==='lasso'?g.points:null);this.overlay();return;}if(this.id==='eraser'&&g.erasures.length){this.eraseHits(g.erasures,e);return;}const now=performance.now(),previous=this.lastClick,repeat=previous&&now-previous.time<420&&Math.hypot(this.cursor.x-previous.x,this.cursor.y-previous.y)<5&&previous.tool===this.id,count=repeat?Math.min(3,previous.count+1):1;this.lastClick={...this.cursor,time:now,tool:this.id,count};await this.click(e,count);}catch(err){this.app.toast(err.message,'error');}this.overlay();
 }
 anchor(){const p=this.pending;if(p?.kind==='lasso')return null;return p?.anchor||p?.points?.at(-1)||p?.a||p?.center;}
 plane(){if(this.lockedPlane)return this.lockedPlane;if(this.pending?.plane)return this.pending.plane;const hit=this.hover||this.app.renderer.raycast(this.cursor.x,this.cursor.y),onPlane=planar.has(this.id)||this.id==='rotate',normal=this.axis&&onPlane?AXES[this.axis]:this.parallelDirection&&onPlane?this.parallelDirection:hit&&onPlane?hit.normal:[0,1,0],basis=Math.abs(normal[1])>.9999?{u:[1,0,0],v:[0,0,-Math.sign(normal[1])],normal}:M.planeBasis(normal);return {point:hit&&onPlane?hit.point:[0,0,0],...basis};}
 resolvePoint(pos){const r=this.app.renderer,ray=r.camera.ray(pos.x,pos.y),plane=this.plane(),anchor=this.anchor(),hit=r.raycast(pos.x,pos.y),onPlane=planar.has(this.id)||this.id==='rotate';let point=hit&&!onPlane?hit.point:M.rayPlane(ray,plane.point,plane.normal),label=hit&&!onPlane?'On face':'On plane';if(!point&&anchor)point=M.rayPlane(ray,anchor,r.camera.direction);const constraint=this.axis&&!onPlane?AXES[this.axis]:this.lockedDirection||(!onPlane?this.parallelDirection:null),candidate=this.snapEnabled?this.inference.query(this.app.doc.project,pos,{plane:onPlane&&this.pending?plane:null,exclude:this.pending?.kind==='move'?this.app.highlightedSelection():null}):null;if(candidate?.direction)this.referenceDirection=candidate.direction;if(candidate){point=candidate.point;label=candidate.label;}
  if(this.pending?.kind==='line'&&this.pending.points.length>=3){const first=this.pending.points[0],screen=r.camera.project(first);if(screen&&Math.hypot(screen[0]-pos.x,screen[1]-pos.y)<11){point=first;label='Close loop';}}
  if(constraint&&anchor){const direction=M.norm(constraint),t=candidate?M.dot(M.sub(candidate.point,anchor),direction):rayLineParameter(ray,anchor,direction);if(t!==null)return {point:M.add(anchor,M.mul(direction,t)),label:(candidate?'From '+candidate.label.toLowerCase()+' · ':'')+(this.axis?this.axis.toUpperCase()+' locked':'Inference locked'),direction,axis:this.axis,reference:candidate};}
  if(!point)return null;if(!candidate&&this.snapEnabled&&anchor&&!onPlane){const directions={...AXES};if(this.referenceDirection){directions.parallel=this.referenceDirection;const perpendicular=M.cross(plane.normal,this.referenceDirection);if(M.len(perpendicular)>.5)directions.perpendicular=M.norm(perpendicular);}const inferred=inferAxis(r.camera,pos,anchor,point,directions);if(inferred)return inferred;}
  if(!candidate&&this.snapEnabled&&this.snapStep>0&&label==='On plane'){const delta=M.sub(point,plane.point),u=Math.round(M.dot(delta,plane.u)/this.snapStep)*this.snapStep,v=Math.round(M.dot(delta,plane.v)/this.snapStep)*this.snapStep;point=M.add(plane.point,M.add(M.mul(plane.u,u),M.mul(plane.v,v)));label='Grid';}return {...candidate,point,label};
 }
 pickEdge(pos){const r=this.app.renderer,p=this.app.doc.project,candidate=this.inference.query(p,pos,{radius:10,edgesOnly:true});if(candidate?.entry){const entry=candidate.entry,mesh=p.meshes[entry.node.mesh],edge=adjacency(mesh).edges.get(candidate.edgeKey),faceId=[...edge.faces][0],index=mesh.faces.findIndex(f=>f.id===faceId),normal=index>=0?M.norm(M.transform(M.transpose(M.inverse(entry.matrix)),mesh.faces[index].normal||M.faceNormal(mesh.faces[index].loops[0].map(i=>mesh.vertices[i])),0)):[0,1,0];return {node:entry.node,entry,mesh,faceId,face:index,edgeKey:edge.key,point:candidate.point,normal,distance:M.dist(r.camera.eye,candidate.point)};}
  if(this.id==='eraser'){const hit=r.raycast(pos.x,pos.y);if(hit){const vp=r.camera.matrices([0,0,0]).vp;let best=null;for(const edge of adjacency(hit.mesh).edges.values()){if(!edge.faces.has(hit.faceId))continue;const a=M.transform(hit.entry.matrix,hit.mesh.vertices[edge.a]),b=M.transform(hit.entry.matrix,hit.mesh.vertices[edge.b]),pa=projectWith(vp,a,r.camera.width,r.camera.height),pb=projectWith(vp,b,r.camera.width,r.camera.height);if(!pa||!pb)continue;const near=nearestOnProjectedEdge(pos,a,b,pa,pb);if(near.distance<7&&(!best||near.distance<best.screenDistance))best={...hit,edgeKey:edge.key,point:near.point,screenDistance:near.distance};}return best;}}return null;
 }
 pickHit(pos){return this.pickEdge(pos)||this.app.renderer.raycast(pos.x,pos.y);}
 updatePending(){const p=this.pending;if(!p)return;const app=this.app,r=app.renderer,c=r.camera;
  if(p.kind==='pushpull'){p.direction||=facingNormal(p.hit,c);p.value=(p.baseValue||0)+normalDrag(c,p.hit.point,p.direction,p.mouse||this.cursor,this.cursor);if(this.snapEnabled&&this.snapInfo&&['Endpoint','Midpoint','Center','Face center','On edge'].includes(this.snapInfo.label))p.value=M.dot(M.sub(this.snapInfo.point,p.hit.point),p.direction);if(this.hover&&this.hover.faceId!==p.hit.faceId&&Math.abs(M.dot(this.hover.normal,p.direction))>.999)p.value=M.dot(M.sub(this.hover.point,p.hit.point),p.direction);if(Math.abs(p.value)>1e-8)try{const delta=M.transform(M.inverse(p.hit.entry.matrix),M.mul(p.direction,p.value),0);r.previewGeometry?.(p.hit.node.id,G.extrudeFace(p.hit.mesh,p.hit.faceId,delta,{keepBase:this.copyMode}));}catch{r.clearGeometryPreview?.();}}
  if(p.kind==='offset'){const points=p.hit.mesh.faces[p.hit.face].loops[0].map(i=>M.transform(p.hit.entry.matrix,p.hit.mesh.vertices[i])),plane={point:points[0],...M.planeBasis(p.hit.normal)},q=M.rayPlane(c.ray(this.cursor.x,this.cursor.y),plane.point,plane.normal);if(q){const uv=x=>[M.dot(M.sub(x,plane.point),plane.u),M.dot(M.sub(x,plane.point),plane.v)];let distance=Infinity;for(let i=0;i<points.length;i++){const a=points[i],d=M.sub(points[(i+1)%points.length],a),t=M.clamp(M.dot(M.sub(q,a),d)/M.dot(d,d),0,1);distance=Math.min(distance,M.dist(q,M.add(a,M.mul(d,t))));}p.value=distance*(pointInPolygon(uv(q),points.map(uv))?1:-1);}}
  if(p.kind==='rotate'&&p.reference&&this.snapInfo){const delta=M.sub(this.snapInfo.point,p.center),dir=M.norm(M.sub(delta,M.mul(p.normal,M.dot(delta,p.normal))));if(M.len(dir)>.5){let angle=Math.atan2(M.dot(p.normal,M.cross(p.reference,dir)),M.dot(p.reference,dir))*180/Math.PI,step=Math.round(angle/15)*15;if(Math.abs(angle-step)<2)angle=step;p.value=angle;}}
  if(p.kind==='scale')p.factors=this.scaleFactors(p);let matrix=null;if(p.kind==='move'&&this.snapInfo)matrix=M.translation(M.sub(this.snapInfo.point,p.anchor));if(p.kind==='rotate'&&p.reference)matrix=around(p.center,M.rotation(p.normal,(p.value||0)*Math.PI/180));if(p.kind==='scale'&&p.factors)matrix=this.scaleMatrix(p,p.factors);
  if(matrix){const roots=app.selectedRoots();if(roots.length===1&&app.subSelection.has(roots[0].id)){const e=r.entries.find(e=>e.node.id===roots[0].id);if(e)try{r.previewGeometry?.(e.node.id,transformedSelection(app.doc.project.meshes[e.node.mesh],app.subSelection.get(e.node.id),M.mmul(M.inverse(e.matrix),M.mmul(matrix,e.matrix)),{autoFold:this.modifiers.alt}));}catch{r.clearGeometryPreview?.();}}else{r.previewTransform={ids:descendants(app.doc.project,app.selection),matrix};r.requestRender();}}
  if(document.activeElement!==app.measurement){let value='';if(['pushpull','offset'].includes(p.kind))value=M.formatLength(p.value||0,app.doc.project.units);else if(p.kind==='rotate')value=(p.value||0).toFixed(1)+'°';else if(p.kind==='scale')value=(p.factors||[1,1,1]).map(v=>v.toFixed(3)).join(', ');else if(this.snapInfo&&this.anchor())value=M.formatLength(M.dist(this.anchor(),this.snapInfo.point),app.doc.project.units);app.measurement.placeholder=value||'Type a precise value';}
 }
 async click(e={},count=1){const app=this.app,r=app.renderer,p=this.pending,hit=r.raycast(this.cursor.x,this.cursor.y),info=this.resolvePoint(this.cursor),point=info?.point;this.snapInfo=info;
  if(this.id==='select'){app.selectHit(this.pickHit(this.cursor),e,count);return;}
  if(this.id==='lasso'){if(!p)this.pending={kind:'lasso',points:[[this.cursor.x,this.cursor.y]]};else if(count===2&&p.points.length>2){this.marquee(null,null,e,p.points);this.pending=null;}else p.points.push([this.cursor.x,this.cursor.y]);return;}
  if(this.id==='vertex'||this.id==='edge'){const target=this.id==='edge'?this.pickEdge(this.cursor):hit;if(!target)return;if(!app.hitInContext(target))throw Error('Open the container before editing its geometry.');app.selectHit(target,e);if(this.id==='vertex'&&hit){const candidates=hit.mesh.faces[hit.face].loops.flat().map(i=>({i,p:r.camera.project(M.transform(hit.entry.matrix,hit.mesh.vertices[i]))})).filter(x=>x.p).sort((a,b)=>Math.hypot(a.p[0]-this.cursor.x,a.p[1]-this.cursor.y)-Math.hypot(b.p[0]-this.cursor.x,b.p[1]-this.cursor.y));if(candidates.length){app.vertex=candidates[0].i;app.face=hit;app.renderEntity();}}return;}
  if(this.id==='eraser'){const edge=this.pickEdge(this.cursor);if(edge)this.eraseHits([edge],e);else if(hit){const root=contextRoot(app.doc.project,hit.node.id,app.editContext);if(root&&!isRaw(root)){app.select(root.id);app.deleteSelection();}}return;}
  if(this.id==='paint'){if(hit)this.paintAt(hit,e);return;}
  if(['pushpull','offset'].includes(this.id)){const last=this.id==='pushpull'?this.lastExtrusion:this.lastOffset;if(count===2&&hit&&last!=null){if(!app.hitInContext(hit))throw Error('Open the container to edit its faces.');this.pending={kind:this.id,hit,direction:facingNormal(hit,r.camera),mouse:{...this.cursor},value:last};this.commitValue(last);return;}if(p){this.commitValue(p.value);return;}if(!hit)throw Error('Click a face first.');if(!app.hitInContext(hit))throw Error('Double-click the group to edit its faces first.');if(hit.entry.locked)throw Error('This geometry is locked.');app.selectHit(hit,{});this.pending={kind:this.id,hit,direction:facingNormal(hit,r.camera),mouse:{...this.cursor},value:0};this.lastOperation=null;return;}
  if(this.id==='move'){if(p&&point){this.commitValue(M.sub(point,p.anchor));return;}if(!app.selection.size&&hit)app.selectHit(hit,{});app.editableRoots();if(point){this.pending={kind:'move',anchor:point,mouse:{...this.cursor}};this.lastOperation=null;}return;}
  if(this.id==='rotate'){if(!p){if(!app.selection.size&&hit)app.selectHit(hit,{});app.editableRoots();if(!point)return;const normal=this.axis?AXES[this.axis]:this.lockedPlane?.normal||hit?.normal||[0,1,0];this.pending={kind:'rotate',center:point,normal,plane:{point,...M.planeBasis(normal)},reference:null,value:0};this.lastOperation=null;return;}if(!p.reference&&point){const delta=M.sub(point,p.center);p.reference=M.norm(M.sub(delta,M.mul(p.normal,M.dot(delta,p.normal))));if(M.len(p.reference)<.5){p.reference=null;throw Error('Choose a reference away from the rotation center.');}return;}this.commitValue(p.value);return;}
  if(this.id==='scale'){if(p){this.commitValue(p.factors||[1,1,1]);return;}if(!app.selection.size&&hit){app.selectHit(hit,{});return;}const frame=this.scaleFrame(),grip=this.scaleGrips(frame).map(g=>({...g,screen:r.camera.project(g.world)})).filter(g=>g.screen).sort((a,b)=>Math.hypot(a.screen[0]-this.cursor.x,a.screen[1]-this.cursor.y)-Math.hypot(b.screen[0]-this.cursor.x,b.screen[1]-this.cursor.y))[0];if(!grip||Math.hypot(grip.screen[0]-this.cursor.x,grip.screen[1]-this.cursor.y)>15)throw Error('Click a scale grip on the selected geometry.');this.pending={kind:'scale',frame,grip,mouse:{...this.cursor},factors:[1,1,1]};this.lastOperation=null;return;}
  if(!point)return;
  if(this.id==='measure'||this.id==='dimension'){if(p){const length=M.dist(p.a,point);if(length<1e-8)return;this.lastMeasure={a:p.a,b:point,length};if(this.id==='dimension')app.addMeasurement(p.a,point);else if(this.guideMode)app.doc.transaction('Create guide',q=>{q.guides||=[];if(p.direction){const span=Math.max(r.camera.distance*3,1);q.guides.push({id:M.uid('guide'),a:M.sub(point,M.mul(p.direction,span)),b:M.add(point,M.mul(p.direction,span))});}else q.guides.push({id:M.uid('guide'),point:point.slice()});});app.toast(M.formatLength(length,app.doc.project.units));this.pending=null;app.measurement.placeholder=M.formatLength(length,app.doc.project.units)+' · type a target size to resize';}else{this.pending={kind:this.id,a:point,direction:info?.direction};this.lastMeasure=null;}return;}
  if(this.id==='rectangle'||this.id==='circle'){if(p){this.id==='rectangle'?this.createRectangle(p,point):this.createCircle(p,M.dist(p.a,point));this.pending=null;}else{this.pending={kind:this.id,a:point,plane:{...this.plane(),point}};this.lastOperation=null;}return;}
  if(this.id==='line'){if(!p){this.pending={kind:'line',points:[point],committed:0};this.lastOperation=null;return;}if(count===2&&p.points.length>1){this.finishLine(false);return;}if(p.points.length>=3&&M.dist(point,p.points[0])<1e-6){this.addLinePoint(point);this.finishLine(true);return;}this.addLinePoint(point);return;}
  if(this.id==='arc'){if(!p){this.pending={kind:'arc',points:[point],plane:{...this.plane(),point}};this.lastOperation=null;}else if(p.points.length===1)p.points.push(point);else{this.createArc(p,point);this.pending=null;}return;}
 }
 createRectangle(p,b){const a=this.centerMode?M.sub(p.a,M.sub(b,p.a)):p.a,mesh=G.rectangle(a,b,p.plane),normal=M.faceNormal(mesh.vertices);if(M.len(normal)<.5)throw Error('Rectangle dimensions must be nonzero.');if(M.dot(normal,p.plane.normal)<0)mesh.faces[0].loops=mesh.faces[0].loops.map(l=>l.slice().reverse());mesh.faces[0].normal=p.plane.normal;this.app.addGeometry(mesh);}
 createCircle(p,radius){this.app.addGeometry(G.circle(p.a,radius,this.circleSegments,p.plane.normal));}
 addLinePoint(point){const p=this.pending,last=p.points.at(-1);if(M.dist(last,point)<1e-7)return;const m=G.mesh([last.slice(),point.slice()],[],'Line');m.edges=[{a:0,b:1}];this.app.addGeometry(m);p.points.push(point.slice());p.committed=(p.committed||0)+1;this.app.measurement.value='';}
 finishLine(close=false){const p=this.pending;if(!p||p.kind!=='line')return;if(close){const points=p.points.slice();if(M.dist(points[0],points.at(-1))<1e-7)points.pop();this.app.addGeometry(G.polygon(points));}else if(!p.committed&&p.points.length>1){const m=G.mesh(p.points,[],'Polyline');m.edges=p.points.slice(1).map((_,i)=>({a:i,b:i+1}));this.app.addGeometry(m);}this.pending=null;this.overlay();}
 arcPoints(points,plane){const [a,b,through]=points,normal=plane.normal,chord=M.sub(b,a),mid=M.mul(M.add(a,b),.5),perp=M.norm(M.cross(normal,chord)),bulge=M.dot(M.sub(through,mid),perp),length=M.len(chord);if(length<1e-7||Math.abs(bulge)<1e-7)throw Error('Arc endpoints and bulge must be distinct.');const center=M.add(mid,M.mul(perp,(bulge*bulge-length*length/4)/(2*bulge))),radius=M.dist(center,a),u=M.norm(M.sub(a,center)),v=M.cross(normal,u),end=Math.atan2(M.dot(M.sub(b,center),v),M.dot(M.sub(b,center),u)),peak=M.add(mid,M.mul(perp,bulge)),angle=Math.atan2(M.dot(M.sub(peak,center),v),M.dot(M.sub(peak,center),u)),tau=2*Math.PI,positive=x=>(x%tau+tau)%tau;let sweep=positive(end);if(positive(angle)>sweep+1e-7)sweep-=tau;this.arcGeometry={center,radius,normal:normal.slice()};return Array.from({length:this.arcSegments+1},(_,i)=>M.add(center,M.add(M.mul(u,Math.cos(sweep*i/this.arcSegments)*radius),M.mul(v,Math.sin(sweep*i/this.arcSegments)*radius))));}
 createArc(p,through){const vertices=this.arcPoints([...p.points,through],p.plane),mesh=G.mesh(vertices,[],'Arc');mesh.edges=vertices.slice(1).map((_,i)=>({a:i,b:i+1}));mesh.curves=[{type:'arc',...this.arcGeometry,vertices:vertices.map((_,i)=>i)}];this.app.addGeometry(mesh);}
 scaleFrame(){const app=this.app,roots=app.selectedRoots();if(!roots.length)throw Error('Select geometry before scaling.');const entries=sceneEntries(app.doc.project),root=roots.length===1?entries.find(e=>e.node.id===roots[0].id):null,matrix=root?.matrix||M.identity(),inverse=M.inverse(matrix),ids=descendants(app.doc.project,new Set(roots.map(n=>n.id))),bounds=M.emptyBounds();for(const e of entries){if(!ids.has(e.node.id)||!e.node.mesh)continue;const m=app.doc.project.meshes[e.node.mesh],part=app.subSelection.get(e.node.id),graph=adjacency(m);let vertices=m.vertices;if(part){const selected=new Set();for(const id of part.faces)for(const i of graph.faces.get(id)?.loops.flat()||[])selected.add(i);for(const key of part.edges){const edge=graph.edges.get(key);if(edge){selected.add(edge.a);selected.add(edge.b);}}vertices=[...selected].map(i=>m.vertices[i]);}for(const v of vertices)M.extendBounds(bounds,M.transform(inverse,M.transform(e.matrix,v)));}if(!Number.isFinite(bounds.min[0]))throw Error('Selection has no scalable geometry.');return {matrix,inverse,bounds};}
 scaleGrips(frame){const {min,max}=frame.bounds,extent=M.extent(frame.bounds),grips=[],seen=new Set();for(let x=0;x<3;x++)for(let y=0;y<3;y++)for(let z=0;z<3;z++){if(x===1&&y===1&&z===1)continue;const indices=[x,y,z],local=indices.map((v,i)=>min[i]+extent[i]*v/2),key=local.join(',');if(seen.has(key))continue;seen.add(key);grips.push({indices,local,world:M.transform(frame.matrix,local),active:indices.map((v,i)=>v!==1&&extent[i]>1e-7)});}return grips;}
 scalePivot(p){return this.modifiers.ctrl?M.center(p.frame.bounds):p.grip.indices.map((v,i)=>v===1?p.grip.local[i]:v===0?p.frame.bounds.max[i]:p.frame.bounds.min[i]);}
 scaleFactors(p){const pivot=this.scalePivot(p),c=this.app.renderer.camera,a=c.project(M.transform(p.frame.matrix,pivot)),b=c.project(p.grip.world),uniform=this.modifiers.shift||p.grip.active.filter(Boolean).length===3;if(!a||!b)return [1,1,1];const dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy,factor=den?((this.cursor.x-a[0])*dx+(this.cursor.y-a[1])*dy)/den:1;if(uniform)return [factor,factor,factor];const point=M.rayPlane(c.ray(this.cursor.x,this.cursor.y),p.grip.world,c.direction);if(!point)return [1,1,1];const local=M.transform(p.frame.inverse,point);return p.grip.active.map((active,i)=>active?(local[i]-pivot[i])/(p.grip.local[i]-pivot[i]):1);}
 scaleMatrix(p,factors){if(!p.frame){const center=M.center(projectBounds(this.app.doc.project,descendants(this.app.doc.project,this.app.selection)));return around(center,M.scaling(factors));}return M.mmul(p.frame.matrix,M.mmul(around(this.scalePivot(p),M.scaling(factors)),p.frame.inverse));}
 enter(text){let p=this.pending;const valueText=text.trim(),unit=this.app.doc.project.units,parse=x=>M.parseLength(x,unit);if(!valueText){if(this.id==='line')this.finishLine(false);else if(p&&['pushpull','offset','rotate','scale'].includes(p.kind))this.commitValue(p.kind==='scale'?p.factors:p.value);return;}
  if(/^[1-9]\d*\s*s$/i.test(valueText)&&['circle','arc'].includes(this.id)){const n=parseInt(valueText);if(n<3||n>2048)throw Error('Segment count must be between 3 and 2048.');this[this.id==='circle'?'circleSegments':'arcSegments']=n;this.app.measurement.value='';this.overlay();return;}
  const array=valueText.match(/^\s*(\d+)\s*(x|\*|\/)\s*$/i);if(array){const op=this.lastOperation;if(!op?.copy||!['move','rotate'].includes(op.kind)||op.history!==this.app.doc.undoStack.at(-1))throw Error('Create a copied move or rotation immediately before entering an array count.');this.app.transformSelection(op.matrix,op.label,{copy:true,count:Number(array[1]),division:array[2]==='/',amend:true,snapshot:op.snapshot,stepFactory:op.stepFactory});op.history=this.app.doc.undoStack.at(-1);this.app.measurement.value='';return;}
  if(!p&&this.id==='measure'&&this.lastMeasure){const length=parse(valueText);if(length<=0)throw Error('Target length must be positive.');this.resizeFromMeasure(length);return;}
  let amend=false;if(!p&&this.lastOperation?.kind===this.id&&this.lastOperation.history===this.app.doc.undoStack.at(-1)){p={...this.lastOperation.pending};this.pending=p;amend=true;}if(!p)throw Error('Begin a tool operation in the canvas first.');
  if(p.kind==='rotate'){const slope=valueText.match(/^([+-]?[\d.]+)\s*:\s*([+-]?[\d.]+)$/),angle=slope?Math.atan2(Number(slope[1]),Number(slope[2]))*180/Math.PI:Number(valueText.replace(/°|deg/g,''));if(!Number.isFinite(angle))throw Error('Enter degrees or a rise:run slope.');this.commitValue(angle,{amend});return;}
  if(p.kind==='scale'){const tokens=valueText.split(','),values=tokens.map((token,i)=>{const dimension=/[a-z'\"]/i.test(token),n=dimension?parse(token):Number(token);if(!Number.isFinite(n))throw Error('Invalid scale factor.');if(!dimension)return n;if(!p.frame)throw Error('Choose a scale grip for dimension entry.');const axis=tokens.length===1?p.grip.active.findIndex(Boolean):[0,2,1][i],extent=M.extent(p.frame.bounds)[axis];if(!extent)throw Error('A zero-width axis cannot be resized by dimension.');return n/extent;});let factors;if(values.length===3)factors=[values[0],values[2],values[1]];else if(values.length===1)factors=p.grip&&!this.modifiers.shift&&p.grip.active.filter(Boolean).length<3?p.grip.active.map(active=>active?values[0]:1):[values[0],values[0],values[0]];else throw Error('Enter one factor or three comma-separated factors.');this.commitValue(factors,{amend});return;}
  const coords=valueText.match(/^(\[|<)([^\]>]+)(\]|>)$/);if(coords){if(!['line','move'].includes(p.kind)||(coords[1]==='[')!==(coords[3]===']'))throw Error('Coordinates use [x,y,z] or <x,y,z>.');const values=coords[2].split(',').map(parse);if(values.length!==3||!values.every(Number.isFinite))throw Error('Enter three valid coordinates.');const point=coords[1]==='['?toWorld(values):M.add(this.anchor(),toWorld(values));if(p.kind==='line')this.addLinePoint(point);else this.commitValue(M.sub(point,p.anchor),{amend});return;}
  if(p.kind==='arc'&&p.points.length===2){const radius=/r$/i.test(valueText),n=parse(radius?valueText.slice(0,-1):valueText),[a,b]=p.points,chord=M.sub(b,a),half=M.len(chord)/2,perp=M.norm(M.cross(p.plane.normal,chord)),mid=M.mul(M.add(a,b),.5),sign=Math.sign(M.dot(M.sub(this.snapInfo?.point||M.add(mid,perp),mid),perp))||1;if(radius&&Math.abs(n)<half)throw Error('Radius cannot be less than half the chord.');const bulge=radius?(Math.abs(n)-Math.sqrt(n*n-half*half))*sign:n;this.createArc(p,M.add(mid,M.mul(perp,bulge)));this.cancel();return;}
  const values=valueText.split(',').map(parse);if(values.some(x=>!Number.isFinite(x)))throw Error('Enter valid measurements.');if(p.kind==='rectangle'){if(values.length!==2)throw Error('Enter width, depth.');const divisor=this.centerMode?2:1,b=M.add(p.a,M.add(M.mul(p.plane.u,values[0]/divisor),M.mul(p.plane.v,values[1]/divisor)));this.createRectangle(p,b);this.cancel();return;}if(p.kind==='circle'){this.createCircle(p,Math.abs(values[0]));this.cancel();return;}
  if(p.kind==='line'||p.kind==='move'){const anchor=this.anchor(),axis=this.axis?AXES[this.axis]:this.lockedDirection||this.parallelDirection,dir=axis?M.mul(axis,Math.sign(M.dot(M.sub(this.snapInfo?.point||M.add(anchor,axis),anchor),axis))||1):M.norm(M.sub(this.snapInfo?.point||M.add(anchor,[1,0,0]),anchor)),delta=values.length===3?toWorld(values):M.mul(dir,values[0]);if(p.kind==='line')this.addLinePoint(M.add(anchor,delta));else this.commitValue(delta,{amend});return;}this.commitValue(values[0],{amend});
 }
 commitValue(value,{amend=false}={}){const p=this.pending;if(!p)return;const app=this.app,copy=this.copyMode;app.renderer.previewTransform=null;app.renderer.clearGeometryPreview?.();let operation={kind:p.kind,pending:{...p},copy};
  if(['pushpull','offset'].includes(p.kind)){const hit=p.hit,entry=hit.entry,direction=p.direction||facingNormal(hit,app.renderer.camera),delta=M.transform(M.inverse(entry.matrix),M.mul(direction,value),0),perform=project=>{const source=project.meshes[hit.mesh.id];if(!source)throw Error('Source geometry no longer exists.');const changed=p.kind==='pushpull'?G.extrudeFace(source,hit.faceId,delta,{keepBase:copy}):G.transformMesh(G.offsetFace(G.transformMesh(source,entry.matrix),hit.faceId,value),M.inverse(entry.matrix));changed.id=source.id;project.meshes[source.id]=changed;};const label=p.kind==='pushpull'?'Push / Pull':'Offset';if(amend)app.doc.amendLast(label,perform);else app.doc.transaction(label,perform);if(p.kind==='pushpull')this.lastExtrusion=value;else this.lastOffset=value;app.select(null);}
  if(p.kind==='move'){const matrix=M.translation(value),label=copy?'Move copies':'Move',snapshot=app.transformSelection(matrix,label,{copy,amend,snapshot:amend?this.lastOperation.snapshot:null,autoFold:this.modifiers.alt});operation={...operation,matrix,label,snapshot};}
  if(p.kind==='rotate'){const center=p.center||M.center(projectBounds(app.doc.project,descendants(app.doc.project,app.selection))),normal=p.normal||AXES[this.axis||'z'],stepFactory=t=>around(center,M.rotation(normal,value*Math.PI/180*t)),matrix=stepFactory(1),label=copy?'Rotate copies':'Rotate',snapshot=app.transformSelection(matrix,label,{copy,amend,snapshot:amend?this.lastOperation.snapshot:null,stepFactory});operation={...operation,matrix,label,snapshot,stepFactory};}
  if(p.kind==='scale'){const factors=Array.isArray(value)?value:[value,value,value];if(factors.length!==3||factors.some(x=>!Number.isFinite(x)||Math.abs(x)<.00001))throw Error('Scale factors must be finite and nonzero.');const matrix=this.scaleMatrix(p,factors),snapshot=app.transformSelection(matrix,'Scale',{amend,snapshot:amend?this.lastOperation.snapshot:null});operation={...operation,matrix,label:'Scale',snapshot};}
  this.cancel();operation.history=app.doc.undoStack.at(-1);this.lastOperation=operation;app.canvas.focus();
 }
 resizeFromMeasure(length){const m=this.lastMeasure,factor=length/m.length,app=this.app;app.modal('Resize measured geometry',`<p class="modal-intro">Scale ${app.editContext?'the active context':'the whole model'} by ${factor.toFixed(6)} to make the measured distance ${M.formatLength(length,app.doc.project.units)}?</p><form><div class="modal-actions"><button type="button" data-action="close-modal">Cancel</button><button type="submit" class="button primary">Resize model</button></div></form>`,()=>{const previous=new Set(app.selection);app.selectMany(app.doc.project.nodes.filter(n=>n.parent===app.editContext&&!n.locked).map(n=>n.id));app.transformSelection(around(m.a,M.scaling([factor,factor,factor])),'Resize by measurement');app.selectMany([...previous]);app.closeModal();this.lastMeasure=null;});}
 marquee(a,b,e={},lasso=null){const app=this.app,p=app.doc.project,r=app.renderer,region=lasso||rectangularRegion(a,b),crossing=lasso?clockwise(region):b.x<a.x,mode=selectionMode(e,!!lasso),objects=new Map(),raw=new Map(),vp=r.camera.matrices([0,0,0]).vp;
  for(const entry of r.entries||[]){if(!entry.visible||!entry.node.mesh)continue;const root=contextRoot(p,entry.node.id,app.editContext);if(!root)continue;const mesh=p.meshes[entry.node.mesh],project=i=>projectWith(vp,M.transform(entry.matrix,mesh.vertices[i]),r.camera.width,r.camera.height);if(!isRaw(root)){const c=objects.get(root.id)||{all:true,any:false};for(const f of mesh.faces){if(f.hidden)continue;const pts=f.loops[0].map(project);c.all&&=polygonSelected(pts,region,false);c.any||=polygonSelected(pts,region,true);}for(const edge of adjacency(mesh).edges.values()){if(edge.hidden)continue;const pts=[project(edge.a),project(edge.b)];c.all&&=polygonSelected(pts,region,false,false);c.any||=polygonSelected(pts,region,true,false);}objects.set(root.id,c);}else{const part={faces:new Set(),edges:new Set()};for(const f of mesh.faces)if(!f.hidden&&(!f.tag||tagVisible(p,f.tag))&&polygonSelected(f.loops[0].map(project),region,crossing))part.faces.add(f.id);for(const edge of adjacency(mesh).edges.values())if(!edge.hidden&&!edge.soft&&!edge.smooth&&polygonSelected([project(edge.a),project(edge.b)],region,crossing,false))part.edges.add(edge.key);if(part.faces.size||part.edges.size)raw.set(root.id,part);}}
  if(mode==='replace'){app.selection.clear();app.subSelection.clear();}for(const [id,c] of objects)if(crossing?c.any:c.all)app.selection=applySelection(app.selection,[id],mode==='replace'?'add':mode);for(const [id,part] of raw){const old=app.subSelection.get(id)||{faces:new Set(),edges:new Set()},next={faces:applySelection(old.faces,part.faces,mode),edges:applySelection(old.edges,part.edges,mode)};if(next.faces.size||next.edges.size){app.selection.add(id);app.subSelection.set(id,next);}else{app.selection.delete(id);app.subSelection.delete(id);}}app.face=null;app.vertex=null;app.selectionChanged();
 }
 paintAt(hit,e){const app=this.app,root=contextRoot(app.doc.project,hit.node.id,app.editContext),material=hit.mesh.faces[hit.face].material??hit.entry.material;if(e.altKey){app.activeMaterial=material;app.renderMaterials();return;}if(hit.entry.locked)throw Error('This geometry is locked.');if(root&&!isRaw(root)){app.select(root.id);app.paintSelection();return;}if(!app.hitInContext(hit))return;const original=hit.mesh.faces[hit.face].material,target=app.activeMaterial;
  app.doc.transaction('Paint faces',p=>{const ids=e.shiftKey&&!e.ctrlKey?new Set(sceneEntries(p).filter(entry=>entry.visible&&!entry.locked&&entry.node.parent===app.editContext&&isRaw(entry.node)).map(entry=>entry.node.mesh)):new Set([hit.mesh.id]);for(const id of ids){const source=p.meshes[id],m=G.cloneMesh(source),selected=new Set();if(e.shiftKey){for(const f of m.faces)if(f.material===original)selected.add(f.id);}else if(e.ctrlKey){const graph=adjacency(source),queue=[hit.faceId];selected.add(hit.faceId);for(let i=0;i<queue.length;i++){const f=graph.faces.get(queue[i]);for(const l of f.loops)for(let j=0;j<l.length;j++)for(const neighbor of graph.edges.get(edgeKey(l[j],l[(j+1)%l.length])).faces)if(!selected.has(neighbor)&&graph.faces.get(neighbor).material===original){selected.add(neighbor);queue.push(neighbor);}}}else{selected.add(hit.faceId);if(source.smooth)for(const f of source.faces)selected.add(f.id);}for(const f of m.faces)if(selected.has(f.id))f.material=target;p.meshes[id]=m;}});app.renderMaterials();
 }
 eraseHits(hits,e){const app=this.app,valid=hits.filter(hit=>app.hitInContext(hit)&&!hit.entry.locked);if(!valid.length)return;app.doc.transaction('Erase / soften edges',p=>{const groups=new Map();for(const hit of valid){if(!groups.has(hit.mesh.id))groups.set(hit.mesh.id,new Set());groups.get(hit.mesh.id).add(hit.edgeKey);}for(const [id,keys] of groups){let result=G.cloneMesh(p.meshes[id]);result.edges=[...adjacency(result).edges.values()].map(edge=>({a:edge.a,b:edge.b,hidden:!!edge.hidden,soft:!!edge.soft||!!result.smooth,smooth:!!edge.smooth||!!result.smooth}));if(e.altKey||e.ctrlKey&&e.shiftKey){result.smooth=false;for(const edge of result.edges)if(keys.has(edgeKey(edge.a,edge.b))){edge.soft=false;edge.smooth=false;edge.hidden=false;}}else if(e.ctrlKey){for(const edge of result.edges)if(keys.has(edgeKey(edge.a,edge.b))){edge.soft=true;edge.smooth=true;}}else if(e.shiftKey){for(const edge of result.edges)if(keys.has(edgeKey(edge.a,edge.b)))edge.hidden=true;}else for(const key of keys)result=eraseEdge(result,key);p.meshes[id]=result;}});app.select(null);}
 previewPoints(){const p=this.pending,q=this.snapInfo?.point;if(!p)return null;if(p.kind==='rectangle'&&q)return G.rectangle(this.centerMode?M.sub(p.a,M.sub(q,p.a)):p.a,q,p.plane).vertices;if(p.kind==='circle'&&q){const radius=M.dist(p.a,q);return radius>1e-7?G.circle(p.a,radius,this.circleSegments,p.plane.normal).vertices:null;}if(p.kind==='line')return q?[p.points.at(-1),q]:p.points;if(p.kind==='arc'){if(p.points.length===2&&q)try{return this.arcPoints([...p.points,q],p.plane);}catch{}return q?[...p.points,q]:p.points;}if(['measure','dimension'].includes(p.kind)&&q)return [p.a,q];if(p.kind==='move'&&q)return [p.anchor,q];if(p.kind==='rotate'&&q)return [p.center,q];if(p.kind==='pushpull')return p.hit.mesh.faces[p.hit.face].loops[0].map(i=>M.add(M.transform(p.hit.entry.matrix,p.hit.mesh.vertices[i]),M.mul(p.direction||p.hit.normal,p.value||0)));return null;}
 overlay(){const app=this.app;if(!app.ready)return;const camera=app.renderer.camera,p=app.doc.project,preview=document.querySelector('#preview-layer'),selection=document.querySelector('#selection-layer'),snap=document.querySelector('#snap-layer'),dims=document.querySelector('#dimension-layer');if(!preview||!selection||!snap||!dims)return;for(const layer of [preview,selection,snap,dims])layer.replaceChildren();const vp=camera.matrices([0,0,0]).vp,project=point=>projectWith(vp,point,camera.width,camera.height),line=(layer,points,closed=false,attrs={})=>{const pts=points.map(project);if(pts.some(p=>!p))return;layer.append(svg(closed?'polygon':'polyline',{points:pts.map(p=>p.slice(0,2).join(',')).join(' '),fill:closed?'rgba(38,148,103,.10)':'none',stroke:'#278362','stroke-width':1.5,...attrs}));};
  const measured=(a,b,label)=>{const pa=project(a),pb=project(b);if(!pa||!pb)return;line(dims,[a,b],false,{stroke:'#475b51','stroke-dasharray':'4 3'});for(const p of [pa,pb])dims.append(svg('circle',{cx:p[0],cy:p[1],r:3,fill:'#f7f8f4',stroke:'#475b51'}));const x=(pa[0]+pb[0])/2,y=(pa[1]+pb[1])/2-9,text=label||M.formatLength(M.dist(a,b),p.units);dims.append(svg('rect',{x:x-text.length*3.4-6,y:y-12,width:text.length*6.8+12,height:19,rx:4,fill:'#f7f8f4',stroke:'#d8ded4'}));const el=svg('text',{x,y,'text-anchor':'middle',fill:'#344638','font-size':11,'font-family':'system-ui'});el.textContent=text;dims.append(el);};
  for(const m of p.measurements)measured(m.a,m.b,m.label);for(const guide of p.guides||[]){if(guide.point){const q=project(guide.point);if(q)dims.append(svg('path',{d:`M${q[0]-4},${q[1]}h8M${q[0]},${q[1]-4}v8`,stroke:'#596d75','stroke-width':1.2}));}else if(guide.a&&guide.b)line(dims,[guide.a,guide.b],false,{stroke:'#647780','stroke-dasharray':'9 5'});}
  const links=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];for(const root of app.selectedRoots())if(!app.subSelection.has(root.id)){const corners=M.corners(projectBounds(p,descendants(p,new Set([root.id]))));for(const [a,b] of links)line(selection,[corners[a],corners[b]],false,{stroke:'#2c8b66','stroke-width':1,'stroke-dasharray':'3 3'});}
  const entries=new Map((app.renderer.entries||[]).map(e=>[e.node.id,e]));for(const [id,part] of app.subSelection){const entry=entries.get(id),mesh=p.meshes[entry?.node.mesh];if(!entry||!mesh)continue;const graph=adjacency(mesh),screens=new Map(),get=i=>{if(!screens.has(i))screens.set(i,project(M.transform(entry.matrix,mesh.vertices[i])));return screens.get(i);};let faces='',edges='';for(const id of part.faces){const f=graph.faces.get(id);if(!f)continue;for(const l of f.loops){const points=l.map(get);if(points.some(p=>!p))continue;faces+='M'+points.map(p=>p.slice(0,2).join(',')).join('L')+'Z';}}for(const key of part.edges){const e=graph.edges.get(key);if(!e)continue;const a=get(e.a),b=get(e.b);if(a&&b)edges+=`M${a.slice(0,2).join(',')}L${b.slice(0,2).join(',')}`;}if(faces)selection.append(svg('path',{d:faces,fill:'rgba(62,164,116,.22)','fill-rule':'evenodd',stroke:'#188e59','stroke-width':1.2}));if(edges)selection.append(svg('path',{d:edges,fill:'none',stroke:'#138759','stroke-width':2.4}));}
  if(app.face&&app.vertex!=null){const e=entries.get(app.face.node.id),mesh=p.meshes[app.face.mesh.id],vertex=mesh?.vertices[app.vertex];if(e&&vertex){const q=project(M.transform(e.matrix,vertex));if(q)selection.append(svg('rect',{x:q[0]-4,y:q[1]-4,width:8,height:8,fill:'#fff',stroke:'#128858','stroke-width':2}));}}
  if(this.id==='scale'&&app.selection.size)try{for(const g of this.scaleGrips(this.pending?.frame||this.scaleFrame())){const q=project(g.world);if(q)selection.append(svg('rect',{x:q[0]-4,y:q[1]-4,width:8,height:8,fill:'#94c39f',stroke:'#255e3b','stroke-width':1.4}));}}catch{}
  const points=this.previewPoints();if(points?.length)line(preview,points,['rectangle','circle','pushpull'].includes(this.pending.kind),{'stroke-dasharray':'5 3'});if(['measure','dimension'].includes(this.pending?.kind)&&this.snapInfo)measured(this.pending.a,this.snapInfo.point);
  if(this.gesture?.moved&&!this.gesture.camera&&this.id==='select'){const a=this.gesture.start,b=this.cursor;preview.append(svg('rect',{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(a.x-b.x),height:Math.abs(a.y-b.y),fill:b.x<a.x?'rgba(67,148,106,.08)':'rgba(68,104,158,.08)',stroke:b.x<a.x?'#438d67':'#44689e','stroke-dasharray':b.x<a.x?'4 3':'none'}));}
  if(this.id==='lasso'){const points=this.gesture?.points||this.pending?.points;if(points?.length>1)preview.append(svg('polygon',{points:[...points,[this.cursor.x,this.cursor.y]].map(p=>p.join(',')).join(' '),fill:'rgba(67,148,106,.08)',stroke:'#438d67','stroke-dasharray':'4 3'}));}
  const anchor=this.anchor(),constraint=this.axis?AXES[this.axis]:this.lockedDirection||this.parallelDirection;if(anchor&&constraint){const span=camera.distance*2;line(preview,[M.sub(anchor,M.mul(constraint,span)),M.add(anchor,M.mul(constraint,span))],false,{stroke:AXIS_COLORS[this.axis]||'#ac62aa','stroke-dasharray':'7 4'});}
  if(this.snapInfo&&!['select','lasso','orbit','pan','zoom'].includes(this.id)){const q=project(this.snapInfo.point);if(q){const color=AXIS_COLORS[this.snapInfo.axis]||'#20885d';snap.append(svg('rect',{x:q[0]-3,y:q[1]-3,width:6,height:6,fill:'#ecfff3',stroke:color,'stroke-width':1.5}));const text=svg('text',{x:q[0]+12,y:q[1]-9,fill:color,'font-size':11,'font-family':'system-ui'});text.textContent=this.snapInfo.label+(this.copyMode&&['move','rotate','pushpull'].includes(this.id)?' · Copy':'');snap.append(text);}}
  const widget=document.querySelector('.axis-widget');if(widget){widget.replaceChildren();const view=svg('svg',{viewBox:'0 0 70 70',width:70,height:70,role:'img','aria-label':'Model axes: X red, Y green, Z blue'}),right=M.norm(M.cross(camera.direction,camera.up)),up=M.norm(M.cross(right,camera.direction));for(const [axis,d] of Object.entries(AXES)){const x=35+M.dot(d,right)*24,y=35-M.dot(d,up)*24;view.append(svg('line',{x1:35,y1:35,x2:x,y2:y,stroke:AXIS_COLORS[axis],'stroke-width':2}));const label=svg('text',{x:x+3,y:y-3,fill:AXIS_COLORS[axis],'font-size':11,'font-weight':700});label.textContent=axis.toUpperCase();view.append(label);}widget.append(view);}
 }
}
