import * as M from '../core/math.js';
import {sceneEntries,descendants,serializeProject} from '../core/document.js';
import {bakeMesh} from '../geometry/mesh.js';
import {zip} from '../io/zip.js';
const encoder=new TextEncoder();
const safe=(s)=>String(s).replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,100)||'model';
const linear=v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4;
const fmt=n=>Number(n.toFixed(7)).toString();
export function exportEntries(project,selection=null){const chosen=selection?.size?descendants(project,selection):null;return sceneEntries(project).filter(e=>e.visible&&e.node.mesh&&(!chosen||chosen.has(e.node.id)));}
function looseEdges(m){const used=new Set();for(const f of m.faces)for(const l of f.loops)for(let i=0;i<l.length;i++){const a=l[i],b=l[(i+1)%l.length];used.add(a<b?a+':'+b:b+':'+a);}return (m.edges||[]).filter(e=>!e.hidden&&!used.has(e.a<e.b?e.a+':'+e.b:e.b+':'+e.a));}
function* triangles(project,selection=null){const cache=new Map(),tags=new Map(project.tags.map(t=>[t.id,t.visible]));for(const e of exportEntries(project,selection)){const m=project.meshes[e.node.mesh];let baked=cache.get(m.id);if(!baked){baked=bakeMesh(m);if(baked.errors.length)throw Error(`Mesh ${m.name} has ${baked.errors.length} invalid faces. Repair them before exporting.`);cache.set(m.id,baked);}const reflected=M.dot(M.transform(e.matrix,[1,0,0],0),M.cross(M.transform(e.matrix,[0,1,0],0),M.transform(e.matrix,[0,0,1],0)))<0;for(const t of baked.triangles){const f=m.faces[t.face];if(tags.get(f.tag)===false)continue;const indices=reflected?[t.a,t.c,t.b]:[t.a,t.b,t.c];yield {points:indices.map(i=>M.transform(e.matrix,m.vertices[i])),material:f.material??e.material,node:e.node};}}}
export function exportSTL(project,selection=null){const ts=[...triangles(project,selection)];if(!ts.length)throw Error('No visible faces to export.');const bytes=new Uint8Array(84+ts.length*50),dv=new DataView(bytes.buffer);bytes.set(encoder.encode('SingleTake binary STL | coordinates in meters').subarray(0,80));dv.setUint32(80,ts.length,true);let at=84;for(const t of ts){const n=M.norm(M.cross(M.sub(t.points[1],t.points[0]),M.sub(t.points[2],t.points[0])));for(const v of [n,...t.points])for(const x of v){dv.setFloat32(at,x,true);at+=4;}dv.setUint16(at,0,true);at+=2;}return new Blob([bytes],{type:'model/stl'});}
export function exportPLY(project,selection=null){const ts=[...triangles(project,selection)],out=['ply','format ascii 1.0','comment SingleTake; meters; Y up',`element vertex ${ts.length*3}`,'property float x','property float y','property float z','property uchar red','property uchar green','property uchar blue',`element face ${ts.length}`,'property list uchar uint vertex_indices','end_header'];if(!ts.length)throw Error('No visible faces to export.');for(const t of ts){const c=(project.materials[t.material]||project.materials[0]).color.slice(0,3).map(v=>Math.round(v*255));for(const v of t.points)out.push(v.map(fmt).join(' ')+' '+c.join(' '));}for(let i=0;i<ts.length;i++)out.push(`3 ${i*3} ${i*3+1} ${i*3+2}`);return new Blob([out.join('\n')],{type:'application/octet-stream'});}
export function exportDXF(project,selection=null){const out=['0','SECTION','2','HEADER','9','$ACADVER','1','AC1015','9','$INSUNITS','70','6','0','ENDSEC','0','SECTION','2','ENTITIES'];const point=(p,j)=>{out.push(String(10+j),fmt(p[0]),String(20+j),fmt(-p[2]),String(30+j),fmt(p[1]));};for(const t of triangles(project,selection)){out.push('0','3DFACE','8',safe(t.node.name));for(let j=0;j<4;j++)point(t.points[Math.min(j,2)],j);}for(const e of exportEntries(project,selection)){const m=project.meshes[e.node.mesh];for(const edge of looseEdges(m)){out.push('0','LINE','8',safe(e.node.name));point(M.transform(e.matrix,m.vertices[edge.a]),0);point(M.transform(e.matrix,m.vertices[edge.b]),1);}}out.push('0','ENDSEC','0','EOF');return new Blob([out.join('\n')],{type:'application/dxf'});}
export async function exportOBJ(project,selection=null){
 const out=['# SingleTake OBJ; meters; Y up','# Textures and material definitions are in the accompanying MTL file.','mtllib materials.mtl'],mtl=['# SingleTake materials'],files=[],cache=new Map(),tags=new Map(project.tags.map(t=>[t.id,t.visible]));let offset=1,uvOffset=1;
 project.materials.forEach((m,i)=>{mtl.push(`newmtl mat_${i}`,`Kd ${m.color.slice(0,3).map(fmt).join(' ')}`,`d ${fmt(m.color[3]??1)}`,`Ns ${fmt(Math.max(0,2/(Math.max(.03,m.roughness||.7)**2)-2))}`);if(m.texture?.bytes?.length){const ext=m.texture.mime==='image/png'?'png':m.texture.mime==='image/webp'?'webp':'jpg',name=`textures/material_${i}.${ext}`;files.push([name,m.texture.bytes]);mtl.push(`map_Kd ${name}`);}mtl.push('');});
 for(const e of exportEntries(project,selection).sort((a,b)=>Number(!project.meshes[a.node.mesh].faces.length)-Number(!project.meshes[b.node.mesh].faces.length))){const m=project.meshes[e.node.mesh];let baked=cache.get(m.id);if(!baked){baked=bakeMesh(m);if(baked.errors.length)throw Error('Invalid faces in '+m.name);cache.set(m.id,baked);}const normalMatrix=M.transpose(M.inverse(e.matrix));out.push(`o ${safe(e.node.name)}`);const reflected=M.dot(M.transform(e.matrix,[1,0,0],0),M.cross(M.transform(e.matrix,[0,1,0],0),M.transform(e.matrix,[0,0,1],0)))<0;
  for(const g of baked.groups){if(tags.get(g.tag)===false)continue;const mi=g.material>=0?g.material:e.material,mat=project.materials[mi]||project.materials[0];out.push(`usemtl mat_${mi}`);for(let i=0;i<g.vertices.length;i+=8){const v=g.vertices.subarray(i,i+3),n=g.vertices.subarray(i+3,i+6),p=M.transform(e.matrix,v),nn=M.norm(M.transform(normalMatrix,n,0));out.push('v '+p.map(fmt).join(' '),'vt '+fmt(g.vertices[i+6])+' '+fmt(mat.texture&&!mat.texture.flipY?1-g.vertices[i+7]:g.vertices[i+7]),'vn '+nn.map(fmt).join(' '));}for(let i=0;i<g.indices.length;i+=3){const t=reflected?[g.indices[i],g.indices[i+2],g.indices[i+1]]:Array.from(g.indices.subarray(i,i+3));out.push('f '+t.map(k=>`${k+offset}/${k+uvOffset}/${k+uvOffset}`).join(' '));}offset+=g.vertices.length/8;uvOffset+=g.vertices.length/8;}
  const loose=looseEdges(m);if(loose.length){for(const v of m.vertices)out.push('v '+M.transform(e.matrix,v).map(fmt).join(' '));for(const edge of loose)out.push(`l ${edge.a+offset} ${edge.b+offset}`);offset+=m.vertices.length;}
 }
 files.push(['model.obj',encoder.encode(out.join('\n'))],['materials.mtl',encoder.encode(mtl.join('\n'))]);return zip(files);
}
export async function exportGLB(project,selection=null){
 const entries=exportEntries(project,selection),all=sceneEntries(project),byId=new Map(all.map(e=>[e.node.id,e])),keep=new Set(entries.map(e=>e.node.id));for(const e of entries){let n=e.node;while(n.parent){keep.add(n.parent);n=byId.get(n.parent).node;}}
 const json={asset:{version:'2.0',generator:'SingleTake 0.1'},scene:0,scenes:[{name:project.name,nodes:[]}],nodes:[],meshes:[],materials:[],buffers:[{byteLength:0}],bufferViews:[],accessors:[]},chunks=[];let byteLength=0;
 const addBuffer=(array,target)=>{const bytes=new Uint8Array(array.buffer||array,array.byteOffset||0,array.byteLength);const padding=(4-byteLength%4)%4;if(padding){chunks.push(new Uint8Array(padding));byteLength+=padding;}const index=json.bufferViews.length;json.bufferViews.push({buffer:0,byteOffset:byteLength,byteLength:bytes.byteLength,...(target?{target}:{})});chunks.push(bytes);byteLength+=bytes.byteLength;return index;};
 const addAccessor=(a,type,componentType,target,min,max)=>{const index=json.accessors.length;json.accessors.push({bufferView:addBuffer(a,target),componentType,count:a.length/({SCALAR:1,VEC2:2,VEC3:3}[type]),type,...(min?{min,max}:{})});return index;};
 project.materials.forEach(m=>{const gm={name:m.name,pbrMetallicRoughness:{baseColorFactor:[...m.color.slice(0,3).map(linear),m.color[3]??1],metallicFactor:m.metalness??0,roughnessFactor:m.roughness??.7},doubleSided:true};if((m.color[3]??1)<1)gm.alphaMode='BLEND';if(m.texture?.bytes?.length){json.images??=[];json.textures??=[];json.samplers??=[{magFilter:9729,minFilter:9729,wrapS:10497,wrapT:10497}];const image=json.images.length;json.images.push({name:m.name,bufferView:addBuffer(m.texture.bytes),mimeType:m.texture.mime||'image/png'});const tex=json.textures.length;json.textures.push({source:image,sampler:0});gm.pbrMetallicRoughness.baseColorTexture={index:tex};}json.materials.push(gm);});
 const bakedCache=new Map(),meshIndices=new Map(),nodeIndices=new Map(),tags=new Map(project.tags.map(t=>[t.id,t.visible]));
 for(const e of all){if(!keep.has(e.node.id))continue;const n={name:e.node.name,matrix:e.node.matrix.slice(),extras:{singletakeTag:e.node.tag}};if(e.node.mesh){const key=e.node.mesh+':'+e.material;let meshIndex=meshIndices.get(key);if(meshIndex===undefined){const source=project.meshes[e.node.mesh];let baked=bakedCache.get(source.id);if(!baked){baked=bakeMesh(source);if(baked.errors.length)throw Error('Invalid faces in '+source.name);bakedCache.set(source.id,baked);}const primitives=[];
   for(const g of baked.groups){if(tags.get(g.tag)===false)continue;const count=g.vertices.length/8,position=new Float32Array(count*3),normal=new Float32Array(count*3),uv=new Float32Array(count*2),mi=g.material>=0?g.material:e.material,mat=project.materials[mi]||project.materials[0],bound=M.emptyBounds();for(let i=0;i<count;i++){const v=g.vertices.subarray(i*8,i*8+3);position.set(v,i*3);normal.set(g.vertices.subarray(i*8+3,i*8+6),i*3);uv[i*2]=g.vertices[i*8+6];uv[i*2+1]=mat.texture?.flipY?1-g.vertices[i*8+7]:g.vertices[i*8+7];M.extendBounds(bound,v);}if(!count)continue;primitives.push({attributes:{POSITION:addAccessor(position,'VEC3',5126,34962,bound.min,bound.max),NORMAL:addAccessor(normal,'VEC3',5126,34962),TEXCOORD_0:addAccessor(uv,'VEC2',5126,34962)},indices:addAccessor(g.indices,'SCALAR',5125,34963),material:mi,mode:4});}
   const loose=looseEdges(source);if(loose.length){const position=new Float32Array(source.vertices.flat()),indices=new Uint32Array(loose.flatMap(x=>[x.a,x.b])),bound=M.bounds(source.vertices);primitives.push({attributes:{POSITION:addAccessor(position,'VEC3',5126,34962,bound.min,bound.max)},indices:addAccessor(indices,'SCALAR',5125,34963),mode:1,material:e.material});}
   if(primitives.length){meshIndex=json.meshes.length;json.meshes.push({name:source.name,primitives});meshIndices.set(key,meshIndex);}}
  if(meshIndex!==undefined)n.mesh=meshIndex;}
  nodeIndices.set(e.node.id,json.nodes.length);json.nodes.push(n);
 }
 for(const e of all){const i=nodeIndices.get(e.node.id);if(i===undefined)continue;const parent=nodeIndices.get(e.node.parent);if(parent!==undefined){json.nodes[parent].children??=[];json.nodes[parent].children.push(i);}else json.scenes[0].nodes.push(i);}
 const pad=(4-byteLength%4)%4;if(pad){chunks.push(new Uint8Array(pad));byteLength+=pad;}json.buffers[0].byteLength=byteLength;let jsonBytes=encoder.encode(JSON.stringify(json)),jsonPad=(4-jsonBytes.length%4)%4;if(jsonPad){const padded=new Uint8Array(jsonBytes.length+jsonPad).fill(32);padded.set(jsonBytes);jsonBytes=padded;}
 const header=new Uint8Array(20),dv=new DataView(header.buffer);dv.setUint32(0,0x46546c67,true);dv.setUint32(4,2,true);dv.setUint32(8,12+8+jsonBytes.length+8+byteLength,true);dv.setUint32(12,jsonBytes.length,true);dv.setUint32(16,0x4e4f534a,true);const bh=new Uint8Array(8),bd=new DataView(bh.buffer);bd.setUint32(0,byteLength,true);bd.setUint32(4,0x004e4942,true);return new Blob([header,jsonBytes,bh,...chunks],{type:'model/gltf-binary'});
}
export function exportTAKE(project){return new Blob([serializeProject(project)],{type:'application/json'});}
export async function exportFormat(project,format,selection=null){switch(format){case 'glb':return exportGLB(project,selection);case 'obj':return exportOBJ(project,selection);case 'stl':return exportSTL(project,selection);case 'ply':return exportPLY(project,selection);case 'dxf':return exportDXF(project,selection);case 'take':return exportTAKE(project);default:throw Error('Unsupported export format.');}}
