/** Runtime-neutral UTF-8/base64 and minimum data primitives; no browser APIs required. */
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
export function toBase64(input){const a=input instanceof Uint8Array?input:new Uint8Array(input.buffer||input,input.byteOffset||0,input.byteLength);const chunks=[];let out='';for(let i=0;i<a.length;i+=3){const n=(a[i]<<16)|((a[i+1]||0)<<8)|(a[i+2]||0);out+=alphabet[n>>>18]+alphabet[(n>>>12)&63]+(i+1<a.length?alphabet[(n>>>6)&63]:'=')+(i+2<a.length?alphabet[n&63]:'=');if(out.length>=16384){chunks.push(out);out='';}}chunks.push(out);return chunks.join('');}
export function fromBase64(text,maxBytes=300*1024*1024){if(typeof text!=='string'||text.length%4||text.length>Math.ceil(maxBytes/3)*4||/[^A-Za-z0-9+/=]/.test(text)||text.indexOf('=')!==-1&&text.indexOf('=')<text.length-(text.endsWith('==')?2:1))throw Error('Invalid or oversized base64 payload.');const len=text.length/4*3-(text.endsWith('==')?2:text.endsWith('=')?1:0);if(len>maxBytes)throw Error('Payload limit exceeded.');const bytes=new Uint8Array(len);for(let i=0,j=0;i<text.length;i+=4){const n=(alphabet.indexOf(text[i])<<18)|(alphabet.indexOf(text[i+1])<<12)|((alphabet.indexOf(text[i+2])&63)<<6)|(alphabet.indexOf(text[i+3])&63);if(j<len)bytes[j++]=n>>>16;if(j<len)bytes[j++]=n>>>8;if(j<len)bytes[j++]=n;}return bytes;}
export function utf8Encode(value){const bytes=[];for(const character of String(value)){let n=character.codePointAt(0);if(n>=0xd800&&n<=0xdfff)n=0xfffd;if(n<128)bytes.push(n);else if(n<2048)bytes.push(192|(n>>6),128|(n&63));else if(n<65536)bytes.push(224|(n>>12),128|((n>>6)&63),128|(n&63));else bytes.push(240|(n>>18),128|((n>>12)&63),128|((n>>6)&63),128|(n&63));}return Uint8Array.from(bytes);}
export function utf8Decode(input){const a=new Uint8Array(input.buffer||input,input.byteOffset||0,input.byteLength),out=[];for(let i=0;i<a.length;){const b=a[i++];if(b<128){out.push(String.fromCharCode(b));continue;}const count=b>=0xc2&&b<=0xdf?1:b>=0xe0&&b<=0xef?2:b>=0xf0&&b<=0xf4?3:0;if(!count){out.push('\ufffd');continue;}let n=b&((1<<(6-count))-1),valid=true,start=i;for(let j=0;j<count;j++){const v=a[i];if(v===undefined||(v&192)!==128){valid=false;break;}n=(n<<6)|(v&63);i++;}if(!valid){out.push('\ufffd');continue;}if(n<(count===1?128:count===2?2048:65536)||n>0x10ffff||(n>=0xd800&&n<=0xdfff)){out.push('\ufffd');continue;}out.push(String.fromCodePoint(n));}return out.join('');}
export class DataTextDecoder {constructor(label='utf-8'){this.label=String(label).toLowerCase();if(!['utf-8','utf8','utf-16le','utf-16be'].includes(this.label))throw Error('Unsupported text encoding: '+label);}decode(input=new Uint8Array()){if(this.label==='utf-8'||this.label==='utf8')return utf8Decode(input);const a=new Uint8Array(input.buffer||input,input.byteOffset||0,input.byteLength),little=this.label==='utf-16le';let text='';for(let i=0;i+1<a.length;i+=2){const n=little?a[i]|a[i+1]<<8:a[i]<<8|a[i+1];if(i===0&&n===0xfeff)continue;text+=String.fromCharCode(n);}if(a.length%2)text+='\ufffd';return text;}}
export class DataBlob{constructor(parts=[],options={}){this.type=options.type||'';this.parts=parts.map(p=>typeof p==='string'?utf8Encode(p):p instanceof DataBlob?p.bytes():p instanceof ArrayBuffer?new Uint8Array(p):ArrayBuffer.isView(p)?new Uint8Array(p.buffer,p.byteOffset,p.byteLength):utf8Encode(String(p)));this.size=this.parts.reduce((n,p)=>n+p.byteLength,0);}bytes(){const a=new Uint8Array(this.size);let i=0;for(const p of this.parts){a.set(p,i);i+=p.length;}return a;}async arrayBuffer(){return this.bytes().buffer;}async text(){return utf8Decode(this.bytes());}}
function copy(value,seen=new Map()){if(value===null||typeof value!=='object')return value;if(seen.has(value))return seen.get(value);if(value instanceof ArrayBuffer)return value.slice(0);if(ArrayBuffer.isView(value))return new value.constructor(value);if(value instanceof Date)return new Date(value);const result=Array.isArray(value)?[]:value instanceof Map?new Map():value instanceof Set?new Set():{};seen.set(value,result);if(value instanceof Map)for(const [k,v]of value)result.set(copy(k,seen),copy(v,seen));else if(value instanceof Set)for(const v of value)result.add(copy(v,seen));else for(const k of Object.keys(value))result[k]=copy(value[k],seen);return result;}
export function installDataPrimitives(){if(!globalThis.TextEncoder)globalThis.TextEncoder=class{encode(s=''){return utf8Encode(s);}};if(!globalThis.TextDecoder)globalThis.TextDecoder=DataTextDecoder;if(!globalThis.Blob)globalThis.Blob=DataBlob;if(!globalThis.structuredClone)globalThis.structuredClone=copy;if(!globalThis.atob)globalThis.atob=s=>Array.from(fromBase64(s),b=>String.fromCharCode(b)).join('');if(!globalThis.btoa)globalThis.btoa=s=>toBase64(Uint8Array.from(s,c=>c.charCodeAt(0)));if(!globalThis.CustomEvent)globalThis.CustomEvent=class extends Event{constructor(type,options={}){super(type,options);this.detail=options.detail;}};}
