import './primitives.js';
import * as M from '../../src/core/math.js';
import * as G from '../../src/geometry/mesh.js';
import {Document,newProject,makeNode,makeMaterial,sceneEntries,projectBounds,descendants,purge} from '../../src/core/document.js';
import {synchronizeDefinition} from '../../src/core/components.js';
import {assignTag} from '../../src/core/tags.js';
import {fromWorld,toWorld} from '../../src/core/coordinates.js';
import {Tools} from '../../src/ui/tools.js';
import {installModelInteractions} from '../../src/ui/model-interactions.js';
import {SHORTCUTS} from '../../src/ui/shortcuts.js';
import {importFiles} from '../../src/importers/formats.js';
import {exportFormat} from '../../src/exporters/formats.js';
import {booleanSolid} from '../../src/geometry/csg.js';
import {setNativeInflater} from '../../src/io/zip.js';
import {fromBase64,toBase64} from './encoding.js';
import {SceneProxy,collectOverlay} from './scene-proxy.js';
const $=s=>document.querySelector(s);
export const escapeText=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,id='')=>`<button data-action="${escapeText(action)}" data-id="${escapeText(id)}">${escapeText(label)}</button>`;
const toolNames=['select','lasso','line','rectangle','circle','arc','pushpull','offset','move','rotate','scale','paint','eraser','measure','dimension','vertex','edge','orbit','pan','zoom'];
const field=(label,key,value)=>`<label>${label}<input data-property="${key}" value="${escapeText(value)}"></label>`;
export function installPanel(){
 document.body.innerHTML=`<main id="desktop-panel"><header><h1>SingleTake</h1><p>Native desktop preview</p></header><nav>${button('new','New')}${button('open','Open')}${button('save','Save')}${button('export','Export')}${button('undo','Undo')}${button('redo','Redo')}</nav><div id="project-title"></div><section><h2>Tools</h2><div id="tool-grid">${toolNames.map(t=>`<button data-tool="${t}">${t.replace('-',' ')}</button>`).join('')}</div><div id="tool-label"></div><label>Measurements<input id="measurement" placeholder="Type a dimension; Enter applies" autocomplete="off"></label></section><section><h2>View</h2><nav>${button('fit','Fit')}${button('projection','Projection')}${button('view:iso','3D')}${button('view:top','Top')}${button('view:front','Front')}${button('view:right','Right')}${button('axes','Axes')}${button('grid','Grid')}${button('edges','Edges')}${button('section','Section')}${button('style','Style')}</nav><div id="editing-context"></div></section><section><h2>Model</h2><nav>${button('box','Box')}${button('sphere','Sphere')}${button('group','Group')}${button('component','Component')}${button('ungroup','Explode')}${button('unique','Make unique')}${button('duplicate','Duplicate')}${button('delete','Erase')}</nav><input id="outliner-search" placeholder="Find an object"><div id="outliner-tree"></div><div id="entity-info"></div></section><section><h2>Materials</h2><div id="material-grid"></div><div id="material-editor"></div>${button('add-material','New material')}${button('paint-selection','Apply')}</section><section><h2>Tags</h2><div id="tags-list"></div><nav>${button('add-tag','New tag')}${button('add-tag-folder','New folder')}${button('purge-tags','Purge')}${button('color-by-tag','Tag colors')}</nav></section><section><h2>Saved views</h2><div id="scene-list"></div>${button('save-scene','Save view')}</section><section><h2>Solid tools</h2><nav>${button('union','Union')}${button('subtract','Subtract')}${button('intersect','Intersect')}${button('triangulate','Triangulate')}${button('weld','Weld')}${button('sweep','Sweep')}</nav></section><footer>${button('command','Commands')}${button('help','Controls')}<p id="status-text">Ready</p></footer><div id="dialog" hidden><h2 id="dialog-title"></h2><div id="dialog-body"></div>${button('close-modal','Close')}</div><svg style="display:none" xmlns="http://www.w3.org/2000/svg"><g id="preview-layer"></g><g id="selection-layer"></g><g id="snap-layer"></g><g id="dimension-layer"></g></svg></main>`;
 const style=document.createElement('style');style.textContent=`*{box-sizing:border-box}body{margin:0;background:#202725;color:#e5e9e5;font-family:Arial,sans-serif;font-size:13px}main{padding:18px}header{border-bottom:1px solid #435048}h1{font-size:25px;margin:0}h2{font-size:12px;text-transform:uppercase;letter-spacing:1px;color:#afc7b7}p{color:#adbbb1;line-height:1.4}section{padding:9px 0;border-bottom:1px solid #39443d}button,input,select,textarea{font:inherit;color:inherit;background:#303b33;border:1px solid #526556;border-radius:4px;padding:7px;margin:2px}button{cursor:pointer}button.active{background:#697f5a}button:hover{border-color:#b2cb91}nav,#tool-grid{display:flex;flex-wrap:wrap;gap:2px}label{display:block;margin-top:6px}input,select,textarea{width:100%}#outliner-tree{max-height:220px;overflow:auto}#outliner-tree button{display:block;text-align:left;width:100%}#entity-info{padding:6px 0}#material-grid{display:flex;flex-wrap:wrap}#material-grid button{width:28px;height:28px}#tags-list>div{display:flex;align-items:center}#tags-list button{flex:1}#tags-list input{width:18px}#dialog{position:fixed;top:8px;left:8px;right:8px;bottom:8px;background:#26332c;padding:16px;overflow:auto;border:2px solid #9cbd80;border-radius:8px}#dialog[hidden]{display:none}#editing-context{color:#c5dfab}#status-text{overflow-wrap:anywhere}kbd{font-weight:bold}.shortcut-row{margin:5px 0}#project-title{margin-top:8px;font-weight:bold}`;document.head.appendChild(style);return style;
}
/** Application editing stays in JavaScript. The only desktop boundary is a narrow command capability. */
export class NativeApp {
 constructor(invoke){this.invoke=invoke;this.doc=new Document();this.selection=new Set();this.subSelection=new Map();this.expanded=new Set();this.editContext=null;this.face=null;this.vertex=null;this.activeMaterial=0;this.ready=true;this.disposed=false;this.framePending=false;this.frameFlight=null;this.listeners=[];this.renderer=new SceneProxy(()=>this.scheduleFrame());this.measurement=$('#measurement');this.canvas={style:{},focus:()=>this.invoke('focusViewport',{}).catch(e=>this.toast(e.message)),getBoundingClientRect:()=>({left:0,top:0,width:this.renderer.camera.width,height:this.renderer.camera.height}),setPointerCapture(){},releasePointerCapture(){},addEventListener(){}};this.tools=new Tools(this);this.overlayDirty=true;
  for(const method of ['transaction','amendLast']){const run=this.doc[method].bind(this.doc);this.doc[method]=(label,edit)=>{const before=method==='amendLast'?this.doc.undoStack.at(-1)?.before:this.doc.project;return run(label,p=>{edit(p);if(before&&this.editContext)synchronizeDefinition(before,p,this.editContext);});};}
  this.onChange=()=>{if(this.editContext&&!this.doc.project.nodes.some(n=>n.id===this.editContext))this.editContext=null;this.renderer.setProject(this.doc.project);this.tools.inference.invalidate();this.selectionChanged();this.renderAll();};this.doc.addEventListener('change',this.onChange);this.bind();setNativeInflater(async(bytes,expected)=>fromBase64((await this.invoke('inflate',{data:toBase64(bytes),expected})).data,expected));this.renderer.setProject(this.doc.project);this.renderAll();this.fit();
 }
 on(element,event,fn){element.addEventListener(event,fn);this.listeners.push(()=>element.removeEventListener(event,fn));}
 bind(){this.on(document,'click',e=>{const tool=e.target.closest?.('[data-tool]'),action=e.target.closest?.('[data-action]'),node=e.target.closest?.('[data-node]');if(tool)this.tools.set(tool.dataset.tool);else if(action)this.guard(()=>this.action(action.dataset.action,action));else if(node)this.select(node.dataset.node,e.ctrlKey?'add':e.shiftKey?'toggle':'replace');});this.on(document,'dblclick',e=>{const row=e.target.closest?.('[data-node]');if(row)this.guard(()=>this.enterContext(row.dataset.node));});this.on(document,'change',e=>this.guard(()=>this.propertyChange(e)));this.on(document,'keydown',e=>{if(e.target===this.measurement&&e.key==='Enter'){e.preventDefault();this.guard(()=>{this.tools.enter(this.measurement.value);this.measurement.value='';this.canvas.focus();});}else this.keydown(e);});this.on(document,'keyup',e=>this.tools.modifier(e,false));this.on($('#outliner-search'),'input',()=>this.renderOutliner());}
 async guard(fn){try{return await fn();}catch(error){this.toast(error.message||String(error),'error');}}
 toast(text){$('#status-text').textContent=String(text);this.invoke('status',{text:String(text).slice(0,400)}).catch(()=>{});}
 scheduleFrame(){if(this.disposed||this.framePending)return;this.framePending=true;setTimeout(()=>{this.framePending=false;this.guard(()=>this.flushFrame());},0);}
 async flushFrame(){if(this.disposed||this.frameFlight)return;if(!this.renderer.dirty)return;this.tools.overlay();const frame=this.renderer.packet(collectOverlay());this.renderer.dirty=false;this.frameFlight=this.invoke('frame',frame);try{const ack=await this.frameFlight;if(ack?.accepted!==frame.serial)throw Error('Native presenter did not accept the scene revision.');this.renderer.acknowledge(frame);}catch(error){this.renderer.resetResources();this.renderer.dirty=false;throw error;}finally{this.frameFlight=null;if(this.renderer.dirty)this.scheduleFrame();}}
 async receive(events){if(!Array.isArray(events)||events.length>512)throw Error('Invalid native input batch.');for(const input of events){const e={...input,clientX:input.x||0,clientY:input.y||0,button:input.button||0,buttons:input.buttons||0,pointerId:1,target:{closest:()=>null},preventDefault(){},stopPropagation(){}};switch(input.kind){case 'resize':this.renderer.resize(input.width,input.height);this.tools.inference.invalidate();break;case 'reset':this.renderer.resetResources();break;case 'down':this.tools.down(e);break;case 'move':this.tools.move(e);break;case 'up':await this.tools.up(e);break;case 'wheel':{const p=this.renderer.raycast(e.clientX,e.clientY);this.renderer.camera.zoomAt(input.deltaY,e.clientX,e.clientY,p?.point);this.tools.changedCamera();break;}case 'keyDown':this.keydown(e);if(/^[0-9.\-]$/.test(e.key)&&!e.ctrlKey&&!e.metaKey&&!e.altKey){await this.invoke('focusPanel',{});this.measurement.focus();}break;case 'keyUp':this.tools.modifier(e,false);break;case 'blur':this.tools.releaseModifiers();break;case 'action':await this.guard(()=>this.action(input.action));break;default:throw Error('Unknown native input.');}}this.renderer.requestRender();return {accepted:events.length};}
 renderAll(){$('#project-title').textContent=this.doc.project.name+(this.doc.dirty?' •':'');this.renderOutliner();this.renderEntity();this.renderTags();this.renderMaterials();this.renderScenes();this.renderContext();this.refreshTools();}
 refreshTools(){for(const b of document.querySelectorAll('[data-tool]'))b.classList.toggle('active',b.dataset.tool===this.tools.id);$('#tool-label').textContent=this.tools.id+(this.tools.axis?' · '+this.tools.axis.toUpperCase()+' locked':'');}
 renderContext(){const n=this.doc.project.nodes.find(n=>n.id===this.editContext);$('#editing-context').innerHTML=n?`Editing ${escapeText(n.name)} ${button('close-context','Done')}`:'';}
 renderOutliner(){const query=($('#outliner-search').value||'').toLowerCase(),p=this.doc.project;$('#outliner-tree').innerHTML=p.nodes.filter(n=>!query||n.name.toLowerCase().includes(query)).map(n=>{let depth=0,q=n;while(q.parent&&depth<128){depth++;q=p.nodes.find(x=>x.id===q.parent);if(!q)break;}return `<button data-node="${escapeText(n.id)}" class="${this.selection.has(n.id)?'active':''}" style="padding-left:${8+depth*12}px">${n.locked?'[locked] ':''}${escapeText(n.name)}${n.visible===false?' [hidden]':''}</button>`;}).join('')||'<p>Draw on the native canvas to begin.</p>';}
 renderEntity(){const n=this.doc.project.nodes.find(n=>this.selection.has(n.id));if(!n){$('#entity-info').textContent='No selection';return;}const m=this.doc.project.meshes[n.mesh];$('#entity-info').innerHTML=field('Name','node-name',n.name)+`<p>${this.selection.size} selected · ${m?m.faces.length+' faces':n.kind||'container'}</p><label>Tag<select data-property="node-tag">${this.doc.project.tags.filter(t=>!t.folder).map(t=>`<option value="${escapeText(t.id)}" ${t.id===n.tag?'selected':''}>${escapeText(t.name)}</option>`).join('')}</select></label>`+fromWorld([n.matrix[12],n.matrix[13],n.matrix[14]]).map((v,i)=>field('Position '+'XYZ'[i],'position-draw-'+i,v)).join('')+(this.vertex!=null&&m?fromWorld(m.vertices[this.vertex]).map((v,i)=>field('Vertex '+'XYZ'[i],'vertex-draw-'+i,v)).join(''):'')+button('node-visibility','Visibility',n.id)+button('lock','Lock/unlock')+(this.face?button('reverse-face','Reverse face'):'');}
 renderTags(){$('#tags-list').innerHTML=this.doc.project.tags.map(t=>`<div><input type="checkbox" data-property="tag-visible" data-id="${escapeText(t.id)}" ${t.visible!==false?'checked':''}><button data-action="edit-tag" data-id="${escapeText(t.id)}">${escapeText(t.name)}${t.folder?' [folder]':''}</button></div>`).join('');}
 renderMaterials(){const mats=this.doc.project.materials;this.activeMaterial=M.clamp(this.activeMaterial,0,mats.length-1);$('#material-grid').innerHTML=mats.map((m,i)=>`<button title="${escapeText(m.name)}" data-action="choose-material" data-index="${i}" style="background:rgb(${m.color.slice(0,3).map(x=>Math.round(x*255))})" class="${i===this.activeMaterial?'active':''}"></button>`).join('');const m=mats[this.activeMaterial];$('#material-editor').innerHTML=field('Material name','material-name',m.name)+field('Color (#rrggbb)','material-color','#'+m.color.slice(0,3).map(v=>Math.round(v*255).toString(16).padStart(2,'0')).join(''))+field('Roughness','material-roughness',m.roughness)+field('Metallic','material-metalness',m.metalness)+field('Opacity','material-opacity',m.color[3]);}
 renderScenes(){$('#scene-list').innerHTML=this.doc.project.scenes.map((s,i)=>`<button data-action="restore-scene" data-index="${i}">${escapeText(s.name)}</button>`).join('');}
 selectedRoots(){const p=this.doc.project;return p.nodes.filter(n=>this.selection.has(n.id)&&!(()=>{let q=n;while(q.parent){if(this.selection.has(q.parent))return true;q=p.nodes.find(x=>x.id===q.parent);}return false;})());}
 editableRoots(){const roots=this.selectedRoots(),entries=sceneEntries(this.doc.project);if(roots.some(n=>entries.find(e=>e.node.id===n.id)?.locked))throw Error('Unlock the selected object before editing.');return roots;}
 editMesh(label,hit,fn){if(hit.entry.locked)throw Error('This geometry is locked.');this.doc.transaction(label,p=>{const id=p.nodes.find(n=>n.id===hit.node.id).mesh,result=fn(p.meshes[id]);result.id=id;p.meshes[id]=result;});this.face=null;this.vertex=null;}
 paintSelection(){if(this.face){const face=this.face.faceId;this.editMesh('Paint face',this.face,m=>{const copy=G.cloneMesh(m);copy.faces.find(f=>f.id===face).material=this.activeMaterial;return copy;});}else{const ids=new Set(this.editableRoots().map(n=>n.id));this.doc.transaction('Paint selection',p=>{for(const n of p.nodes)if(ids.has(n.id))n.material=this.activeMaterial;});}}
 addMeasurement(a,b){this.doc.transaction('Add measurement',p=>p.measurements.push({id:M.uid('dim'),a:a.slice(),b:b.slice()}));}
 propertyChange(e){const key=e.target.dataset?.property,value=e.target.value,p=this.doc.project;if(!key)return;if(key==='tag-visible'){this.doc.transaction('Tag visibility',q=>q.tags.find(t=>t.id===e.target.dataset.id).visible=e.target.checked);return;}if(key.startsWith('material-')){this.doc.transaction('Material',q=>{const m=q.materials[this.activeMaterial],k=key.slice(9);if(k==='name')m.name=value.slice(0,200);else if(k==='color'){if(!/^#[0-9a-f]{6}$/i.test(value))throw Error('Enter #rrggbb.');m.color=[1,3,5].map(i=>parseInt(value.slice(i,i+2),16)/255).concat(m.color[3]);}else{const v=Number(value);if(!Number.isFinite(v)||v<0||v>1)throw Error('Enter a value between zero and one.');if(k==='opacity')m.color[3]=v;else m[k]=v;}});return;}const roots=this.editableRoots();if(!roots.length)return;if(key.startsWith('vertex-draw-')){const hit=this.face,vertex=this.vertex;if(!hit||vertex==null)return;const index=Number(key.slice(-1)),v=M.parseLength(value,p.units);this.editMesh('Move vertex',hit,m=>{const copy=G.cloneMesh(m),coords=fromWorld(copy.vertices[vertex]);coords[index]=v;copy.vertices[vertex]=toWorld(coords);for(const f of copy.faces){f.normal=undefined;f.cornerNormals=undefined;}if(G.bakeMesh(copy).errors.length)throw Error('Vertex move would produce an invalid face.');return copy;});return;}this.doc.transaction('Edit selection',q=>{if(key==='node-tag'){assignTag(q,new Set(roots.map(n=>n.id)),value);return;}for(const root of roots){const n=q.nodes.find(n=>n.id===root.id);if(key==='node-name')n.name=value.slice(0,200);if(key.startsWith('position-draw-')){const coords=fromWorld(n.matrix.slice(12,15));coords[Number(key.slice(-1))]=M.parseLength(value,p.units);n.matrix.splice(12,3,...toWorld(coords));}}});}
 async confirmReplace(){return !this.doc.dirty||(await this.invoke('confirmDiscard',{})).discard;}
 async open(append=false){if(!append&&!await this.confirmReplace())return;const result=await this.invoke('open',{});if(!result.files?.length)return;this.toast('Reading model…');const files=result.files.map(f=>({name:f.name,buffer:fromBase64(f.data).buffer}));const primary=files.find(f=>/\.(take|skp|glb|gltf|obj|stl|ply|dxf)$/i.test(f.name));if(!primary)throw Error('Select a model file and any companion assets.');const project=await importFiles(files,primary.name,1);if(append){const saved=this.clipboard;this.clipboard={nodes:project.nodes,meshes:project.meshes,materials:project.materials,tags:project.tags,documentId:project.id};this.paste(true);this.clipboard=saved;}else{this.editContext=null;this.selection.clear();this.subSelection.clear();this.doc.replace(project);}this.fit();this.toast('Opened '+primary.name);}
 async save(format='take'){const blob=await exportFormat(this.doc.project,format),data=toBase64(await blob.arrayBuffer()),extension=format==='obj'?'zip':format;const result=await this.invoke('save',{name:this.doc.project.name.replace(/[^a-z0-9_. -]/gi,'_')+'.'+extension,data});if(result.saved){if(format==='take'){this.doc.dirty=false;this.renderAll();}this.toast('Saved '+result.name);}}
 async action(action,buttonElement={dataset:{}}){const d=buttonElement.dataset||{},p=this.doc.project;switch(action){
  case 'new':if(await this.confirmReplace()){this.selection.clear();this.doc.replace(newProject());this.fit();}break;
  case 'open':await this.open();break;case 'import':await this.open(true);break;case 'save':await this.save();break;
  case 'undo':this.tools.cancel();this.doc.undo();break;case 'redo':this.tools.cancel();this.doc.redo();break;
  case 'deselect':this.select(null);break;case 'delete':this.deleteSelection();break;case 'copy':this.copy();break;case 'paste':this.paste();break;
  case 'group':this.group();break;case 'component':this.makeComponent();break;case 'ungroup':this.ungroup();break;
  case 'unique':{const ids=descendants(p,new Set(this.editableRoots().map(n=>n.id)));this.doc.transaction('Make unique',q=>{const map=new Map();for(const n of q.nodes)if(ids.has(n.id)){if(n.mesh){if(!map.has(n.mesh)){const mesh=G.cloneMesh(q.meshes[n.mesh]);mesh.id=M.uid('m');q.meshes[mesh.id]=mesh;map.set(n.mesh,mesh.id);}n.mesh=map.get(n.mesh);}if(n.component)n.component=M.uid('component');}});break;}
  case 'lock':{const ids=this.selection;this.doc.transaction('Toggle lock',q=>{for(const n of q.nodes)if(ids.has(n.id))n.locked=!n.locked;});break;}
  case 'node-visibility':this.doc.transaction('Visibility',q=>{const n=q.nodes.find(n=>n.id===d.id);n.visible=n.visible===false;});break;
  case 'fit':this.fit();break;case 'projection':this.renderer.camera.orthographic=!this.renderer.camera.orthographic;this.renderer.requestRender();break;
  case 'grid':case 'edges':this.renderer[action]=!this.renderer[action];this.renderer.requestRender();break;
  case 'style':this.renderer.style=(this.renderer.style+1)%4;this.renderer.requestRender();this.toast(['Material','Wireframe','Clay','X-ray'][this.renderer.style]);break;
  case 'section':this.prompt('Section height','Height in model units',p.section.value,v=>this.doc.transaction('Section plane',q=>{q.section.enabled=true;q.section.axis='y';q.section.value=M.parseLength(v,q.units);}));break;
  case 'section-off':this.doc.transaction('Disable section',q=>q.section.enabled=false);break;
  case 'choose-material':this.activeMaterial=Number(d.index);this.renderMaterials();this.tools.set('paint');break;case 'paint-selection':this.paintSelection();break;
  case 'add-material':this.doc.transaction('Add material',q=>q.materials.push(makeMaterial('New material')));this.activeMaterial=this.doc.project.materials.length-1;this.renderMaterials();break;
  case 'add-tag':this.prompt('New tag','Name','New tag',name=>this.doc.transaction('Add tag',q=>q.tags.push({id:M.uid('tag'),name,visible:true,color:'#789087',parent:null})));break;
  case 'tag-visibility':this.doc.transaction('Tag visibility',q=>{const t=q.tags.find(t=>t.id===d.id);t.visible=t.visible===false;});break;
  case 'box':this.prompt('Create box','Width, height, depth','2m, 2m, 2m',v=>{const n=v.split(',').map(x=>M.parseLength(x,p.units));if(n.length!==3||n.some(x=>!Number.isFinite(x)||x<=0))throw Error('Enter three positive dimensions.');this.addGeometry(G.box(...n));this.fit();});break;
  case 'sphere':this.prompt('Create sphere','Radius','1m',v=>{const r=M.parseLength(v,p.units);if(r<=0)throw Error('Radius must be positive.');this.addGeometry(G.sphere(r));this.fit();});break;
  case 'sweep':this.prompt('Sweep rectangular profile','Width, height; path X,Y,Z triples in model units','0.2,0.2;0,0,0;0,2,0;2,2,0',v=>{const parts=v.split(';').map(line=>line.split(',').map(x=>M.parseLength(x,p.units)));const [size,...path]=parts;if(size.length!==2||size.some(x=>x<=0)||path.length<2||path.some(x=>x.length!==3))throw Error('Enter a profile and at least two path triples.');this.addGeometry(G.sweep([[-size[0]/2,-size[1]/2],[size[0]/2,-size[1]/2],[size[0]/2,size[1]/2],[-size[0]/2,size[1]/2]],path.map(toWorld)));this.fit();});break;
  case 'union':case 'subtract':case 'intersect':this.boolean(action);break;
  case 'triangulate':case 'weld':{const ids=descendants(p,new Set(this.editableRoots().map(n=>n.id))),meshIds=new Set(p.nodes.filter(n=>ids.has(n.id)&&n.mesh).map(n=>n.mesh));this.doc.transaction(action,q=>{for(const id of meshIds){const source=q.meshes[id];if(action==='weld')q.meshes[id]=G.weld(source,1e-6);else{const b=G.bakeMesh(source);if(b.errors.length)throw Error('Invalid mesh.');const copy=G.cloneMesh(source);copy.faces=b.triangles.map(t=>G.face([[t.a,t.b,t.c]],source.faces[t.face].material));copy.edges=[];q.meshes[id]=copy;}}});break;}
  case 'reverse-face':{const id=this.face?.faceId;if(!id)throw Error('Select a face first.');this.editMesh('Reverse face',this.face,m=>{const c=G.cloneMesh(m),f=c.faces.find(x=>x.id===id);f.loops=f.loops.map(l=>l.slice().reverse());f.normal=undefined;f.cornerNormals=undefined;return c;});break;}
  case 'save-scene':this.prompt('Save view','Name','View '+(p.scenes.length+1),name=>this.doc.transaction('Save view',q=>q.scenes.push({id:M.uid('scene'),name,camera:this.renderer.camera.save(),section:{...q.section},tags:q.tags.map(t=>[t.id,t.visible])})));break;
  case 'restore-scene':{const s=p.scenes[Number(d.index)];this.renderer.camera.restore(s.camera);this.doc.transaction('Restore view',q=>{q.section={...s.section};for(const [id,visible]of s.tags||[]){const t=q.tags.find(t=>t.id===id);if(t)t.visible=visible;}});break;}
  case 'export':this.modal('Export a model',['take','glb','obj','stl','ply','dxf'].map(f=>button('export:'+f,f.toUpperCase())).join(''));break;
  case 'command':this.modal('Commands',`<input id="command-query" placeholder="Search"><div id="commands"></div>`);{const render=()=>{$('#commands').innerHTML=this.commands().filter(c=>c.name.toLowerCase().includes($('#command-query').value.toLowerCase())).map(c=>button('run:'+c.action,c.name)).join('');};$('#command-query').oninput=render;render();}break;
  case 'close-modal':this.closeModal();break;
  default:if(action.startsWith('view:')){this.renderer.camera.preset(action.slice(5));this.renderer.requestRender();}else if(action.startsWith('tool:'))this.tools.set(action.slice(5));else if(action.startsWith('export:')){await this.save(action.slice(7));this.closeModal();}else if(action.startsWith('run:')){this.closeModal();await this.action(action.slice(4));}else throw Error('This command has no desktop implementation: '+action);
 }}
 boolean(operation){const roots=this.editableRoots();if(roots.length!==2||roots.some(n=>!n.mesh))throw Error('Select two mesh objects.');const entries=new Map(sceneEntries(this.doc.project).map(e=>[e.node.id,e])),[a,b]=roots,ea=entries.get(a.id),eb=entries.get(b.id),result=booleanSolid(this.doc.project.meshes[a.mesh],this.doc.project.meshes[b.mesh],operation,{aMatrix:ea.matrix,bMatrix:eb.matrix,aMaterial:ea.material,bMaterial:eb.material});let id;this.doc.transaction(operation,p=>{p.nodes=p.nodes.filter(n=>n.id!==a.id&&n.id!==b.id);p.meshes[result.id]=result;const n=makeNode(result.name,result.id,{kind:'raw'});id=n.id;p.nodes.push(n);purge(p);});this.select(id);}
 modal(title,html,onSubmit=null){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').hidden=false;$('#dialog').open=true;if(onSubmit){const form=$('#dialog-body').querySelector('form');if(form)form.onsubmit=e=>{e.preventDefault();const values=new Map([...form.querySelectorAll('[name]')].map(el=>[el.name,el.value]));this.guard(()=>onSubmit({get:key=>values.get(key)||''}));};}this.invoke('focusPanel',{}).catch(()=>{});}
 closeModal(){$('#dialog').hidden=true;$('#dialog').open=false;$('#dialog-body').innerHTML='';this.canvas.focus();}
 prompt(title,label,value,apply){this.modal(title,`<form id="prompt-form"><label>${escapeText(label)}<input id="prompt-value" value="${escapeText(value)}"></label><button type="submit">Apply</button></form>`);$('#prompt-form').onsubmit=e=>{e.preventDefault();this.guard(async()=>{await apply($('#prompt-value').value);this.closeModal();});};$('#prompt-value').focus();}
 commands(){return [...toolNames.map(name=>({name,action:'tool:'+name})),...['open','save','export','new','undo','redo','group','component','ungroup','unique','box','sphere','sweep','union','subtract','intersect','section','section-off','projection','fit','copy','paste','triangulate','weld'].map(action=>({name:action,action}))];}
 help(){this.modal('Desktop controls',Object.entries(SHORTCUTS).map(([key,v])=>`<div><kbd>${escapeText(key)}</kbd> ${escapeText(v.tool||v.action)}</div>`).join('')+'<p>Middle-drag: orbit. Shift+middle-drag: pan. Scroll: zoom at cursor. Right/Left/Up: X/Y/Z lock. Hold Shift: inference lock. Double-click faces and groups; triple-click connected geometry. Core editing tools are shared; photo matching and browser-only commands are not desktop features.</p>');}
 context(){this.modal('Selection', ['copy','paste','group','component','ungroup','unique','duplicate','delete','fit-selection','close-context'].map(a=>button('run:'+a,a)).join(''));}
 hideContext(){} hidePhotoReference(){} hideLoading(){} showLoading(text){this.toast(text);} renderReport(){}
 async dispose(){this.disposed=true;this.ready=false;for(const remove of this.listeners)remove();this.doc.removeEventListener('change',this.onChange);setNativeInflater(null);this.tools.releaseModifiers();if(this.frameFlight)try{await this.frameFlight;}catch{}}
}
// Install the same geometry/context/input semantics; retain the desktop UI and lifecycle, not browser IO.
const desktopMethods={};for(const name of ['bind','renderEntity','renderOutliner','renderTags','renderContext','propertyChange','help','hidePhotoReference'])desktopMethods[name]=NativeApp.prototype[name];
installModelInteractions(NativeApp);
for(const [name,method]of Object.entries(desktopMethods))NativeApp.prototype[name]=method;
// Keep unsupported photo operations explicit rather than falling into browser file controls.
NativeApp.prototype.photoNavigation=function(){this.toast('Photo-reference presentation is not implemented in the native preview.');};
NativeApp.prototype.addPhotoReference=NativeApp.prototype.photoNavigation;
