export function selectionMode(e={},lasso=false){const add=e.ctrlKey||e.metaKey||lasso&&e.altKey;return add&&e.shiftKey?'remove':add?'add':e.shiftKey?'toggle':'replace';}
export function applySelection(current,values,mode='replace'){const result=new Set(mode==='replace'?[]:current);for(const id of values){if(mode==='remove'||mode==='toggle'&&result.has(id))result.delete(id);else result.add(id);}return result;}
export function isRaw(node){return !!node.mesh&&!node.component&&node.kind!=='component'&&node.kind!=='group';}
export function contextRoot(project,id,context=null){const map=new Map(project.nodes.map(n=>[n.id,n]));let n=map.get(id);if(!n||n.id===context)return null;while(n.parent!==context){if(!n.parent)return null;n=map.get(n.parent);if(!n||n.id===context)return null;}return n;}
export function pointInPolygon(p,loop){let inside=false;for(let i=0,j=loop.length-1;i<loop.length;j=i++){const a=loop[i],b=loop[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function segmentCross(a,b,c,d){const o=(p,q,r)=>(q[0]-p[0])*(r[1]-p[1])-(q[1]-p[1])*(r[0]-p[0]);if(o(a,b,c)*o(a,b,d)>0||o(c,d,a)*o(c,d,b)>0)return false;return Math.max(a[0],b[0])+1e-8>=Math.min(c[0],d[0])&&Math.max(c[0],d[0])+1e-8>=Math.min(a[0],b[0])&&Math.max(a[1],b[1])+1e-8>=Math.min(c[1],d[1])&&Math.max(c[1],d[1])+1e-8>=Math.min(a[1],b[1]);}
export function polygonSelected(points,region,crossing=false,closed=true){if(!points.length||points.some(p=>!p))return false;const inside=points.map(p=>pointInPolygon(p,region));if(!crossing)return inside.every(Boolean);if(inside.some(Boolean))return true;if(closed&&points.length>2&&region.some(p=>pointInPolygon(p,points)))return true;for(let i=0;i<(closed?points.length:points.length-1);i++)for(let j=0;j<region.length;j++)if(segmentCross(points[i],points[(i+1)%points.length],region[j],region[(j+1)%region.length]))return true;return false;}
export const rectangularRegion=(a,b)=>[[Math.min(a.x,b.x),Math.min(a.y,b.y)],[Math.max(a.x,b.x),Math.min(a.y,b.y)],[Math.max(a.x,b.x),Math.max(a.y,b.y)],[Math.min(a.x,b.x),Math.max(a.y,b.y)]];
export const clockwise=points=>points.reduce((s,p,i)=>{const q=points[(i+1)%points.length];return s+p[0]*q[1]-q[0]*p[1];},0)>0;
