import {installModelInteractions} from './ui/model-interactions.js';
import {toWorld} from './core/coordinates.js';
import * as M from './core/math.js';
import * as G from './geometry/mesh.js';
import {Document,newProject,makeNode,makeMaterial,sceneEntries,projectBounds,descendants,purge,validateProject} from './core/document.js';
import {Tools} from './ui/tools.js';
import {icon,TOOLS} from './ui/icons.js';
import {exportFormat,exportTAKE} from './exporters/formats.js';
import {formValues,showDialog,closeDialog,submitForm,trapDialogFocus} from './ui/forms.js';
const $=(q)=>document.querySelector(q),$$=(q)=>[...document.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n<1048576?(n/1024).toFixed(0)+' KB':(n/1048576).toFixed(1)+' MB';
const nice=n=>Number(n||0).toLocaleString();
const colorHex=c=>'#'+c.slice(0,3).map(x=>Math.round(M.clamp(x,0,1)*255).toString(16).padStart(2,'0')).join('');
const readColor=s=>[1,3,5].map(i=>parseInt(s.slice(i,i+2),16)/255);
const nameFile=s=>String(s).replace(/[^\w .-]/g,'_').slice(0,100)||'Model';
const DOWNLOAD_EXT={obj:'zip',take:'take',glb:'glb',stl:'stl',ply:'ply',dxf:'dxf'};
export class App {
 constructor(platform){if(!platform?.createRenderer)throw Error('An application platform is required.');this.platform=platform;this.listeners=[];this.disposed=false;this.canvas=$('#canvas');if(!this.canvas)throw Error('The canonical application canvas is missing.');this.measurement=$('#measurement-input');this.doc=new Document();this.renderer=platform.createRenderer(this.canvas);this.ready=false;this.selection=new Set();this.subSelection=new Map();this.editContext=null;this.face=null;this.vertex=null;this.expanded=new Set();this.activeMaterial=0;this.previewURLs=new Map();this.clipboard=null;this.loadWorker=null;this.autoTimer=null;this.gpuErrors=new Set();this.importScale=1;this.tools=new Tools(this);this.modalSubmit=null;this.startup=true;
  this.buildToolbar();this.bind();this.refreshTools();this.renderPanels();
 }
 async init(){
  try{await this.renderer.init();this.ready=true;if(this.renderer.capabilities?.shadows===false){const control=$('#shadows-toggle');control.checked=false;control.disabled=true;control.title='Shadow maps are not implemented by the active native renderer.';}$('#engine-label').textContent=this.platform.engineLabel;}catch(e){this.initializationError=e;this.gpuFailure(e.message);}
  let saved;try{saved=await this.platform.loadWorkspace();if(saved)validateProject(saved.project);}catch(e){this.toast('Local recovery is unavailable: '+e.message,'warning');saved=null;}
  try{if(saved){this.doc.replace(saved.project);if(saved.camera)this.renderer.camera.restore(saved.camera);this.toast('Recovered your local workspace.','success');this.expanded.add(this.doc.project.nodes[0]?.id);}else this.doc.replace(newProject());}catch(e){this.toast(e.message,'error');this.doc.replace(newProject());}
  this.startup=false;this.hideLoading();this.renderPanels();if(this.ready){await this.renderer.setProject(this.doc.project);if(!saved)this.fit();this.tools.overlay();}
 }
 buildToolbar(){for(const group of ['main','edit','view'])$('#tools-'+group).innerHTML=TOOLS.filter(t=>t.group===group).map(t=>`<button class="tool-button${t.id==='select'?' active':''}" data-tool="${t.id}" title="${t.label} · ${t.key}" aria-label="${t.label}" aria-pressed="${t.id==='select'}">${icon(t.id)}<span class="tool-tooltip">${t.label}<kbd>${t.key}</kbd></span></button>`).join('');const set=(id,name,label)=>$(id).innerHTML=icon(name)+(label?`<span>${label}</span>`:'');set('#undo-button','undo');set('#redo-button','redo');set('#open-button','open','Open');set('#save-button','save','Save model');set('#new-button','plus','New');set('#export-button','export','Export');set('#command-button','command','Commands');set('#rail-command','command');set('#fit-button','fit');set('#view-iso','box');}
 bind(){
  this.listen(document,'click',e=>{const btn=e.target.closest('button,[data-action]');if(!btn)return;const run=()=>{if(btn.dataset.tool)this.tools.set(btn.dataset.tool);else if(btn.dataset.action)return this.action(btn.dataset.action,btn);else if(btn.dataset.tab)this.tab(btn.dataset.tab);else if(btn.dataset.style!==undefined){this.renderer.style=+btn.dataset.style;$$('[data-style]').forEach(b=>b.classList.toggle('active',b===btn));this.renderer.requestRender();}else if(btn.dataset.view){this.renderer.camera.preset(btn.dataset.view);this.renderer.requestRender();this.tools.overlay();}else if(btn.dataset.node){this.select(btn.dataset.node,e.ctrlKey&&e.shiftKey?'remove':e.ctrlKey?'add':e.shiftKey?'toggle':'replace');}};Promise.resolve().then(run).catch(err=>this.toast(err.message,'error'));});
  this.listen(document,'keydown',e=>{const dialog=$('#dialog');if(dialog.hasAttribute('open')){if(e.key==='Escape'){e.preventDefault();this.closeModal();return;}if(trapDialogFocus(dialog,e))return;const form=e.target.closest?.('#dialog form');if(e.key==='Enter'&&form&&e.target.tagName.toLowerCase()!=='textarea'){e.preventDefault();submitForm(form);return;}}this.keydown(e);});this.listen(document,'pointerdown',e=>{if(!e.target.closest('#context-menu'))this.hideContext();});
  this.listen($('#outliner-search'),'input',()=>this.renderOutliner());
  this.listen(this.measurement,'keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();this.guard(()=>this.tools.enter(this.measurement.value));}if(e.key==='Escape'){this.tools.cancel();this.canvas.focus();}});
  this.listen($('#file-input'),'change',async e=>{const files=[...e.target.files];e.target.value='';if(files.length){const append=!!this.appendNext;this.appendNext=false;if(!append&&!await this.confirmReplace())return;await this.guard(()=>this.openFiles(files,append));}});
  this.listen($('#texture-input'),'change',e=>this.guard(async()=>{const f=e.target.files[0];e.target.value='';if(f)await this.setTextureFile(f);}));
  for(const [id,key] of [['shadows-toggle','shadows'],['edges-toggle','edges'],['grid-toggle','grid']])this.listen($('#'+id),'change',e=>{this.renderer[key]=e.target.checked;this.renderer.requestRender();});
  this.listen($('#section-toggle'),'change',e=>this.doc.transaction('Toggle section',p=>p.section.enabled=e.target.checked));this.listen($('#section-axis'),'change',e=>this.doc.transaction('Section axis',p=>p.section.axis=e.target.value));this.listen($('#section-slider'),'change',e=>this.doc.transaction('Move section',p=>p.section.value=Number(e.target.value)));this.listen($('#section-slider'),'input',e=>$('#section-value').textContent=M.formatLength(Number(e.target.value),this.doc.project.units));
  this.listen(document,'change',e=>this.guard(()=>this.propertyChange(e)));
  this.listen($('#dialog'),'cancel',e=>{e.preventDefault();this.closeModal();});this.listen($('#dialog'),'click',e=>{const button=e.target.closest?.('button');const form=button?.closest('form');if(form&&(button.getAttribute('type')||'submit')==='submit'){e.preventDefault();submitForm(form);}});this.listen($('#dialog'),'click',e=>{if(e.target===$('#dialog'))this.closeModal();});this.listen($('#dialog'),'submit',e=>{e.preventDefault();this.guard(async()=>{const fn=this.modalSubmit;if(fn)await fn(formValues(e.target));});});
  const view=$('#viewport');let drags=0;this.listen(view,'dragenter',e=>{if(!e.dataTransfer.types.includes('Files'))return;e.preventDefault();drags++;$('#drop-zone').classList.remove('hidden');});this.listen(view,'dragover',e=>e.preventDefault());this.listen(view,'dragleave',()=>{if(--drags<=0)$('#drop-zone').classList.add('hidden');});this.listen(view,'drop',async e=>{e.preventDefault();drags=0;$('#drop-zone').classList.add('hidden');const files=[...e.dataTransfer.files];if(files.length&&await this.confirmReplace())await this.guard(()=>this.openFiles(files));});
  this.listen($('#cancel-load'),'click',()=>{this.loadWorker?.terminate();this.loadReject?.(Error('Import cancelled.'));this.loadWorker=null;this.hideLoading();});
  this.listen(this.doc,'change',()=>{this.selection=new Set([...this.selection].filter(id=>this.doc.project.nodes.some(n=>n.id===id)));if(this.face){const m=this.doc.project.meshes[this.face.mesh.id];if(!m?.faces.some(f=>f.id===this.face.faceId))this.face=null;}this.activeMaterial=Math.min(this.activeMaterial,this.doc.project.materials.length-1);this.renderPanels();if(this.ready&&!this.loadingModel&&!this.startup)this.renderer.setProject(this.doc.project).then(()=>{if(this.disposed)return;this.renderer.selected=this.highlightedSelection();this.renderer.requestRender();this.tools.overlay();}).catch(e=>this.toast(e.message,'error'));if(!this.startup)this.scheduleSave();});
  this.listen(this.renderer,'frame',e=>{const s=e.detail;$('#render-stats').textContent=`${nice(s.triangles)} tris · ${nice(s.draws)} draws · ${s.gpuMs!=null?s.gpuMs.toFixed(1)+' ms GPU':s.cpuMs.toFixed(1)+' ms CPU'}`;this.tools.overlay();});
  for(const type of ['error','warning','lost'])this.listen(this.renderer,type,e=>{if(this.gpuErrors.has(e.detail))return;this.gpuErrors.add(e.detail);if(type==='lost'){this.ready=false;this.gpuFailure(e.detail);}this.toast(e.detail,type==='warning'?'warning':'error');});
  this.listen(window,'beforeunload',e=>{if(this.doc.dirty&&this.unsavedLocal){e.preventDefault();e.returnValue='';}});
 }
 listen(target,type,handler,options){if(!target)return;target.addEventListener(type,handler,options);(this.listeners??=[]).push(()=>target.removeEventListener(type,handler,options));return handler;}
 async setTextureFile(file){if(file.size>30*1048576)throw Error('Texture files must be smaller than 30 MB.');const texture={bytes:new Uint8Array(await file.arrayBuffer()),mime:file.type,name:file.name,flipY:false};this.doc.transaction('Set texture',p=>{p.materials[this.activeMaterial].texture=texture;p.materials[this.activeMaterial].color=[1,1,1,p.materials[this.activeMaterial].color[3]];});}
 async pickModelFiles(append=false){this.appendNext=append;if(!this.platform.pickFiles){$('#file-input').click();return;}const files=await this.platform.pickFiles('model');if(!files.length)return;if(!append&&!await this.confirmReplace())return;await this.openFiles(files,append);}
 async dispose(){if(this.disposed)return;this.disposed=true;this.ready=false;clearTimeout(this.autoTimer);this.loadWorker?.terminate();this.loadReject?.(Error('Application closed.'));this.tools.releaseModifiers();for(const remove of this.listeners.splice(0))remove();this.modalResolve?.(false);this.modalResolve=null;for(const url of this.previewURLs.values())this.platform.revokeImageURL(url);this.previewURLs.clear();this.hidePhotoReference?.();await this.renderer.dispose();await this.platform.dispose?.();}

 guard(fn){return Promise.resolve().then(fn).catch(e=>{console.error(e);this.toast(e.message||String(e),'error');});}
 gpuFailure(message){this.ready=false;$('#engine-label').textContent='GPU unavailable';$('#render-stats').textContent=this.platform.engineLabel+' not running';let card=$('#gpu-error');if(!card){card=document.createElement('div');card.id='gpu-error';card.className='gpu-error';$('#viewport').append(card);}card.innerHTML=`${icon('info',32)}<h2>The rendering device is unavailable.</h2><p>${esc(message)}</p><p class="quiet">Model import, inspection, saving, and export remain available. The canvas is not a substitute preview.</p><button class="button primary" data-action="reload-gpu">Retry GPU</button>`;}
 refreshTools(){const t=TOOLS.find(t=>t.id===this.tools.id)||{label:this.tools.id==='vertex'?'Vertex edit':'Edge inspection',hint:'Click a face, then edit its nearest vertex coordinates in Entity Info.'};$$('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===this.tools.id);b.setAttribute('aria-pressed',b.dataset.tool===this.tools.id);});$('#active-tool-label').textContent=t.label;$('#status-instruction').textContent=t.hint;$('#measurement-label').textContent={rectangle:'Width, depth',circle:'Radius',pushpull:'Distance',offset:'Inset',move:'X, Y, Z',rotate:'Degrees',scale:'Scale factor'}[this.tools.id]||'Measurements';this.measurement.value='';this.measurement.placeholder='Type a precise value';}
 toast(message,type='info'){const el=document.createElement('div');el.className='toast '+type;el.innerHTML=`<span>${icon(type==='success'?'check':'info',17)}</span><p></p><button aria-label="Dismiss">×</button>`;el.querySelector('p').textContent=message;el.querySelector('button').onclick=()=>el.remove();$('#toast-stack').append(el);setTimeout(()=>el.remove(),type==='error'?15000:6500);}
 tab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===name+'-panel'));}
 select(id,add=false,face=null){if(!add)this.selection.clear();if(id){if(add&&this.selection.has(id))this.selection.delete(id);else this.selection.add(id);}this.face=face;this.vertex=null;this.renderer.selected=this.highlightedSelection();this.renderOutliner();this.renderEntity();this.renderer.requestRender();this.tools.overlay();$('#selection-hint').classList.toggle('hidden',this.selection.size>0);}
 selectMany(ids,add=false){if(!add)this.selection.clear();for(const id of ids)this.selection.add(id);this.face=null;this.vertex=null;this.renderer.selected=this.highlightedSelection();this.renderOutliner();this.renderEntity();this.renderer.requestRender();this.tools.overlay();}
 selectedRoots(){const byId=new Map(this.doc.project.nodes.map(n=>[n.id,n]));return this.doc.project.nodes.filter(n=>{if(!this.selection.has(n.id))return false;let a=n;while(a.parent){a=byId.get(a.parent);if(this.selection.has(a.id))return false;}return true;});}
 editableRoots(){const locked=new Set(sceneEntries(this.doc.project).filter(e=>e.locked).map(e=>e.node.id));const roots=this.selectedRoots();if(!roots.length)throw Error('Select an object first.');if(roots.some(n=>locked.has(n.id)))throw Error('Unlock the selected objects before editing.');return roots;}
 addGeometry(mesh,name=mesh.name){for(const f of mesh.faces)if(f.material==null)f.material=this.activeMaterial;const id=this.doc.addMesh(mesh,name);this.select(id);this.toast(name+' created.','success');return id;}
 editMesh(label,hit,fn){const n=this.doc.project.nodes.find(n=>n.id===hit.node.id),entry=sceneEntries(this.doc.project).find(e=>e.node.id===n?.id);if(!n||entry.locked)throw Error('This object is locked or no longer exists.');this.doc.transaction(label,p=>{const source=p.meshes[n.mesh],changed=fn(source);changed.id=source.id;p.meshes[source.id]=changed;});this.face=null;this.vertex=null;}
 transformSelection(worldTransform,label){const roots=this.editableRoots(),entries=new Map(sceneEntries(this.doc.project).map(e=>[e.node.id,e]));this.doc.transaction(label,p=>{for(const root of roots){const n=p.nodes.find(n=>n.id===root.id),parent=n.parent?entries.get(n.parent).matrix:M.identity();n.matrix=M.mmul(M.inverse(parent),M.mmul(worldTransform,entries.get(n.id).matrix));}});this.face=null;this.vertex=null;}
 paintSelection(){if(this.face){this.editMesh('Paint face',this.face,m=>{const copy=G.cloneMesh(m);copy.faces.find(f=>f.id===this.face.faceId).material=this.activeMaterial;return copy;});}else{const roots=this.editableRoots();this.doc.transaction('Paint object',p=>{for(const n of roots){const target=p.nodes.find(x=>x.id===n.id);target.material=this.activeMaterial;if(target.mesh){const original=p.meshes[target.mesh],copy=G.cloneMesh(original);copy.id=M.uid('m');for(const f of copy.faces)f.material=this.activeMaterial;p.meshes[copy.id]=copy;target.mesh=copy.id;}}});}this.toast('Material applied.','success');}
 deleteFace(){if(!this.face)throw Error('Double-click a face first.');const id=this.face.faceId;this.editMesh('Erase face',this.face,m=>{const copy=G.cloneMesh(m);copy.faces=copy.faces.filter(f=>f.id!==id);copy.edges=[];return copy;});this.face=null;}
 deleteSelection(){const roots=this.editableRoots(),ids=descendants(this.doc.project,new Set(roots.map(n=>n.id)));this.doc.transaction('Erase objects',p=>{p.nodes=p.nodes.filter(n=>!ids.has(n.id));purge(p);});this.select(null);}
 addMeasurement(a,b){if(M.dist(a,b)<1e-7)return;this.doc.transaction('Add dimension',p=>p.measurements.push({id:M.uid('dim'),a:a.slice(),b:b.slice(),label:''}));this.toast(M.formatLength(M.dist(a,b),this.doc.project.units),'success');}
 fit(){const ids=this.selection.size?descendants(this.doc.project,this.selection):null;this.renderer.camera.fit(projectBounds(this.doc.project,ids));this.renderer.requestRender();this.tools.overlay();}
 scheduleSave(){clearTimeout(this.autoTimer);this.unsavedLocal=true;$('#save-status').textContent='Unsaved changes';this.autoTimer=setTimeout(async()=>{const revision=this.doc.revision;try{await this.platform.saveWorkspace(this.doc.project,this.renderer.camera.save());if(!this.disposed&&revision===this.doc.revision){this.unsavedLocal=false;$('#save-status').textContent='Saved on this device';}}catch(e){if(this.disposed)return;$('#save-status').textContent='Local save unavailable';this.toast('Autosave failed. Use Save model to download your work. '+e.message,'warning');}},1200);}
 renderPanels(){const p=this.doc.project;$('#project-name').textContent=p.name;$('#breadcrumb-name').textContent=p.name;$('#project-format').textContent=p.source?.type?.toUpperCase()||'TAKE';$('#source-badge').textContent=p.source?'IMPORTED MODEL':'LOCAL MODEL';$('#object-count').textContent=nice(p.nodes.filter(n=>n.mesh).length)+' objects';$('#save-status').textContent=this.unsavedLocal?'Unsaved changes':this.doc.dirty?'Saved on this device':'Local workspace';$('#undo-button').disabled=!this.doc.undoStack.length;$('#redo-button').disabled=!this.doc.redoStack.length;$('#units-button').textContent=({m:'Meters',mm:'Millimeters',cm:'Centimeters',in:'Inches',ft:'Feet'}[p.units]||'Meters')+' ⌄';this.renderOutliner();this.renderEntity();this.renderTags();this.renderMaterials();this.renderScenes();$('#section-toggle').checked=p.section.enabled;$('#section-axis').value=p.section.axis;$('#section-options').classList.toggle('hidden',!p.section.enabled);const b=projectBounds(p),axis={x:0,y:1,z:2}[p.section.axis];$('#section-slider').min=Math.min(b.min[axis]-1,p.section.value);$('#section-slider').max=Math.max(b.max[axis]+1,p.section.value);$('#section-slider').value=p.section.value;$('#section-value').textContent=M.formatLength(p.section.value,p.units);}
 renderOutliner(){const p=this.doc.project,query=$('#outliner-search').value.toLowerCase(),children=new Map(),byId=new Map(p.nodes.map(n=>[n.id,n])),included=new Set();for(const n of p.nodes){const key=n.parent||'';if(!children.has(key))children.set(key,[]);children.get(key).push(n);if(query&&n.name.toLowerCase().includes(query)){let v=n;while(v){included.add(v.id);v=byId.get(v.parent);}}}
  const rows=[];const walk=(parent,depth)=>{for(const n of children.get(parent)||[]){if(query&&!included.has(n.id))continue;const has=children.has(n.id),expanded=this.expanded.has(n.id)||!!query;rows.push(`<div class="tree-row${this.selection.has(n.id)?' selected':''}${n.visible===false?' dimmed':''}" role="treeitem" aria-level="${depth+1}" aria-selected="${this.selection.has(n.id)}" style="padding-left:${8+depth*14}px"><button class="tree-expander${!has?' invisible':''}" data-action="expand-node" data-id="${esc(n.id)}" aria-label="Expand ${esc(n.name)}">${expanded?'⌄':'›'}</button><button class="tree-name" data-node="${esc(n.id)}" title="${esc(n.name)}">${icon(n.mesh?'box':'group',15)}<span>${esc(n.name||'Object')}</span>${n.locked?icon('lock',11):''}</button><button class="tree-visibility" data-action="node-visibility" data-id="${esc(n.id)}" title="Toggle visibility">${icon(n.visible===false?'eyeoff':'eye',14)}</button></div>`);if(has&&expanded)walk(n.id,depth+1);}};walk('',0);$('#outliner').innerHTML=rows.join('')||'<div class="empty-state">Your model starts here.<br>Draw a face or import a file.</div>';$('#outliner-total').textContent=nice(p.nodes.length)+' entities';}
 renderEntity(){const p=this.doc.project;$('#selection-count').textContent=this.selection.size;const root=p.nodes.find(n=>this.selection.has(n.id));if(!root){$('#entity-info').innerHTML=`<div class="entity-empty">${icon('select',25)}<p>Nothing selected</p><small>Select an object to see its properties.</small></div>`;return;}
  const ids=descendants(p,this.selection),bound=projectBounds(p,ids),size=M.extent(bound),entry=sceneEntries(p).find(e=>e.node.id===root.id),mesh=p.meshes[root.mesh],sourceFace=this.face&&mesh?.faces.find(f=>f.id===this.face.faceId),units=p.units,fmt=v=>M.formatLength(v,units);let html=`<div class="entity-title">${icon(sourceFace?'rectangle':root.mesh?'box':'group',19)}<input data-property="node-name" value="${esc(root.name)}" aria-label="Object name"><button class="tiny-button" data-action="lock" title="Toggle lock">${icon(root.locked?'lock':'select',15)}</button></div><div class="entity-type">${this.selection.size>1?this.selection.size+' selected objects':sourceFace?'Face · '+sourceFace.loops.length+' boundary loops':root.component?'Component instance':root.mesh?'Mesh object':'Group'}</div>`;
  if(this.vertex!=null&&mesh?.vertices[this.vertex]){html+=`<div class="property-caption">VERTEX ${this.vertex} · LOCAL COORDINATES</div><div class="transform-fields">${mesh.vertices[this.vertex].map((v,i)=>`<label><span>${'XYZ'[i]}</span><input data-property="vertex-${i}" value="${fmt(v)}" aria-label="Vertex ${'XYZ'[i]}"></label>`).join('')}</div>`;}
  html+=`<div class="properties-grid"><span>Width / height / depth</span><strong>${size.map(fmt).join(' × ')}</strong>${mesh?`<span>Geometry</span><strong>${nice(mesh.vertices.length)} vertices · ${nice(mesh.faces.length)} faces</strong><span>Shared instances</span><strong>${p.nodes.filter(n=>n.mesh===mesh.id).length}</strong>`:''}</div><div class="property-caption">POSITION · LOCAL</div><div class="transform-fields">${[0,1,2].map(i=>`<label><span>${'XYZ'[i]}</span><input data-property="position-${i}" value="${fmt(root.matrix[12+i])}" aria-label="Position ${'XYZ'[i]}" ${root.locked?'disabled':''}></label>`).join('')}</div><div class="input-row"><label class="quiet" for="entity-tag">Tag</label><select id="entity-tag" data-property="node-tag">${p.tags.map(t=>`<option value="${esc(t.id)}" ${t.id===root.tag?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div><div class="entity-actions"><button class="small-button" data-action="duplicate">Duplicate</button><button class="small-button" data-action="unique">Make unique</button><button class="small-button" data-action="inspect">Inspect</button></div>`;
  if(sourceFace)html+=`<div class="entity-actions"><button class="small-button" data-action="reverse-face">Reverse face</button><button class="small-button" data-action="delete-face">Erase face</button><button class="small-button" data-action="vertex-tool">Edit vertex</button></div>`;$('#entity-info').innerHTML=html;
 }
 renderTags(){$('#tags-list').innerHTML=this.doc.project.tags.map(t=>`<div class="tag-row"><button class="tag-visibility" data-action="tag-visibility" data-id="${esc(t.id)}" title="Toggle tag visibility">${icon(t.visible===false?'eyeoff':'eye',15)}</button><i style="background:${esc(/^#[\da-f]{6}$/i.test(t.color)?t.color:'#859382')}"></i><button class="tag-name" data-action="rename-tag" data-id="${esc(t.id)}">${esc(t.name)}</button><span>${this.doc.project.nodes.filter(n=>n.tag===t.id).length}</span></div>`).join('');}
 renderMaterials(){const mats=this.doc.project.materials,usedTextures=new Set(mats.map(m=>m.texture));for(const [texture,url] of this.previewURLs)if(!usedTextures.has(texture)){this.platform.revokeImageURL(url);this.previewURLs.delete(texture);}const preview=m=>{if(!m.texture?.bytes?.length)return '';let url=this.previewURLs.get(m.texture);if(!url){url=this.platform.imageURL(m.texture.bytes,m.texture.mime);this.previewURLs.set(m.texture,url);}return `<img src="${url}" alt="" loading="lazy">`;};this.activeMaterial=M.clamp(this.activeMaterial,0,Math.max(0,mats.length-1));$('#material-grid').innerHTML=mats.map((m,i)=>`<button class="material-card${i===this.activeMaterial?' active':''}" data-action="choose-material" data-index="${i}" title="${esc(m.name)}"><span class="material-swatch${m.texture?' textured':''}" style="--swatch:${colorHex(m.color)}">${preview(m)}</span><span>${esc(m.name)}</span></button>`).join('');const m=mats[this.activeMaterial];if(!m)return;$('#material-editor').innerHTML=`<div class="section-heading"><h2>MATERIAL PROPERTIES</h2></div><label class="field-label">Name<input data-property="material-name" value="${esc(m.name)}"></label><div class="input-row"><label class="quiet">Base color</label><input type="color" value="${colorHex(m.color)}" data-property="material-color" aria-label="Material color"></div><label class="range-label"><span>Roughness</span><input type="range" min=".04" max="1" step=".01" value="${m.roughness??.7}" data-property="material-roughness"></label><label class="range-label"><span>Metallic</span><input type="range" min="0" max="1" step=".01" value="${m.metalness??0}" data-property="material-metalness"></label><label class="range-label"><span>Opacity</span><input type="range" min=".03" max="1" step=".01" value="${m.color[3]}" data-property="material-opacity"></label><div class="texture-info">${m.texture?'Embedded texture · '+bytes(m.texture.bytes.length):'No texture assigned'}</div><div class="entity-actions"><button class="small-button" data-action="load-texture">Load texture</button>${m.texture?'<button class="small-button" data-action="remove-texture">Remove</button>':''}</div><button class="button primary full-width" data-action="paint-selection">Apply to selection</button><p class="panel-intro">Face edits affect shared component geometry. Use Make unique for an independent copy.</p>`;}
 renderScenes(){$('#scene-list').innerHTML=this.doc.project.scenes.map((s,i)=>`<div class="scene-card"><button data-action="restore-scene" data-index="${i}"><span class="scene-thumb">${icon('camera',24)}</span><strong>${esc(s.name)}</strong><small>${s.camera?.orthographic?'Parallel projection':'Perspective'}</small></button><button class="tiny-button" data-action="delete-scene" data-index="${i}" title="Delete saved view">×</button></div>`).join('')||'<div class="empty-state">A new perspective is one click away.<br>Save your first view below.</div>';}
 propertyChange(e){const property=e.target.dataset.property;if(!property)return;const value=e.target.value,root=this.doc.project.nodes.find(n=>this.selection.has(n.id));
  if(property.startsWith('material-')){this.doc.transaction('Edit material',p=>{const m=p.materials[this.activeMaterial],key=property.slice(9);if(key==='name')m.name=value.slice(0,200);if(key==='color')m.color=[...readColor(value),m.color[3]];if(key==='opacity')m.color[3]=Number(value);if(key==='roughness'||key==='metalness')m[key]=Number(value);});return;}
  if(!root)return;if(root.locked)throw Error('Unlock this object first.');if(property.startsWith('vertex-')){if(!this.face||this.vertex==null)return;const axis=Number(property.slice(-1)),n=M.parseLength(value,this.doc.project.units),vertex=this.vertex,hit=this.face;if(!Number.isFinite(n))throw Error('Invalid coordinate.');this.editMesh('Move vertex',hit,m=>{const copy=G.cloneMesh(m);copy.vertices[vertex][axis]=n;for(const f of copy.faces){f.normal=undefined;f.cornerNormals=undefined;}const bad=G.bakeMesh(copy).errors;if(bad.length)throw Error('This edit produces invalid faces. Move within the face plane or triangulate it first.');return copy;});return;}
  this.doc.transaction('Edit object',p=>{const n=p.nodes.find(n=>n.id===root.id);if(property==='node-name')n.name=value.slice(0,200);if(property==='node-tag')n.tag=value;if(property.startsWith('position-')){const axis=Number(property.slice(-1)),v=M.parseLength(value,p.units);if(!Number.isFinite(v))throw Error('Invalid position.');n.matrix[12+axis]=v;}});
 }
 async action(action,button={dataset:{}}){const d=button.dataset||{},p=this.doc.project;
  switch(action){
   case 'undo':this.tools.cancel();this.face=null;this.doc.undo();break;case 'redo':this.tools.cancel();this.face=null;this.doc.redo();break;
   case 'open':await this.pickModelFiles(false);break;case 'import':await this.pickModelFiles(true);break;case 'save':{const revision=this.doc.revision;const saved=await this.download(exportTAKE(p),nameFile(p.name)+'.take');if(saved!==false&&revision===this.doc.revision){this.unsavedLocal=false;this.doc.dirty=false;$('#save-status').textContent=this.platform.saveLabel;await this.platform.saveWorkspace(p,this.renderer.camera.save()).catch(()=>{});}break;}
   case 'new':if(await this.confirmReplace()){this.select(null);this.doc.replace(newProject());this.tools.set('rectangle');this.fit();}break;
   case 'load-sample':if(await this.confirmReplace()){this.closeModal();await this.loadSample(false);}break;
   case 'rename-project':this.prompt('Name your model','Project name',p.name,value=>this.doc.transaction('Rename model',q=>q.name=value||'Untitled model'));break;
   case 'fit':this.fit();break;case 'view-iso':this.renderer.camera.preset('iso');this.renderer.requestRender();break;
   case 'projection':this.renderer.camera.orthographic=!this.renderer.camera.orthographic;$('#projection-toggle').textContent=this.renderer.camera.orthographic?'Parallel':'Perspective';this.renderer.requestRender();break;
   case 'workspace-model':$$('.workspace-tab').forEach(b=>b.classList.toggle('active',b.dataset.action===action));this.tools.set('select');break;
   case 'workspace-inspect':$$('.workspace-tab').forEach(b=>b.classList.toggle('active',b.dataset.action===action));this.inspect();break;
   case 'expand-node':this.expanded.has(d.id)?this.expanded.delete(d.id):this.expanded.add(d.id);this.renderOutliner();break;
   case 'expand-all':p.nodes.forEach(n=>this.expanded.add(n.id));this.renderOutliner();break;case 'collapse-all':this.expanded.clear();this.renderOutliner();break;
   case 'node-visibility':this.doc.transaction('Toggle visibility',q=>{const n=q.nodes.find(n=>n.id===d.id);n.visible=n.visible===false;});break;
   case 'tag-visibility':this.doc.transaction('Toggle tag',q=>{const t=q.tags.find(t=>t.id===d.id);t.visible=t.visible===false;});break;
   case 'rename-tag':{const t=p.tags.find(t=>t.id===d.id);this.prompt('Rename tag','Tag name',t.name,value=>this.doc.transaction('Rename tag',q=>q.tags.find(t=>t.id===d.id).name=value));break;}
   case 'add-tag':this.prompt('Organize your model','New tag name','New tag',name=>this.doc.transaction('Add tag',q=>q.tags.push({id:M.uid('tag'),name,visible:true,color:'#8b9e83'})));break;
   case 'choose-material':this.activeMaterial=Number(d.index);this.renderMaterials();this.tools.set('paint');break;
   case 'add-material':this.doc.transaction('New material',q=>{q.materials.push(makeMaterial('Material '+q.materials.length));this.activeMaterial=q.materials.length-1;});this.tab('materials');break;
   case 'paint-selection':this.paintSelection();break;case 'load-texture':if(this.platform.pickFiles){const files=await this.platform.pickFiles('image');if(files[0])await this.setTextureFile(files[0]);}else $('#texture-input').click();break;case 'remove-texture':this.doc.transaction('Remove texture',q=>q.materials[this.activeMaterial].texture=null);break;
   case 'section':this.doc.transaction('Toggle section',q=>q.section.enabled=!q.section.enabled);break;case 'flip-section':this.doc.transaction('Flip section',q=>q.section.flip=!q.section.flip);break;
   case 'toggle-snap':this.tools.snapEnabled=!this.tools.snapEnabled;$('#snap-toggle').classList.toggle('active',this.tools.snapEnabled);break;
   case 'group':this.group();break;case 'ungroup':this.ungroup();break;case 'component':this.makeComponent();break;case 'unique':this.makeUnique();break;
   case 'duplicate':this.duplicate();break;case 'copy':this.copy();break;case 'paste':this.paste();break;case 'delete':this.deleteSelection();break;case 'delete-face':this.deleteFace();break;
   case 'select-all':this.selectMany(p.nodes.filter(n=>!n.parent&&n.visible!==false).map(n=>n.id));break;case 'deselect':this.select(null);break;
   case 'hide':{const roots=this.selectedRoots();if(!roots.length)return;this.doc.transaction('Hide selection',q=>roots.forEach(root=>q.nodes.find(n=>n.id===root.id).visible=false));this.select(null);break;}
   case 'unhide':this.doc.transaction('Show all',q=>{q.nodes.forEach(n=>n.visible=true);q.tags.forEach(t=>t.visible=true);});break;
   case 'lock':{const roots=this.selectedRoots();this.doc.transaction('Toggle lock',q=>roots.forEach(root=>{const n=q.nodes.find(n=>n.id===root.id);n.locked=!n.locked;}));break;}
   case 'box':this.primitiveDialog('box');break;case 'sphere':this.primitiveDialog('sphere');break;case 'sweep':this.sweepDialog();break;
   case 'union':case 'subtract':case 'intersect':await this.boolean(action);break;
   case 'reverse-face':if(!this.face)throw Error('Double-click a face first.');this.editMesh('Reverse face',this.face,m=>{const copy=G.cloneMesh(m),f=copy.faces.find(f=>f.id===this.face.faceId);f.loops=f.loops.map(l=>l.slice().reverse());f.uv=f.uv?.map(l=>l.slice().reverse());f.cornerNormals=undefined;f.normal=undefined;return copy;});break;
   case 'vertex-tool':this.tools.set('vertex');this.toast('Click near a vertex on a face, then edit its coordinates in Entity Info.');break;
   case 'triangulate':this.triangulateSelection();break;case 'weld':this.weldSelection();break;
   case 'save-scene':this.prompt('Save this perspective','View name','View '+(p.scenes.length+1),name=>this.doc.transaction('Save view',q=>q.scenes.push({id:M.uid('scene'),name,camera:this.renderer.camera.save(),tags:q.tags.map(t=>[t.id,t.visible]),section:{...q.section}})));break;
   case 'restore-scene':{const s=p.scenes[Number(d.index)];this.renderer.camera.restore(s.camera);this.doc.transaction('Restore view',q=>{q.section={...s.section};for(const [id,visible] of s.tags||[]){const t=q.tags.find(t=>t.id===id);if(t)t.visible=visible;}});break;}
   case 'delete-scene':this.doc.transaction('Delete view',q=>q.scenes.splice(Number(d.index),1));break;
   case 'clear-dimensions':this.doc.transaction('Clear dimensions',q=>q.measurements=[]);break;
   case 'export':this.exportDialog();break;case 'screenshot':if(!this.ready)throw Error('The GPU must be running to capture a viewport.');await this.download(await this.renderer.screenshot(),nameFile(p.name)+'.png');break;
   case 'settings':this.settings();break;case 'shortcuts':this.help();break;case 'about':this.about();break;case 'command':this.commandPalette();break;case 'inspect':this.inspect();break;case 'diagnostics':this.diagnostics();break;case 'import-report':this.importReport();break;
   case 'reload-gpu':await this.reloadGPU();break;case 'forget-workspace':await this.platform.clearWorkspace();this.toast('Saved recovery data cleared. The current model is unchanged.');break;
   case 'close-modal':this.closeModal();break;case 'confirm-modal':{const fn=this.modalResolve;this.modalResolve=null;this.closeModal();fn?.(true);break;}
   default:if(action.startsWith('tool:'))this.tools.set(action.slice(5));else throw Error('Unknown command: '+action);
  }
 }
 group(){const roots=this.editableRoots(),entries=new Map(sceneEntries(this.doc.project).map(e=>[e.node.id,e])),id=M.uid('group');this.doc.transaction('Group objects',p=>{p.nodes.push(makeNode('Group',null,{id}));for(const r of roots){const n=p.nodes.find(n=>n.id===r.id);n.matrix=entries.get(r.id).matrix.slice();n.parent=id;}});this.expanded.add(id);this.select(id);}
 ungroup(){const groups=this.editableRoots().filter(n=>!n.mesh);if(!groups.length)throw Error('Select a group in the Outliner.');const ids=new Set(groups.map(n=>n.id)),entries=new Map(sceneEntries(this.doc.project).map(e=>[e.node.id,e]));this.doc.transaction('Ungroup',p=>{for(const n of p.nodes)if(ids.has(n.parent)){n.matrix=entries.get(n.id).matrix.slice();n.parent=null;}p.nodes=p.nodes.filter(n=>!ids.has(n.id));});this.select(null);}
 makeComponent(){const roots=this.editableRoots();this.doc.transaction('Make component',p=>{for(const r of roots)p.nodes.find(n=>n.id===r.id).component=r.mesh||M.uid('component');});this.toast('Component created. Duplicate shares its mesh definitions.','success');}
 makeUnique(){const roots=this.editableRoots(),ids=descendants(this.doc.project,new Set(roots.map(n=>n.id)));this.doc.transaction('Make unique',p=>{const meshes=new Map();for(const n of p.nodes){if(!ids.has(n.id))continue;if(n.mesh){let id=meshes.get(n.mesh);if(!id){const m=G.cloneMesh(p.meshes[n.mesh]);m.id=M.uid('m');id=m.id;meshes.set(n.mesh,id);p.meshes[id]=m;}n.mesh=id;}if(n.component)n.component=M.uid('component');}});this.toast('Selection now has independent geometry.','success');}
 copy(){if(!this.selection.size)throw Error('Select objects to copy.');const ids=descendants(this.doc.project,this.selection),entries=new Map(sceneEntries(this.doc.project).map(e=>[e.node.id,e]));this.clipboard={nodes:this.doc.project.nodes.filter(n=>ids.has(n.id)).map(n=>({...n,matrix:ids.has(n.parent)?n.matrix.slice():entries.get(n.id).matrix.slice(),parent:ids.has(n.parent)?n.parent:null})),meshes:{...this.doc.project.meshes},materials:this.doc.project.materials,tags:this.doc.project.tags,project:this.doc.project.name};this.toast('Selection copied locally.');}
 paste(){if(!this.clipboard)throw Error('Copy an object first.');const c=this.clipboard,map=new Map(c.nodes.map(n=>[n.id,M.uid('n')])),roots=[];this.doc.transaction('Paste',p=>{const matMap=new Map();c.materials.forEach((m,i)=>{let target=p.materials.findIndex(x=>x.id===m.id);if(target<0){target=p.materials.length;p.materials.push(m);}matMap.set(i,target);});for(const t of c.tags)if(!p.tags.some(x=>x.id===t.id))p.tags.push({...t});for(const n of c.nodes){if(n.mesh&&!p.meshes[n.mesh]){const m=G.cloneMesh(c.meshes[n.mesh]);for(const f of m.faces)if(f.material!=null)f.material=matMap.get(f.material)??0;p.meshes[n.mesh]=m;}const node={...n,id:map.get(n.id),parent:n.parent?map.get(n.parent):null,matrix:n.parent?n.matrix.slice():M.mmul(M.translation([.5,0,.5]),n.matrix),material:n.material==null?null:matMap.get(n.material)};if(!n.parent)roots.push(node.id);p.nodes.push(node);}});this.selectMany(roots);}
 duplicate(){this.copy();this.paste();}
 triangulateSelection(){const roots=this.editableRoots(),ids=descendants(this.doc.project,new Set(roots.map(n=>n.id))),meshIds=new Set(this.doc.project.nodes.filter(n=>ids.has(n.id)&&n.mesh).map(n=>n.mesh));this.doc.transaction('Triangulate faces',p=>{for(const id of meshIds){const source=p.meshes[id],b=G.bakeMesh(source);if(b.errors.length)throw Error('A face could not be triangulated.');const copy=G.cloneMesh(source);copy.faces=b.triangles.map(t=>G.face([[t.a,t.b,t.c]],source.faces[t.face].material));copy.edges=[];p.meshes[id]=copy;}});this.face=null;}
 weldSelection(){const roots=this.editableRoots(),ids=descendants(this.doc.project,new Set(roots.map(n=>n.id))),meshIds=new Set(this.doc.project.nodes.filter(n=>ids.has(n.id)&&n.mesh).map(n=>n.mesh));this.doc.transaction('Weld vertices',p=>{for(const id of meshIds)p.meshes[id]=G.weld(p.meshes[id],1e-6);});}
 async boolean(operation){const roots=this.editableRoots();if(roots.length!==2||roots.some(n=>!n.mesh))throw Error('Select exactly two mesh objects. Ungroup imported hierarchy as needed. Selection order is the operand order.');const ordered=[...this.selection].map(id=>roots.find(n=>n.id===id)).filter(Boolean),entries=new Map(sceneEntries(this.doc.project).map(e=>[e.node.id,e])),[a,b]=ordered,ea=entries.get(a.id),eb=entries.get(b.id);const revision=this.doc.revision;this.showLoading('Computing '+operation+'…',35,true);try{const result=await new Promise((resolve,reject)=>{const w=this.platform.createWorker('operation');this.loadWorker=w;this.loadReject=reject;w.onmessage=({data})=>{w.terminate();data.type==='error'?reject(Error(data.message)):resolve(data.mesh);};w.onerror=e=>{w.terminate();reject(Error(e.message));};w.postMessage({a:this.doc.project.meshes[a.mesh],b:this.doc.project.meshes[b.mesh],operation,options:{aMatrix:ea.matrix,bMatrix:eb.matrix,aMaterial:ea.material,bMaterial:eb.material}});});if(this.doc.revision!==revision)throw Error('The model changed during the operation. Run the boolean again.');let id;this.doc.transaction(operation,p=>{p.nodes=p.nodes.filter(n=>n.id!==a.id&&n.id!==b.id);p.meshes[result.id]=result;const n=makeNode(result.name,result.id);id=n.id;p.nodes.push(n);purge(p);});this.select(id);this.toast(result.name+' complete.','success');}finally{this.loadWorker=null;this.hideLoading();}}
 primitiveDialog(kind){this.modal(kind==='box'?'Build a box':'Build a sphere',`<form id="primitive-form"><p class="modal-intro">Create exact geometry in model space. Dimensions accept units such as 2400 mm or 8 ft.</p>${kind==='box'?'<label class="field-label">Width, height, depth<input name="dimensions" value="2 m, 2 m, 2 m" required autofocus></label>':'<label class="field-label">Radius<input name="radius" value="1 m" required autofocus></label>'}<label class="field-label">World position · X, Y, Z<input name="position" value="0 m, 0 m, 0 m"></label><div class="modal-actions"><button type="button" class="button secondary" data-action="close-modal">Cancel</button><button class="button primary">Create ${kind}</button></div></form>`,async data=>{const values=String(data.get('position')).split(',').map(x=>M.parseLength(x,this.doc.project.units));if(values.length!==3)throw Error('Enter three position coordinates.');let m;if(kind==='box'){const d=String(data.get('dimensions')).split(',').map(x=>M.parseLength(x,this.doc.project.units));if(d.length!==3||d.some(x=>x<=0))throw Error('Enter three positive dimensions.');m=G.box(...d);}else{const r=M.parseLength(String(data.get('radius')),this.doc.project.units);if(r<=0)throw Error('Radius must be positive.');m=G.sphere(r);}m=G.transformMesh(m,M.translation(toWorld(values)));this.addGeometry(m);this.closeModal();this.fit();});}
 sweepDialog(){this.modal('Sweep a profile',`<form><p class="modal-intro">Sweep a rectangular section along an explicit 3D path. Coordinates are in the selected document units; each line is X, Y, Z. Tight bends can self-intersect.</p><label class="field-label">Profile width, height<input name="profile" value="0.2 m, 0.2 m"></label><label class="field-label">Path points<textarea name="path" rows="5">0, 0, 0\n0, 2, 0\n2, 2, 0</textarea></label><div class="modal-actions"><button type="button" class="button secondary" data-action="close-modal">Cancel</button><button class="button primary">Create sweep</button></div></form>`,data=>{const parse=s=>M.parseLength(s,this.doc.project.units),wh=String(data.get('profile')).split(',').map(parse),path=String(data.get('path')).trim().split('\n').map(s=>s.split(',').map(parse));if(wh.length!==2||wh.some(x=>x<=0)||path.some(p=>p.length!==3))throw Error('Check the profile dimensions and path coordinates.');if(path.length>512)throw Error('Use at most 512 path points.');const [w,h]=wh;const m=G.sweep([[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]],path.map(toWorld));this.addGeometry(m);this.closeModal();this.fit();});}
 download(blob,name){return this.platform.download(blob,name);}
 exportDialog(){this.modal('Take your model further',`<form><p class="modal-intro">Native projects preserve editable topology, components, tags, materials, dimensions, and saved views. Exchange formats preserve their supported geometry and appearance.</p><div class="export-options">${[['take','SingleTake project','Editable project with embedded textures'],['glb','glTF binary · GLB','Instanced mesh scene, PBR colors and textures'],['obj','Wavefront · OBJ ZIP','Geometry + MTL + texture assets'],['stl','Binary STL','Triangulated geometry · meters'],['ply','PLY','Triangulated geometry and vertex colors'],['dxf','DXF mesh','3DFACE and LINE entities · meters, Z up']].map(([v,n,t],i)=>`<label class="export-option"><input type="radio" name="format" value="${v}" ${i===1?'checked':''}><span><strong>${n}</strong><small>${t}</small></span></label>`).join('')}</div><label class="check-label"><input type="checkbox" name="selection" ${this.selection.size?'':'disabled'}> Export selected objects only (exchange formats)</label><p class="compat-note">This build reads modern SKP but does not write native SKP, DWG, IFC, or STEP. Hidden objects are excluded from exchange exports. Section clipping is a display cut, not an exported solid cut.</p><div class="modal-actions"><button type="button" class="button secondary" data-action="close-modal">Cancel</button><button class="button primary">Export model ↗</button></div></form>`,async data=>{const format=String(data.get('format')),selected=data.get('selection')?this.selection:null;const blob=await exportFormat(this.doc.project,format,selected);const saved=await this.download(blob,nameFile(this.doc.project.name)+'.'+DOWNLOAD_EXT[format]);if(saved===false)return;this.closeModal();this.toast('Exported '+format.toUpperCase()+' · '+bytes(blob.size),'success');});}
 showLoading(message,progress=20,cancel=false){$('#loading').classList.remove('hidden');$('#loading-message').textContent=message;$('#loading-progress').style.width=M.clamp(progress,0,100)+'%';$('#cancel-load').classList.toggle('hidden',!cancel);}
 hideLoading(){$('#loading').classList.add('hidden');this.loadWorker=null;this.loadReject=null;}
 async loadSample(){return this.pickModelFiles(false);}
 async openFiles(files,append=false){const model=files.find(f=>/\.(skp|glb|gltf|obj|stl|ply|dxf|take|json)$/i.test(f.name));if(!model)throw Error('Choose a model file together with any referenced textures, MTL, or BIN files.');if(files.reduce((s,f)=>s+f.size,0)>350*1048576)throw Error('Selected files exceed the 350 MB import safety limit.');this.showLoading('Reading '+model.name+'…',5,true);try{const items=await Promise.all(files.map(async f=>({name:f.name,buffer:await f.arrayBuffer()})));await this.importBuffers(items,model.name,append);}finally{this.hideLoading();}}
 async importBuffers(files,name,append=false){this.loadingModel=true;try{const project=await new Promise((resolve,reject)=>{const worker=this.platform.createWorker('import');this.loadWorker=worker;this.loadReject=reject;worker.onmessage=({data})=>{if(data.type==='progress'){const info=data.progress||data;this.showLoading(info.message||info.stage||'Building editable geometry…',info.percent||info.progress||45,true);}else if(data.type==='complete'){worker.terminate();resolve(data.project);}else if(data.type==='error'){worker.terminate();reject(Error(data.message));}};worker.onerror=e=>{worker.terminate();reject(Error(e.message||'Import worker failed.'));};worker.postMessage({files,name,scale:this.importScale},files.map(f=>f.buffer));});validateProject(project);this.selection.clear();this.face=null;this.vertex=null;this.expanded.clear();for(const n of project.nodes.filter(n=>!n.parent))this.expanded.add(n.id);if(append)this.mergeProject(project);else this.doc.replace(project);this.activeMaterial=0;if(this.ready){this.showLoading('Uploading geometry and textures to the GPU…',90,true);await this.renderer.setProject(this.doc.project);this.fit();}this.tools.cancel();this.toast(name+' imported as editable geometry.','success');const report=project.source?.report;if(report?.warnings?.length)this.toast('Import completed with notes. See Scenes → View import report.','warning');}finally{this.loadingModel=false;this.hideLoading();}}
 mergeProject(source){const groupId=M.uid('import');this.doc.transaction('Import '+source.name,p=>{const matMap=new Map(),tagMap=new Map(),meshMap=new Map(),nodeMap=new Map();source.materials.forEach((m,i)=>{matMap.set(i,p.materials.length);p.materials.push({...m,id:M.uid('mat'),color:m.color.slice()});});for(const t of source.tags){if(t.id==='0')tagMap.set(t.id,'0');else{const copy={...t,id:M.uid('tag')};tagMap.set(t.id,copy.id);p.tags.push(copy);}}for(const m of Object.values(source.meshes)){const copy=G.cloneMesh(m);copy.id=M.uid('m');for(const f of copy.faces){if(f.material!=null)f.material=matMap.get(f.material)??0;if(f.backMaterial!=null)f.backMaterial=matMap.get(f.backMaterial)??0;f.tag=tagMap.get(f.tag)||'0';}meshMap.set(m.id,copy.id);p.meshes[copy.id]=copy;}for(const n of source.nodes)nodeMap.set(n.id,M.uid('n'));p.nodes.push(makeNode(source.name,null,{id:groupId}));for(const n of source.nodes)p.nodes.push({...n,id:nodeMap.get(n.id),mesh:meshMap.get(n.mesh)||null,parent:n.parent?nodeMap.get(n.parent):groupId,matrix:n.matrix.slice(),material:n.material==null?null:matMap.get(n.material),tag:tagMap.get(n.tag)||'0'});p.imports=[...(p.imports||[]),{name:source.name,source:source.source?.report||null}];});this.expanded.add(groupId);this.select(groupId);}
 async confirmReplace(){if(!this.doc.dirty)return true;return new Promise(resolve=>{this.modalResolve=resolve;this.modal('Replace the current model?',`<p class="modal-intro">Download the current project with Save model before replacing it. Opening another model replaces this device’s recovery workspace.</p><div class="modal-actions"><button class="button secondary" data-action="close-modal">Keep working</button><button class="button primary" data-action="confirm-modal">Replace model</button></div>`);});}
 modal(title,body,onSubmit=null){this.modalSubmit=onSubmit;$('#dialog-content').innerHTML=`<div class="modal-heading"><div><span class="eyebrow">SINGLETAKE WORKSPACE</span><h2>${esc(title)}</h2></div><button class="icon-button" data-action="close-modal" aria-label="Close">${icon('close')}</button></div>${body}`;showDialog($('#dialog'));requestAnimationFrame(()=>$('#dialog-content [autofocus],#dialog-content input:not([type=radio]):not([type=checkbox])')?.focus());}
 closeModal(){closeDialog($('#dialog'));this.modalSubmit=null;const fn=this.modalResolve;this.modalResolve=null;fn?.(false);this.canvas.focus();}
 prompt(title,label,value,callback){this.modal(title,`<form><label class="field-label">${esc(label)}<input name="value" value="${esc(value)}" maxlength="200" required autofocus></label><div class="modal-actions"><button type="button" class="button secondary" data-action="close-modal">Cancel</button><button class="button primary">Save</button></div></form>`,data=>{callback(String(data.get('value')).trim());this.closeModal();});}
 settings(){this.modal('Your workspace',`<form><div class="settings-grid"><label class="field-label">Display units<select name="units">${[['m','Meters'],['mm','Millimeters'],['cm','Centimeters'],['in','Inches'],['ft','Feet']].map(([v,n])=>`<option value="${v}" ${this.doc.project.units===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field-label">Unitless import coordinates<select name="importScale">${[['1','Meters'],['.001','Millimeters'],['.01','Centimeters'],['.0254','Inches'],['.3048','Feet']].map(([v,n])=>`<option value="${v}" ${this.importScale===Number(v)?'selected':''}>${n}</option>`).join('')}</select></label><label class="field-label">Grid snap spacing · 0 disables<input name="snap" value="${M.formatLength(this.tools.snapStep,this.doc.project.units)}"></label><label class="field-label">Render resolution<select name="resolution" ${this.renderer.capabilities?.renderResolution===false?'disabled title="The native presenter currently renders at full display resolution."':''}>${[[1,'Full'],[.75,'75%'],[.5,'50%']].map(([v,n])=>`<option value="${v}" ${this.renderer.resolution===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field-label">Exposure<input name="exposure" type="number" min=".1" max="5" step=".1" value="${this.renderer.exposure}"></label><label class="field-label">Perspective field of view<input name="fov" type="number" min="15" max="100" value="${Math.round(this.renderer.camera.fov*180/Math.PI)}"></label></div><p class="compat-note">Modeling coordinates use meters and Z up; the GPU uses a converted frame. Changing display units does not resize geometry. SKP and glTF define their own scale. Other imports use the coordinate unit selected above.</p><div class="modal-actions"><button type="button" class="button secondary" data-action="forget-workspace">Clear recovery data</button><button class="button primary">Apply settings</button></div></form>`,data=>{const snap=M.parseLength(String(data.get('snap')),this.doc.project.units);if(snap<0)throw Error('Snap spacing cannot be negative. Use zero to disable grid snapping.');this.tools.snapStep=snap;this.importScale=Number(data.get('importScale'));if(data.has('resolution'))this.renderer.resolution=Number(data.get('resolution')); this.renderer.exposure=Number(data.get('exposure'));this.renderer.camera.fov=Number(data.get('fov'))*Math.PI/180;this.doc.transaction('Change units',p=>p.units=String(data.get('units')));if(this.ready)this.renderer.resize();this.closeModal();});}
 inspect(){const entries=sceneEntries(this.doc.project),chosen=this.selection.size?descendants(this.doc.project,this.selection):null,ids=new Set(entries.filter(e=>e.visible&&e.node.mesh&&(!chosen||chosen.has(e.node.id))).map(e=>e.node.mesh));let result={vertices:0,faces:0,triangles:0,boundary:0,nonmanifold:0,degenerate:0,closed:0},rows=[];for(const id of ids){const m=this.doc.project.meshes[id],s=G.topology(m);for(const k of ['vertices','faces','triangles','boundary','nonmanifold','degenerate'])result[k]+=s[k];result.closed+=s.closed?1:0;if(rows.length<12)rows.push(`<tr><td>${esc(m.name)}</td><td>${nice(s.faces)}</td><td>${s.closed?'Closed':s.boundary+' open edges'}</td></tr>`);}this.modal('Geometry inspection',`<p class="modal-intro">${chosen?'Selected objects':'Visible model'} · unique mesh resources, before instance transforms.</p><div class="diagnostic-grid">${Object.entries(result).map(([k,v])=>`<div><strong>${nice(v)}</strong><span>${esc(k)}</span></div>`).join('')}</div><table class="data-table"><thead><tr><th>Mesh</th><th>Faces</th><th>Topology</th></tr></thead><tbody>${rows.join('')}</tbody></table><p class="compat-note">Closed means every boundary edge has two face uses. This check does not prove absence of self-intersections or consistent outward orientation. Polygon mesh solids are not analytic CAD B-reps.</p><div class="modal-actions"><button class="button secondary" data-action="triangulate">Triangulate selected</button><button class="button secondary" data-action="weld">Weld selected</button><button class="button primary" data-action="close-modal">Done</button></div>`);}
 importReport(){const source=this.doc.project.source;this.modal('Import report',`<p class="modal-intro">${source?'Source: '+esc(source.name||source.type):'This model was created in SingleTake.'}</p><pre class="report-code">${esc(JSON.stringify(source?.report||{format:'SingleTake native project'},null,2))}</pre><p class="compat-note">SKP compatibility is experimental, read-only, and limited to modern VFF containers. Imported faces and component transforms are editable; not all VFF model semantics are reconstructed. See docs/COMPATIBILITY.md in the source package.</p><div class="modal-actions"><button class="button primary" data-action="close-modal">Done</button></div>`);}
 diagnostics(){const r=this.renderer,geometry=[...r.cache.values()].filter(x=>x.source.id!=='__floor'),vbytes=geometry.reduce((s,x)=>s+x.groups.reduce((s,g)=>s+g.vertices.byteLength+g.indices.byteLength,0)+x.lines.byteLength+x.wire.byteLength,0),report={device:r.stats.backend,canvas:this.canvas.width+' × '+this.canvas.height,visibleInstances:r.stats.visible||0,drawCalls:r.stats.draws||0,renderedTriangles:r.stats.triangles||0,uniqueMeshBuffers:geometry.length,geometryGPUBytes:vbytes,cpuFrameEncodeMs:r.stats.cpuMs,gpuFrameMs:r.stats.gpuMs,MSAA:r.capabilities?.msaa??4,shadowMap:r.capabilities?.shadowMap??'2048 × 2048',renderMode:'On demand; no idle animation loop',deviceFeatures:r.device?[...r.device.features]:[],geometryErrors:geometry.flatMap(x=>x.errors.map(e=>({mesh:x.source.name,...e}))).slice(0,30)};this.modal('Renderer diagnostics',`<p class="modal-intro">Live values from the active renderer, not a synthetic performance claim. CPU time includes culling and command encoding; GPU timestamps appear only when supported.</p><pre class="report-code">${esc(JSON.stringify(report,null,2))}</pre><p class="compat-note">The development environment blocked browser navigation, so this package has automated geometry/import/export tests but no recorded WebGPU frame-rate benchmark.</p><div class="modal-actions"><button class="button secondary" data-action="reload-gpu">Reload GPU</button><button class="button primary" data-action="close-modal">Done</button></div>`);}
 help(){throw Error('Interaction controller was not installed.');}
 about(){this.modal('SingleTake',`<div class="about-lockup">Space to make.</div><p class="modal-intro">A local-first polygon modeler built with plain HTML, CSS, JavaScript, and a native WebGPU renderer. No framework, remote rendering, or upload service.</p><p>This is an independent engineering build, not an official VFF model product or a claim of feature parity. Local model files are parsed into editable geometry in your browser.</p><p class="compat-note">Full VFF model round-trip fidelity, legacy SKP, native SKP export, analytic CAD surfaces, IFC/DWG/STEP, extension execution, collision-stopping push/pull, and automatic intersect-and-heal topology are outside this build. The source package includes an explicit capability matrix and tests.</p><div class="modal-actions"><button class="button secondary" data-action="load-sample">Open a model</button><button class="button primary" data-action="close-modal">Explore workspace</button></div>`);}
 commands(){return [...TOOLS.map(t=>({name:t.label,action:'tool:'+t.id,key:t.key})),...Object.entries({'box':'Create box','sphere':'Create sphere','sweep':'Sweep a rectangular profile','vertex-tool':'Edit a vertex','union':'Solid union','subtract':'Solid difference · first minus second','intersect':'Solid intersection','group':'Group selection','ungroup':'Ungroup selection','component':'Make component','unique':'Make unique','duplicate':'Duplicate','hide':'Hide selection','unhide':'Show all objects and tags','lock':'Lock or unlock selection','select-all':'Select all','deselect':'Deselect','delete':'Erase selection','triangulate':'Triangulate selected mesh faces','weld':'Weld selected mesh vertices','reverse-face':'Reverse selected face','section':'Toggle section plane','clear-dimensions':'Clear dimensions','save-scene':'Save current view','inspect':'Inspect topology','diagnostics':'Renderer diagnostics','import-report':'Import compatibility report','load-sample':'Open a local model','new':'New model','open':'Open model','import':'Import another model into the scene','save':'Save native project','export':'Export model','screenshot':'Capture viewport PNG','fit':'Zoom extents','settings':'Workspace settings','shortcuts':'Keyboard shortcuts','about':'About SingleTake'}).map(([action,name])=>({action,name,key:''}))];}
 commandPalette(){const commands=this.commands();this.modal('What would you like to make?',`<div class="command-search">${icon('search')}<input id="command-search" placeholder="Find a tool or command…" autofocus></div><div id="command-results" class="command-results"></div>`);const render=()=>{const q=$('#command-search').value.toLowerCase();$('#command-results').innerHTML=commands.filter(c=>c.name.toLowerCase().includes(q)).map(c=>`<button data-command="${esc(c.action)}"><span>${esc(c.name)}</span><kbd>${esc(c.key)}</kbd></button>`).join('');$('#command-results').querySelectorAll('button').forEach(b=>b.onclick=()=>{this.closeModal();this.guard(()=>this.action(b.dataset.command));});};this.listen($('#command-search'),'input',render);this.listen($('#command-search'),'keydown',e=>{if(e.key==='Enter'){$('#command-results button')?.click();e.preventDefault();}});render();}
 context(x,y){const menu=$('#context-menu');menu.innerHTML=[['copy','Copy'],['paste','Paste'],['duplicate','Duplicate'],['group','Make group'],['unique','Make unique'],['hide','Hide'],['lock','Lock / unlock'],['fit-selection','Zoom selection'],['delete','Erase']].map(([action,name])=>`<button data-action="${action}">${icon(action,15)}<span>${name}</span></button>`).join('');menu.style.left=Math.min(x,innerWidth-210)+'px';menu.style.top=Math.min(y,innerHeight-330)+'px';menu.classList.remove('hidden');}
 hideContext(){$('#context-menu').classList.add('hidden');}
 keydown(e){throw Error('Interaction controller was not installed.');}
 async reloadGPU(){await this.platform.saveWorkspace(this.doc.project,this.renderer.camera.save());await this.renderer.dispose();await this.platform.reload();}
}
installModelInteractions(App);
